### ISSUE TITLE
ES6 modules support

### ISSUE THREAD

**Issue by jmas** [crabbly/Print.js#10]
For now PrintJS lib exports content to `window.PrintJS` variable.
It is unusable when your project is using ES6 modules.

Example how to pretty ES6 modules are looks:
```js
// In PrintJS lib:
export function print (options) {
    // ...
}

export default class PrintJS {
    // ...
}
```
```js
// In our module:
import { print } from 'printjs';

// ...

print({ /* ... */ });
```

And you can make an old-style export:
```js
import { PrintJS } from 'printjs';

winodw.PrintJS = PrintJS;
```

That is easy. :)

**Comment by jmas** [comment]
Rewrote with ES6 modules support here:  https://gist.github.com/jmas/fdc1bbedabd3f934e7e68b34574d4831

**Comment by crabbly** [comment]
Love it. I haven’t had time to work on the library in a little while. I need to work on a few issues.
It will be great to implement this and support ES6 modules.
Thank you.

**Comment by crabbly** [comment]
@jmas It should support ES6 modules now. 
https://github.com/crabbly/Print.js/releases/latest
Thank you.
