### ISSUE TITLE
Can HTML elements support class name ?

### ISSUE THREAD

**Issue by p2yang** [crabbly/Print.js#105]
I find the `html.js` using 'getElementById' to get printElement. This is very limited. Can you support class name or others ?

**Comment by crabbly** [comment]
Hi @p2yang , currently the library supports html printing for one wrapper element, which must have an id. Unfortunately, I'm not planning on adding class support at this moment. Hopefully, someone can submit a PR to support this feature.

**Comment by p2yang** [comment]
Ok, thanks. It helped me a lot. I'm trying to do it.
