### ISSUE TITLE
Add stylesheet

### ISSUE THREAD

**Issue by Kreativschnittstelle** [crabbly/Print.js#106]
First of all thank you for the great plugin! I think it would be a very great feature to be able to add a stylesheet to the printed html section (for example the main css file from the page the html section is in). Or is that maybe already possible and I missed it? Thanks!

**Comment by crabbly** [comment]
@Kreativschnittstelle Hey Matthias, the library currently doesn't support that. It would be a nice feature to have though.

**Comment by riteshrc** [comment]
Hello,
I am facing a similar problem. Css sheet not working when printing the pdf. Even when I try to override the styles in the html tags, some are working and some fails. Font tags in particular are failing always.
any help will be appreciated.

**Comment by crabbly** [comment]
@riteshrc I think your problem can be solved by using the new parameter `targetStyles`. Try passing `['*']` and all your applied styles will be processed when printing any HTML element.
http://printjs.crabbly.com/#configuration

I'm still planing on adding support for CSS media queries, which will allow to differentiate the style of the element when printed, from the screen display. Similar to what Matthias mentioned above.

**Comment by alexthekid07** [comment]
@crabbly Since `['*']` grabs everything, and there is often way too many styles to manually specify manually, would it make sense to also have an `ignoreStyles` or something of the sort?

**Comment by crabbly** [comment]
@alexthekid07 It does make sense to have a `ignoreStyles` parameter. But I probably won't implement it. A PR would be welcome. 
I want to dedicate some time to support css media queries. This way, we will have full control over the print style.

**Comment by crabbly** [comment]
@Kreativschnittstelle  The library has now a new paremeter (`css`) which allow us to pass a url to a custom css file that will be used when printing html.
http://printjs.crabbly.com/#configuration

**Comment by crabbly** [comment]
Hi @JonathanLee-LX , Vue will creates a `<script>` tag on the document page where your component is loaded. Before calling the `printJS` function, you will have to manually grab this stylesheet (`document.styleSheets`) and pass it to the library.

**Comment by RafaelMoid** [comment]
I'm using it like bellow but my css is not beeing loaded :(

function Projetos() {

    function printPage() {
        printJS({
            printable: 'printJS-form',
            type: 'html',
            css: './index.css',
            targetStyles: ['*']
            
        })
    };

**Comment by RafaelMoid** [comment]
Hi, i've this page with multi components rendering it and when i try to all css that should be aplied to them, but none of then as loaded, please help me :(

Here is the code:

function printPage() {
        printJS({
            printable: 'printJS-form',
            type: 'html',
            css: ['./index.css' , '../ChartsJourney/ChartJourney1.css', 
            '../ChartsJourney/chartJourneyHorizontal.css', '../PeopleList/PeopleContainer.css'],
            targetStyles: ['*']
            
        })
    };

**Comment by Maelle94** [comment]
Hello! My css code does not work even though I used the css property
`<button type="button" onclick="printJS({ printable: 'offer-printed', type: 'html', targetStyles: ['*'], css: '../assets/printing.css', scanStyles: true })"> Print </button>`
Can you help me please

**Comment by nemanjakmno** [comment]
Problem is probably with a path of css file, I'm facing it also, can't figure out how to resolve it. When included external css file https://examplecss... works ok, but internal css asset not.
@crabbly anything helpful?
