### ISSUE TITLE
bower is missing dist folder

### ISSUE THREAD

**Issue by vmanchev** [crabbly/Print.js#108]
Hello,
when installing printJS via bower, version 1.0.23 had both "src" and "dist" folders. Files from "dist" was those to be used in our build. With the current version 1.0.25, the "dist" folder is missing and there is only the "scr" folder and files. I know we can build the dist files ourselves, but when using gulp and wiredep, it would be really convenient to have the pre-build versions as well.

**Comment by crabbly** [comment]
@vmanchev Hey Venelin, I agree. 
Just released v1.0.29 which includes the `dist` folder again. 
https://github.com/crabbly/Print.js/releases/latest
It is already published to npm as well. Thank you.

**Comment by alexiosd** [comment]
Hello version 1.6.0 is again missing the dist folder.
