### ISSUE TITLE
Passing print settings

### ISSUE THREAD

**Issue by cTxplorer** [crabbly/Print.js#112]
Hello! Is it possible to directly pass the print settings, so that we don't need to manually set the print settings - like paper size, pages, colour and number of copies?

**Comment by crabbly** [comment]
@cTxplorer Hey Pratik, looks like you want to set the default printer settings, this can't be done via javascript. It must be done in the client's OS printer setup. 
For example, in Windows, under control panel, printers, edit the default printer preferences.

**Comment by tquiroga** [comment]
In the case of a PDF, you can use pdf-lib to copy pages. For instance we have a PDF we want in 10 copies, it has one page. We copy that one page 9 times with pdf-lib to make a 10 pages document and give the pdf binary to printJS.

You can probably do similar things with images. There a quite a few packages that can run in browser now.
