### ISSUE TITLE
Printjs not working with blobs in IE and EDGE

### ISSUE THREAD

**Issue by javascrewpt** [crabbly/Print.js#113]
My use case is as follows: I get a blob from web service, transform it to PDF (in memory) and print it with print.js. While it works flawlessly in Chrome, it causes the following error in EDGE (and IE11):

> SEC7134: Resource 'blob:http://localhost:3000/f2cb3445-edee-414b-91f5-343d7f49badb' not allowed to load. SCRIPT5: Access is denied. 

any ideas?

**Comment by crabbly** [comment]
Hey @javascrewpt , I haven't seen this error before and I'm not aware of a solution for it. However, looks the Microsoft Edge team identified this as an internal issue within their browser:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/13442439/

Are you using Edge's latest version?

**Comment by javascrewpt** [comment]
Yes, I have the latest version. I managed to setup a clean project and while I don't get the access denied error, the PDF is not printed - rather (in both Edge and IE11) the PDF is opened in a new window with the browser plugin for PDF opened or the PDF is downloaded. Is this the normal behavior of Print.js in IE and EDGE?

**Comment by crabbly** [comment]
That's correct. The library can't print PDF's automatically in IE or Edge, as you can see here:
http://printjs.crabbly.com/#browsers

It will identify the browser, and instead of trying to print and keeping the user hanging, it just opens the new tab instead. If the browser is supported, like Chrome or Safari, it will print directly.

**Comment by crabbly** [comment]
Closing this issue in favor of #33

**Comment by PiotrekPaprocki** [comment]
@javascrewpt Are you sure you are able to open new tab with pdf in blob in IE11?
In my case I have pdf in `base64` string fetched from the server. Then I convert it to blob, use `URL.createObjectUrl`, pass it to `printJs` and get `access denied` in IE console.
The only solution I found is to use `msSaveOrOpenBlob`, but it's not opening the pdf in new tab. 
I've read internet twice and couldn't find valid solution. 
One of many references: [click](https://answers.microsoft.com/en-us/ie/forum/all/unable-to-preview-the-pdf-filecontent-using-blob/ba1806e8-307e-4b8f-92d1-b986f5537052)

I'm using win7, ie11.0.9600.18860IS - latest build for win7

**Comment by crabbly** [comment]
Hey @papiscript,
I think the improvement we will do [here](https://github.com/crabbly/Print.js/issues/297) will probably fix the issue with blobs in IE11
