### ISSUE TITLE
Duplicate remote request

### ISSUE THREAD

**Issue by santurelli** [crabbly/Print.js#114]
In my application pdf file is generated on the fly via http request to server. Client side code is:
printJS('http://myserver/invoice/printList')

The server send pdf to client with this code ("bytes" is byte array representing pdf file):
response.setContentType("application/pdf");
response.setHeader("Content-disposition", "inline; filename=file.pdf");
response.setContentLength(bytes.length);
response.getOutputStream().write(bytes);

All works right, but I have seen that every request is sent two times to server. In Google Chrome Developer Tools, I see that type of first request is "xhr" and type of second request is "document".
Is this a bug?

**Comment by crabbly** [comment]
The first request is to preload the pdf, useful when showing a "loading" message to the user. It should then be retrieved from the browser cache. I'll take a look into this.
Is your server sending a "no cache" request?

**Comment by santurelli** [comment]
Hello, I have analyzed request and response and I have seen that in server response is "no cache" attribute.
Here is the response header:
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache

**Comment by santurelli** [comment]
Hello, even if I add `response.setHeader("Cache-Control", "max-age=30");` to my code, I see again two request to my server side

**Comment by crabbly** [comment]
Got it. 
About the second request, we should always see it, however, check if it uses the browser cache, which is what we want.

However, maybe we could add an option to disable the preload, by passing a parameter to the `printJS` function.

**Comment by LorenzoRogai** [comment]
Hi,

Is there any update on this?

It would be better to send only one request, as if you execute some database queries when retrieving document as output from a php script the query gets executed twice

Thank you

**Comment by GlebDolzhikov** [comment]
+1 for one request!

**Comment by bearshunter** [comment]
+1

**Comment by crabbly** [comment]
The second request is happening when `showModal` is used. The browser is not using the cache because of the document request type. I'm working on an alternate solution to provide a better "pdf is loaded" state to be used with the modal loading message and `onLoadingEnd` hook.

In the meantime, do not use `showModal` and the lib will run one request only.
I'll post an update here as soon as a solution has been pushed to npm.

Ps.: Make sure you are running the library latest version: `npm update print-js`

**Comment by crabbly** [comment]
Just published a new version with a better solution for pdf preload. It will not longer create the second request to the server. It will use the browser cache instead.
The documentation page already has the updated version, you can run tests there:
http://printjs.crabbly.com/#pdf

Please reopen this if you get any issues.
Thx.
