### ISSUE TITLE
How to style individual columns using styled json?

### ISSUE THREAD

**Issue by Kuchiriel** [crabbly/Print.js#115]
There is some documentation or example for doing that?
e.g I have this HTML table 
![image](https://user-images.githubusercontent.com/4648891/35229238-08c03a6c-ff7a-11e7-968f-26fc2a80a036.png) I want to print with the same colors.

Thanks in advance!

**Comment by crabbly** [comment]
@Kuchiriel , hey Matheus, printing JSON data directly with the library, won't allow you to style the grid like that. What you could do, is to print the HTML version of your table, if that fits the page.
Also, remember that by default, your browser may not print the background color when printing HTML. Being that this is a browser setting, I don't believe javascript would be able to manipulate that. That said, printing background colors in your grid columns won't be reliable. If that's really necessary, a solid solution may be to generate a pdf file on the server side, then just print that pdf. This will guarantee the colors. 
Hope this help somehow.

**Comment by Kuchiriel** [comment]
Thanks @crabbly I will follow your advice.
