### ISSUE TITLE
Print an object inside an object

### ISSUE THREAD

**Issue by daniportillo** [crabbly/Print.js#116]
I'm trying to print a Json that have an object inside, but every time I call that object it show undefined.
Here an example of my json
{
        "name": "Jhon",
        "Last name": Smith,
        "Age": 30,
        "records": {
            "id": "1",
            "size": "10",
        }
    },

So when a call records.id it shown undefined, but if a call just records it shown 'object Object'

**Comment by crabbly** [comment]
@daniportillo Hi Daniela, to be honest the JSON print feature wasn't really designed to handle nested objects. I'll take a look at the code to see if there is a problem there, and if it doesn't really support nested objects, maybe we could add support for it.

In the mean time, could you please post here the code you used when calling the `printJS` function? Thx

**Comment by daniportillo** [comment]
Thanks for the quickly response.

Here is the code I use to print my data.  

```
  printo() {
    const classes = this.myJson;
    printJS({printable: classes,  properties: ['name', 'age', 'record'], type: 'json'});
  }
```

**Comment by crabbly** [comment]
Cool.
Have you tried passing `record.id` instead?

`printJS({printable: classes,  properties: ['name', 'age', 'record.id'], type: 'json'});`

**Comment by daniportillo** [comment]
Yes I try it and the result is 'Undefined'

Oh well I found a solution 😄 

I add with a for the value of the record.id to the main object of the Json and now I can print it.

OMG. HAHAHA

Thanks!

**Comment by crabbly** [comment]
Perfect! That's true, the data should just be manipulated before sending it to the function.
We shouldn't need to change the library to handle this kind of stuff. 💯

**Comment by crabbly** [comment]
I decided to go ahead and add support for nested objects when printing JSON data.
It's available with the latest release:
https://github.com/crabbly/Print.js/releases/latest

It will accept the `.` notation, to pass the property that we want to print in the nested object. For example, this will work just fine now:

`printJS({printable: classes, properties: ['name', 'age', 'record.id'], type: 'json'});`
