### ISSUE TITLE
How to print directly to printer without any confirmation window

### ISSUE THREAD

**Issue by riteshrc** [crabbly/Print.js#117]
hi,
I am printing a data table from a html page with print.js. I am printing the sheet to PDFCreator but the default windows print box is showing up before print. I want to bypass this confirmation window. My default browser is Google Chrome and Firefox. 
Please HELP !!

**Comment by crabbly** [comment]
Hey @riteshrc , javascript can't bypass the browser print confirmation window. 
This is for security reasons. Otherwise any website could print stuff to your printer without warning.
Refer to #79

**Comment by akelhad** [comment]
at first , very thanks for awesome script 
please do you know any other language which can print silently
