### ISSUE TITLE
Page Break css not working (or need an example)

### ISSUE THREAD

**Issue by mmccallum** [crabbly/Print.js#118]
Can't seem to get the page breaking to work.  Of course, there is no official documentation for it, so I could have pieced it together incorrectly.

Fiddle:
https://jsfiddle.net/budw7fcp/3/

Thanks!
-Matt

**Comment by crabbly** [comment]
@mmccallum The library ins't supporting css page break at the moment. I'm trying to spare some time to work on it, to change how it handles html styling and add support for print media queries, including page breaks.

**Comment by crabbly** [comment]
The library has now a new parameter, `css`, where you can pass the url of a css file that contains your media queries.
http://printjs.crabbly.com/#configuration

Update the library and give it a try.
Thx.
