### ISSUE TITLE
Could add css style when printing?

### ISSUE THREAD

**Issue by thearabbit** [crabbly/Print.js#119]
I base on `Vue`
```js
<template>
   <div>
      <div class="myclass">My Data.....</div>
   </div>
</template>
<style lang="scss" scoped>
   .myclass {
      color: red;
   }
</style>
```
But don't work when printing.

**Comment by crabbly** [comment]
@thearabbit Hey Yuom, have you tried passing the param `honorColor` as `true`?

For example, if you are trying to print the div element with it `test`:

```
<template>
   <div id="test">
      <div class="myclass">My Data.....</div>
   </div>
</template>
<style lang="scss" scoped>
   .myclass {
      color: red;
   }
</style>
```
Then:

`printJS({ printable: 'printJS-form', type: 'html', honorColor: true })`

**Comment by thearabbit** [comment]
Thanks for your reply.
This is my example `color css`, but I would like to pass the other css style?
```js
.my-class{
  font..
  border
  color
  ...
}
```
It suport css string like `printd `?

**Comment by crabbly** [comment]
Yuom, there is a recent commit adding parameters where you can tell the lib to process all styles applied to your html elements. 
https://github.com/crabbly/Print.js/commit/5ed39836dd69f4054a64e6fefc6278113651ed05

I haven't yet added it to the documentation, but the changes are already published in npm.

**Comment by crabbly** [comment]
Btw, this still doesn't support css media queries. However, I'm planning on adding support for it soon.

**Comment by mugar** [comment]
thank you @crabbly  for the new options of targetStyles, it working as expected. Now I can control the styling and make it look as desired. Great Job.

**Comment by thearabbit** [comment]
@mugar, How to use `targetStyles`.
I can't find in docs

**Comment by mugar** [comment]
you add the name of the styles properties you want to be kept during printing, like showcased in the snippet below. 

printJS({printable: 'print-container', 
            type:'html',
            maxWidth: 350, 
            honorColor: true,
            targetStyles: ['margin','font-size','text-align','font-weight','border']
          })

**Comment by thearabbit** [comment]
thanks for your reply, but don't understand how to pass `style value`

**Comment by mugar** [comment]
define first your styling like 
`<style lang="scss" scoped>
   .myclass {
      color: red;
     font-size: 15px;
     margin: 10px auto;
   }
</style>`

and in the javascript file, add in the printJS options the targetStyles property which is an array listing all the names of the css properties you have used. for the css sample above it would be like this
`
printJS({printable: 'elementID',
type:'html',
targetStyles: ['color','font-size','margin']
})
` 
so whatever css property that is not in that list of targetStyles will be ignored by printJS, but any property included in the array will be kept and used in the generation of the printable pdf.

**Comment by crabbly** [comment]
@thearabbit Hey Yuom, as Mugabo explained above, you can tell the library which styles should be processed when printing any HTML element, however, the element should already have those styles applied to it.

For example, a HTML element with ID `testElement` and style class `my-class`:

```
<div id="testElement" class="my-class">
    <h1> Test Print </h1>
</div>
```

In your stylesheet:

```
.my-class { 
    color: red;
    font-size: 15px;
    margin: 10px auto;
    padding: 5px;
}
```

Then in your Javascript:

```
printJS({
    printable: 'testElement',
    type:'html',
    targetStyles: [
        'color',
        'font-size',
        'margin',
        'padding'
    ]
})
```

I haven't yet added the `targetStyles` option to the documentation, but I hope this explains how to use it.

**Comment by thearabbit** [comment]
So it mean that we must input all style that we use into `Array of targetStlyles`.
I thinks that it is not good, if we have many style.
Excuse me, Why you don't use `cssText, or any cssObject` such as [Printd](https://github.com/joseluisq/printd)

**Comment by crabbly** [comment]
You can pass * for all styles.

**Comment by crabbly** [comment]
The documentation was updated with `targetStyle` and `targetStyles` params.
http://printjs.crabbly.com/#configuration

@thearabbit Yuom, have you tried using it yet?

**Comment by thearabbit** [comment]
Thanks again, I will try soon

**Comment by sanfx** [comment]
["*"] worked for me but not  `targetStyles: ['color','font-size','margin'] `, now the problem is it is getting applied to all the html tags not just the one html tag that has class specified.

**Comment by crabbly** [comment]
@sanfx Correct, it will process all the HTML being printed. 
To better manipulate the print style, I recommend disabling the style processing on the library by passing `scanStyles: false`, and to use the `css` and `style` properties instead.
http://printjs.crabbly.com/#configuration

**Comment by VikasSingh1694** [comment]
@crabbly, ['*'] is not adding all CSS, There is some CSS that has not to be added to while adding design also break because of this.

**Comment by FazilNusrat** [comment]
> ["*"] worked for me but not `targetStyles: ['color','font-size','margin'] `, now the problem is it is getting applied to all the html tags not just the one html tag that has class specified.

Yeah, worked for me too

**Comment by FazilNusrat** [comment]
> ["*"] worked for me but not `targetStyles: ['color','font-size','margin'] `, now the problem is it is getting applied to all the html tags not just the one html tag that has class specified.

Worked for me
printJS({
          printable: 'myElement',
          type:'html',
          targetStyles: ['*']
        })

**Comment by FazilNusrat** [comment]
**100%** **Worked** for me ['*']

printJS ({ printable: 'myElement', type:'html', targetStyles: ['*'] })

**Comment by VikasSingh1694** [comment]
@FazilNusrat, It worked for me also but I got some break-in the design because of width and am not able to handle those parts.

**Comment by PUJARIANILKUMAR** [comment]
Can we add bootstrap styles

**Comment by altonim** [comment]
Using print.js 
printJS({
  	printable: 'id_to_print',
	type: 'html',
	targetStyles: ['*'],
	style: your_print_style
});

**Comment by ranjanOO7** [comment]
@altonim how to use this bootstrap styles

**Comment by Maelle94** [comment]
Hello! My css code does not work even though I used the css property
<button type="button" onclick="printJS({
          printable: 'offer-printed',
          type: 'html',
          targetStyles: ['*'],
          css: '../assets/printing.css',
          scanStyles: true
        })">
        Print
    </button>
    Can you help me please
