### ISSUE TITLE
Font Size aka Custom CSS on print

### ISSUE THREAD

**Issue by AmGarera** [crabbly/Print.js#12]
No matter what I'm doing it won't change anything CSS wise when doing an HTML print, any advice or tips @crabbly

**Comment by crabbly** [comment]
@AmGarera Could you explain exactly what you are doing? If possible, please post some code here. Thank you.

**Comment by AmGarera** [comment]
I have a table which returned data from my Dexie.js database and I'll style the table to be 10px font-size so that it can fit a lot of data on one page but when it prints by clicking a button that executes printJS it resets all styling as if it never happened as seen in the PDF below.
[testing.pdf](https://github.com/crabbly/Print.js/files/621157/testing.pdf)

**Comment by crabbly** [comment]
By default the library will print using font size 12pt.
I just added `font_size` as an optional parameter. 
Download the latest release (https://github.com/crabbly/Print.js/releases/latest) and try this:
`printJS({ printable: 'your-table', type: 'html', font_size: '10px' })`

**Comment by AmGarera** [comment]
Okay just tested the latest release and it did work! Whenever you'd be able to push that out to NPM would be great! Thank you so much!

**Comment by crabbly** [comment]
Cool. Just published it to NPM.
If you like the library, please star the repository. Thank you
