### ISSUE TITLE
Unable to print several sets of data

### ISSUE THREAD

**Issue by lahiruhashan** [crabbly/Print.js#120]
Let this be my array.
myObj = {
   [
    "name":"John",
    "age":30,
    "car": "BMW"
    ],
   [
    "name":"Rel",
    "age":34,
    "car": "VOLVO"
    ],
 }

I want this two set to be printed in two separate tables. What i get is second table replacing the first. Ultimately only one table printed.
How can I overcome this problem?

**Comment by crabbly** [comment]
@lahiruhashan , Hi Lahiru, this isn't a problem with the library. You should print the two sets separately. 

For example, if you split your sets in different variables, let's say `set1` and `set2`, you can then create two print jobs:

`printJS({printable: set1, properties: ['name', 'age', 'car'], type: 'json'})`

and

`printJS({printable: set2, properties: ['name', 'age', 'car'], type: 'json'})`

This will print them in different tables.

Also, the object you posted is invalid. It doesn't have any property defined.
