### ISSUE TITLE
Chrome Opening New Tab instead of silent printing

### ISSUE THREAD

**Issue by darlie2014** [crabbly/Print.js#122]
I am using Chrome Version 62.0.3202.94 (Official Build) (64-bit).  Instead of silent printing its opening a new tab as shown on the attachment.

is there a specific version of Chrome that i should use?
![chrome_new_tab](https://user-images.githubusercontent.com/8273555/35738498-bb1e85cc-0837-11e8-8004-efa702af3a13.png)

**Comment by crabbly** [comment]
Hey @darlie2014 , this is not a new tab, is just the print preview from Chrome, which is exactly what we want to see. As far as I know, Javascript alone cannot do silent print directly to the printer, for obvious security reasons. So, looks like everything is working as expected in your code.

**Comment by crabbly** [comment]
Take a look at #79
