### ISSUE TITLE
Don't include built files in this repo

### ISSUE THREAD

**Issue by sloria** [crabbly/Print.js#125]
Built files in `dist/` do not belong in the repo. Source control is for *source* files--not compiled/transpiled/built files, which only add noise to the git history.

dist/ files should be distributed in the npm releases.

**Comment by crabbly** [comment]
Thank you, Steve. I'll add a `.npmignore` file and remove the `dist` folder the repo.

**Comment by crabbly** [comment]
Done! Thanks again, Steve.
