### ISSUE TITLE
Printing preview is blank

### ISSUE THREAD

**Issue by jamesst20** [crabbly/Print.js#126]
Hi,

I would like to report a bug with latest version of Opera 51.0.

Issue:
1. The printing preview is empty (didn't try to print)
2. Only happens with PDF. Json printing or everything else is fine.

![capture d ecran 2018-02-20 a 10 06 38](https://user-images.githubusercontent.com/490234/36431634-11a51cca-1626-11e8-9b64-c164efcb69f6.png)

How to reproduce :
1. Visits http://printjs.crabbly.com
3. Click Print PDF of the first example.

Possible workaroud/fix:

Fixing preview manually: Edit the value to 100 and the preview shows up

![capture d ecran 2018-02-20 a 10 23 44](https://user-images.githubusercontent.com/490234/36432493-4faf908e-1628-11e8-8e27-eb2fbe130329.png)

Thank you

**Comment by crabbly** [comment]
@jamesst20 Hey James, I can't replicate this issue. It shows the preview and prints fine for me using Opera.

I'm using Mac OS High Sierra and Opera 51.0.2830.34.

What is your OS and version?
If you click the checkbox "Fit to page" does it show the print preview?

**Comment by jamesst20** [comment]
@crabbly 

Thanks for the fast reply. You don't have this issue if you edit the value of 100 for another, let's say 96? Adjust to page makes the preview empty.

I am also using Mac OS High Sierra 10.13.3

![capture d ecran 2018-02-20 a 11 26 14](https://user-images.githubusercontent.com/490234/36435908-e805e3bc-1630-11e8-8126-40c27f440c58.png)
![capture d ecran 2018-02-20 a 11 26 19](https://user-images.githubusercontent.com/490234/36435909-e812fe6c-1630-11e8-8188-1d54ff02bba8.png)

**Comment by crabbly** [comment]
Got it. 
No matter what settings I choose ("fit to page", 100%, 50%...), it prints fine here. 

However, I'm on Hight Sierra 10.13.2. I'll update to 10.13.3 to check if this version has anything to do with the issue.

**Comment by jamesst20** [comment]
Thank you ! Let me know, otherwise at home I have an iMac on 10.13.2 which I could test if the issue happens

**Comment by crabbly** [comment]
Ok. I updated my system to Hight Sierra 10.13.3, but I still can't replicate the issue. It works fine. So, looks like the issue is not related to that.

Could you try changing the printer? For example, changing the destination to "Save as PDF" and check if the preview will show properly?

**Comment by jamesst20** [comment]
Thank you, it was printer related as I can see :)
