### ISSUE TITLE
How to detect printer connected with system using ionic web application

### ISSUE THREAD

**Issue by Muru1778** [crabbly/Print.js#129]
I  am developing ionic web application with printer functionality. I used Print.js npm to print the content. If in case the printer not connected with system, I need to show some message about this. how can I determine whether the printer is connected or not. Is there any way in print.js npm or any other npm to determine this requirment

**Comment by crabbly** [comment]
Hi @Muru1778 , as far as I know, this is not possible with Web Applications and Javascript. You would probably need a native application to control / detect the user printer settings.

I'm not sure why you would want to implement that, but in my opinion, knowing that you have a working printer before trying to print anything, should be the user's responsibility.
