### ISSUE TITLE
Multi Column Layout Support

### ISSUE THREAD

**Issue by AmGarera** [crabbly/Print.js#13]
The project I'm currently working on would benefit greatly from the ability to use [Multi Column Layouts](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Columns/Using_multi-column_layouts#Height_Balancing) in CSS due to the nature of printing a sheet and having it folded over when in use so overflow from column 1 goes into column 2 without starting a second page.

Thanks,
Anthony

**Comment by crabbly** [comment]
@AmGarera Interesting. I'm not sure if using CSR multi column layouts would fix the issue (when data from one column is too long). Could you post a picture or pdf with an example to better describe the benefits?
Thank you.

**Comment by crabbly** [comment]
@AmGarera I'm going to close this for now, since I can't really see the benefits. If you could show me otherwise, I would try to implement it. Thank you.
