### ISSUE TITLE
How to print using print.js in ionic application without opening printer setup page

### ISSUE THREAD

**Issue by Muru1778** [crabbly/Print.js#130]
We are developing ionic web application with printer functionality. We used Print.js npm to print the content. There is a page open in browser when we call print method. We can see the information like printer name, no.of pages and so on. Our requirement is to print the content without showing that setup page ionic application.

**Comment by crabbly** [comment]
Hi @Muru1778 , this can't be done with Javascript alone. For security reasons. 
Please refer to #79
