### ISSUE TITLE
[Request] - Print HTML as string (with CSS inline)

### ISSUE THREAD

**Issue by LuizLeite** [crabbly/Print.js#131]
Hi.

I need to print an HTML, passing by string.

There is possible in newer version?

When i printing by json i'm limited to formating with CSS, columns width, height of row, bold and other things.

Tanks.

**Comment by crabbly** [comment]
@LuizLeite Hi Luiz, the library doesn't support HTML as string. The JSON feature is a quick way to print JSON data without having to write any HTML. You can style the grid to fit most needs. 

For more complex HTML grids, you would need to display it in the webpage somewhere, and then print the HTML itself. This way, you can control the HTML as you like, before printing it.

If, for any reason, you don't want to display the information in the page (HTML grid), the other option would be to have the HTML hidden in the webpage, and add a print media query to change the visible or display property in it. This way, you can control the HTML as you want, then just send it to printJS with the type `html`.

However, the library current doesn't support CSS media queries. I'm planning on adding support for it.. I'll keep this issue opened and post here whenever the print media query support has been added.

**Comment by crabbly** [comment]
Media query support will be added soon the library. However, I'm closing this issue since it can be fixed by hiding the html element before printing it. For ex. `height:0; overflow:hidden;`. Feel free to open this issue again if necessary.
