### ISSUE TITLE
Uncaught TypeError: (0 , _npmPrintJs.default) is not a function

### ISSUE THREAD

**Issue by 85636682** [crabbly/Print.js#132]
i used print.js in ember and get this error 
```
Uncaught TypeError: (0 , _npmPrintJs.default) is not a function
```
print-js version: 1.0.31
this is my code:
```
import printJS from 'npm:print-js';
...
actions: {
     print () {
      let someJSONdata = [
        {
           name: 'John Doe',
           email: 'john@doe.com',
           phone: '111-111-1111'
        },
        {
           name: 'Barry Allen',
           email: 'barry@flash.com',
           phone: '222-222-2222'
        },
        {
           name: 'Cool Dude',
           email: 'cool@dude.com',
           phone: '333-333-3333'
        }
      ];
      printJS({ printable: someJSONdata, properties: ['name', 'email', 'phone'], type: 'json' });
    }
}
```

**Comment by crabbly** [comment]
Looks like this error has something to do with the import of the library. 
Print.js occupies the global variable `printJS`. Using it in your import, in the same file where you are trying to call the function, will probably fail. 

Try this instead:

```
import print from 'print-js';
...
actions: {
     print () {
      let someJSONdata = [
        {
           name: 'John Doe',
           email: 'john@doe.com',
           phone: '111-111-1111'
        },
        {
           name: 'Barry Allen',
           email: 'barry@flash.com',
           phone: '222-222-2222'
        },
        {
           name: 'Cool Dude',
           email: 'cool@dude.com',
           phone: '333-333-3333'
        }
      ];
      printJS({ printable: someJSONdata, properties: ['name', 'email', 'phone'], type: 'json' });
    }
}
```

Also, if you are trying to import Print.js inside an ember component, I would recommend to import it outside, before you instantiate your ember code.

Since the library assigns the `printJS` function to a global variable, you will be able to use it anywhere in your code.

**Comment by 85636682** [comment]
thx，it works.

**Comment by crabbly** [comment]
Just published a new version to npm which has proper support for module import.
The library will still expose a global variable `printJS`, but the recommend usage now should be to import the package at the same file where it will be used:

For ex.:

`import printJS from 'print-js'`

`printJS('path-to.pdf')`

Run `npm update print-js` to get the latest version.

**Comment by avs30390** [comment]
![image](https://user-images.githubusercontent.com/11497020/186367680-af9d5a10-b040-4066-90c1-b31add16b50a.png)
Getting error while try to add unit test using jest.
jest.mock('print-js', () => {
  const printJS = jest.requireActual("print-js");
    return printJS({printable:'https://someurl/label.pdf', type:'pdf', showModal:true})
    
})
describe('Print TR label', () => {
  it(`Once user clicked on button
  It should open print preview mode`, async () => {
    const wrapper = await mount();
    const newState = copyState();
    wrapper.find('.print-return-label-button').simulate('click');
    expect(printJS('https://someurl/label.pdf')).toHaveBeenCalled();
  });
});
