### ISSUE TITLE
Blank page when printing on Chrome 65

### ISSUE THREAD

**Issue by vshmoylov** [crabbly/Print.js#135]
**Browser:** `Google Chrome 65.0.3325.162`
**OS:** `Windows 7 64-bit`

**Issue:**
After update from Chrome 64 to Chrome 65, printing html block shows and prints blank page. Image printing also shows blank page.

**Steps to reproduce:**
1. Update to Chrome 65
2. Try to print something

**Comment by LuizLeite** [comment]
Me too.

**Comment by amarunko** [comment]
Mee too, mac os 10.13.3 (17D102)

**Comment by vshmoylov** [comment]
This bug is related to recent Chrome modification to support [new CSS property](https://developers.google.com/web/updates/2018/03/nic65#display-contents) `display: contents`.

Somehow this change breaks iframe rendering, that's why we're getting blank page. As a temporary workaround, I suggest to use style `display:content` for iframeElement that is used for printing at `/src/js/print.js` file.

Probably, I'll prepare a fix soon.

**Comment by duksi1993** [comment]
For me, even after setting iframe style to "display: contents" I'm still getting blank page.
The only thing that I can confirm it is working is removing `p.setAttribute("style", "display:none")` from iframe element in `/src/js/print.js` file.

**Comment by crabbly** [comment]
Hey guys, I implemented the solution offered by Igor in #133 
It seems to have fixed the issue with Chrome v65. 

I already pushed the changes to npm as v1.0.33. Just `run npm update print-js`
