### ISSUE TITLE
Unable to print HTML in Chrome Latest Version 65.0.3325.162

### ISSUE THREAD

**Issue by NaveenSelvaraj** [crabbly/Print.js#137]
In the Previous version of Chrome (63), I had been using Print Js for printing HTML. After Updating to **

> chrome latest version  65.0.3325.162. It's not working.

**
**I am getting a print preview without any content.** 
it shows only Document Title, Date in Top and URL in Bottom. None of the DIV displaying in the Print Preview.
my Code is : printJS({ printable: 'divSummary', type: 'html', header:'Summary',font_size:'16pt' })
divSummary is ID of Div.

I have attached Screenshot here.
![image](https://user-images.githubusercontent.com/3745825/37552564-0bd30f16-29de-11e8-9a03-a6dc9bfa3bb2.png)

**Comment by mharapiak** [comment]
I tested PrintJS on Chrome 65.0.3325.162 for OS X and Windows and I can confirm that it just produces blank output for html print. The preview and output are blank pages. You can test directly from the demos on http://printjs.crabbly.com/

It was working with the previous version of Chrome, both platforms.

I tried the printjs demo using FIrefox 59 on OS X and it prints fine.

**Comment by crabbly** [comment]
Hey guys, this has already been fixed with the latest version. Please run `npm update print-js`. 
Test it, and let me know if you are still having issues with it.

Reference #133 , #135

**Comment by crabbly** [comment]
@mharapiak The documentation has been updated with the latest version. You can test it with chrome v65, it works fine now.

**Comment by mharapiak** [comment]
Update worked! Thanks. Sorry to bother. Should have looked at the closed issues.
