### ISSUE TITLE
html print: transform style not work

### ISSUE THREAD

**Issue by ningshen** [crabbly/Print.js#138]
hi, 
thank for your plugin.

when print html node, transform style will not work.

https://github.com/crabbly/Print.js/blob/master/src/js/html.js#L21
`printableElement.setAttribute('style', 'display:none;');` 
which it set the root element `display:none`,  make children node get `transform` style value not work, always get `none`. (google chrome 64.0.3282.186)

some ideas:
1. change to 
`printableElement.setAttribute('style', 'height:0;overflow:hidden;');`
it work.
2. add hook event before copy html data to iframe, change printable element node
3. add event before print , change iframe element node

**Comment by crabbly** [comment]
Hey @ningshen , have you tried the latest version? We replaced `display:none;` with `visibility:hidden`, `height:0` and `width:0`. 

Please run `npm update print-js` or download the latest version here https://github.com/crabbly/Print.js/releases/latest

Please let me know if this fixes the issue. Thx.

**Comment by ningshen** [comment]
@crabbly thank for you reply.

I'm sorry to say it is not work.
  
Because reason is set printableElement(`#printJS-html`)` style `display:none;`. 
 It make `loopNodesCollectStyles` can not collect `transform` style.
https://github.com/crabbly/Print.js/blob/master/src/js/html.js#L21

laster version(1.0.33) set iframe style:  `visibility:hidden, height:0 and width:0.` (https://github.com/crabbly/Print.js/blob/master/src/js/init.js#L108) not help solve.

demo: https://jsbin.com/nuvuvi/9/edit?html,css,js,output

**Comment by crabbly** [comment]
@ningshen , Thanks for explaining the issue, and for the bin. I agree, we should change the `html.js` code and remove the `display: none;`. I'll try to make these changes today and post here once it has been published.

**Comment by crabbly** [comment]
I just pushed the changes: https://github.com/crabbly/Print.js/commit/135cefa677f9b8176cae69ad64f16c8f172716fd

It is already available on npm. Just run `npm update print-js`.
Thank you for your help! @ningshen
