### ISSUE TITLE
Print content without showing setup page

### ISSUE THREAD

**Issue by jbgomez21** [crabbly/Print.js#139]
Hi!

We are developing ionic web application with printer functionality. We used Print.js npm to print the content. There is a page open in browser when we call print method. We can see the information like printer name, no.of pages and so on. Our requirement is to print the content without showing that setup page ionic application.

Regards!

**Comment by crabbly** [comment]
Hi Juan, this is not possible with Javascript alone.

Please refer to #79 , #129 and #130
