### ISSUE TITLE
Laravel blade -> error printJS

### ISSUE THREAD

**Issue by Morpheons** [crabbly/Print.js#140]
i sorry for my english,

i try to explain my pb : 

i unzipp Print.js-1.0.33.zip
i put all js in public/js
i put all css in public/css

i put into the app.blade.php 
        in the head <link href="{{asset('/css/print.css')}}" rel="stylesheet" type="text/css" >
        in the footer <script src="{{asset('/js/print.js')}}"></script>
on the views show.app.blade.php
in the div : 
 <div class="invoice" id="printJS-repas">
....
<button type="button" onclick="printJS('printJS-repas', 'html')"><i class="fa fa-print"></i></button>
</div>

so on my page i see button but i haven't action

and when i use inspection on chrome i see this message : 
12:182 Uncaught ReferenceError: printJS is not defined
    at HTMLButtonElement.onclick (12:182)

Can you help me ?

**Comment by crabbly** [comment]
Hi @Morpheons , I'm not sure where you got your `print.js` file from, but the one available for download form the release page is minified, so maybe you are using one of the source files.

Please download and use this instead, which is the compiled file for our current version 1.0.33:
 https://github.com/crabbly/Print.js/releases/download/v1.0.33/print.min.js
