### ISSUE TITLE
Print multiple images

### ISSUE THREAD

**Issue by nguyenhero** [crabbly/Print.js#141]
Hi, thank for the library.
How can i print multi image/pdf ?

**Comment by crabbly** [comment]
Hi @nguyenhero , The library supports pdfs with any number of pages. 
http://printjs.crabbly.com/#pdf

Would you care to explain what you mean by _multi image/pdf_ ?

**Comment by nguyenhero** [comment]
I mean, I have 2 file: "images/PrintJS.jpg" and "images/PrintJS2.jpg" and i want to print that in 1 time
I saw the API : printJS('images/PrintJS.jpg', 'image').
Cant I do some thing like : printJS(["images/PrintJS.jpg","images/PrintJS2.jpg"], 'image')

**Comment by crabbly** [comment]
Got it. You have multiple image files, not pdf. 

Unfortunately the library does not support multiple image printing.
Not sure this is something I would like to implement. I'll think about this feature and get back to you on this.

**Comment by nguyenhero** [comment]
Thank for reply

**Comment by crabbly** [comment]
@nguyenhero , this feature is now available. You can pass an array of images to be printed together.
Please refer #149 

Run `npm update print-js` to get the latest version.
