### ISSUE TITLE
Images in HTML with no defined height/width not loading

### ISSUE THREAD

**Issue by alexthekid07** [crabbly/Print.js#142]
I have an issue where I have images loading onto my page that need to be sized proportionally but also shrink to the containing div. I have this CSS applied to them:
`max-width: 100%;
max-height: 300px;`

In print.js I pass the ID of the container element of these images (and other child elements) but the browser (Chrome in this case) does not seem to want to print the image out. Its like its not there.
If I go back to the CSS class I have applied to those images and set a fixed height/width, then print.js seems to have no issue loading them up.

**Comment by crabbly** [comment]
Hi @alexthekid07 , have you tried passing `targetStyles` as `['*']` ?

This will tell the library to process all / any styles applied to the html elements, including the images.

Ex.:
`printJS({ printable: 'htmlElementId', type: 'html', targetStyles: ['*'] })`

**Comment by alexthekid07** [comment]
@crabbly Yeah I'm using the wildcard. Since it works when I use static image heights/widths is there a way to calculate and apply the image dimensions within the printed page?

**Comment by crabbly** [comment]
Got it. 
The library currently doesn't calculate any image dimensions, but we could either implement that or find another solution to fix this issue. 

Would you mind creating a fiddle to replicate this problem? 
I would like to play with it to figure out what we are going to do. I'm sure we can fix this.

**Comment by crabbly** [comment]
This issue has been fixed in the latest version, please run `npm update print-js`.

Here is a fiddle where the lib is properly printing images using `max-width`:
https://jsfiddle.net/crabbly/mLyqnLr1/2/
