### ISSUE TITLE
Custom coloum width if using json type datasource

### ISSUE THREAD

**Issue by h4rm41n** [crabbly/Print.js#144]
How to custom coloum width

![screenshot from 2018-03-25 01-26-02](https://user-images.githubusercontent.com/19913777/37867461-81f7fccc-2fcb-11e8-8d76-c394f22d6751.png)

**Comment by crabbly** [comment]
@h4rm41n Hi Ahmad , the library doesn't support any customization for the json data grid. This feature is just a quick way to print json data without having to create / customize any html. If you check the [json.js](https://github.com/crabbly/Print.js/blob/master/src/js/json.js) file, the `jsonToHTML` function creates a flex grid with equal size columns. I personally won't implement any customization options there, but a PR would be welcome.

For more flexible customizations, I recommend creating a HTML element with the desired grid style, using your json data of course. Then print that element. If you don't want to display the HTML element, you could hide it using css (for ex.: `height: 0; overflow: hidden;`). 

Hope this helps.
