### ISSUE TITLE
Is it possible to remove the Header and print URL?

### ISSUE THREAD

**Issue by born2net** [crabbly/Print.js#145]
Is it possible to remove the Header and print URL?
basically looking to print just a clean page as we print stickers for people

regards

Sean

**Comment by h4rm41n** [comment]
Hi @born2net maybe you mean the url and header the default from browser?

**Comment by born2net** [comment]
yes sorry, meant the default doc and url from the browser...
anyway to remove these so we get a nice clean print?

**Comment by crabbly** [comment]
Hey @born2net , 
It would be nice to get a clean print, but the header and footer are controlled by the user's browser settings. Javascript can't overwrite these.

**Comment by h4rm41n** [comment]
anyway you can customize page media print using css, please check here https://www.w3.org/TR/CSS21/page.html#page-box

**Comment by crabbly** [comment]
The library currently doesn't support CSS Media queries, but I'm planning on adding this soon. However, the `@page` CSS rule wouldn't control the browser header and footer.

**Comment by cleever** [comment]
@s-nadesh Google Chrome has this option. 
You can disable the footers and header by choosing "More definition" option at the print page.
