### ISSUE TITLE
Issue with 100% height + overflow-y

### ISSUE THREAD

**Issue by alexthekid07** [crabbly/Print.js#146]
After the fix(es) you implemented in #142 I am having trouble printing elements that are 100% height and have _overflow-y: auto_ applied to them. It seems to collapse the printable element. It worked fine in the release prior to this change.

Here is a fiddle I forked and changed from the one you supplied in #142:
https://jsfiddle.net/L2bpcwaw/

If you remove either the _height: 100%;_ or the _overflow-y: auto;_ it will print the container properly.

**Comment by crabbly** [comment]
Interesting. 
A quick fix would be to just add a wrapper div around it:
https://jsfiddle.net/L2bpcwaw/6/

**Comment by crabbly** [comment]
Hey @alexthekid07 , since adding a wrapper element does the trick, I won't try to figure out a solution for this specific style combination issue. Plus, last commit fixed not only #142 but #138 as well.
Thank you.
