### ISSUE TITLE
Printing several images at once

### ISSUE THREAD

**Issue by olgierd23** [crabbly/Print.js#149]
I need to print several images but I would like the "Choose printer" window to appear only once. Is it possible? Ideally, if the "printable" parameter of the function could be array of images, not only one image.

**Comment by crabbly** [comment]
Hey @olgierd23 , the library currently doesn't support multiple images printing, unless you embed them together in a HTML element first, then print that element. 

I like the idea of supporting the array option though, just don't know when / if I'll be implementing this. A PR would be great.

Reference #141

**Comment by olgierd23** [comment]
OK. Suggesting embedding images in one HTML element looks promising. Maybe this resolve my issue for now. Thank you.

**Comment by crabbly** [comment]
Yea. One challenge would be to decide whether we want to print the images in the same page, or one image per page.

**Comment by crabbly** [comment]
Ok, I have decided to go ahead and implement this feature. You can now pass an array of images. 
https://github.com/crabbly/Print.js/commit/b6a5db52e3c5870c0a1330d27c51c9abfddd2c97

To control the style of each image, use the `imageStyle` parameter.
https://github.com/crabbly/Print.js/commit/5ce5ca09ccc7041731de73c4044a549d54143142

It has already been published to npm, just run `npm update print-js` to get the latest version.
