### ISSUE TITLE
targetStyles with '*' let broswer no response

### ISSUE THREAD

**Issue by L-sizhong** [crabbly/Print.js#150]
Hi, I use targetStyles: ['*'] to add all styles, but that let broswer very slow, sometimes broswer no response.
Is it a bug?  Or something can I optimize it?

**Comment by crabbly** [comment]
Hey @L-sizhong , there are no known bugs with this feature. 

Could you create a fiddle replicating the issue?

Without that, I can only assume that the machine trying to print has a slow CPU. Another guess would be that you may be trying to print too much HTML. This feature is intended to print parts of HTML from a page. The library process each element individually before printing. If the number of elements is too high, it is possible that slower CPUs would not be able to handle the job. If that's the case, it may be a good idea to create a separate page instead, and let the user print that entire page. This would prevent the need of any javascript processing.

Anyways, if you create a fiddle, I may be able to help more. Thx.
