### ISSUE TITLE
Image printing with chrome / Cannot set property 'innerHTML' of null

### ISSUE THREAD

**Issue by timactive** [crabbly/Print.js#152]
When i try to print image on http://printjs.crabbly.com/.
I have this error 
```
print.js?v1.0.37:1 Uncaught TypeError: Cannot set property 'innerHTML' of null
    at HTMLIFrameElement.pdf.e.type.t.onload (print.js?v1.0.37:1)
pdf.e.type.t.onload @ print.js?v1.0.37:1
```

Chrome Version 57.0.2987.110 (64-bit)

**Comment by crabbly** [comment]
Hi @timactive , thank you for reporting this issue. It seems to be related to older versions of Chrome. I'll test and try to implement a solution. Btw, everything is working well with v65.

Could you please post your OS and its version?

**Comment by crabbly** [comment]
Image printing seems to be working fine in Chrome. 
Make sure to update Chrome to its latest version.
Feel free to reopen the issue if necessary. Thx.
