### ISSUE TITLE
Text cropped and splitted into 2 parts 

### ISSUE THREAD

**Issue by bassemwadie** [crabbly/Print.js#153]
Hello , I am using printjs to print a json object , it contains large data 
the problem is that when the text is located at the end of the page , it split it into 2 parts 
please check the following image 

![1](https://user-images.githubusercontent.com/12097611/38310798-c3038c2c-381d-11e8-9669-30690ca76664.png)

Any Idea , 
Thanks

**Comment by crabbly** [comment]
Hi @bassemwadie , I believe this has been fixed. I just published v1.0.38. Please run `npm update print-js` and give it a try.
Let me know how it goes. Thx.
