### ISSUE TITLE
PrintJS() Expected 1 arguments, but got 2.

### ISSUE THREAD

**Issue by ahawary92** [crabbly/Print.js#154]
I'm using print js lately and it was awesome but when i did an update for print-js library, I got the following Error when using the method printJS(): Expected 1 arguments, but got 2. 
The method was receiving 2 string parameters which are the html id and configuration string respectively.
i.e. printJS('print-items', 'html'); , now printJS method receives only one parameter. How could I reuse it with the same old behavior?
Thanks

**Comment by crabbly** [comment]
Hi @ahawary92 , the library API hasn't changed. It still accepts two parameters, if you don't pass an object.

To print and HTML element of id `myElement`, just use `printJS('myElement`, 'html`)`. Or, as Alex mentioned, you could use `printJS({ printable: 'anElementID', type: 'html' })`

Here is a fiddle showing both methods using the latest version of the library:
https://jsfiddle.net/crabbly/mLyqnLr1/15/

That said, I believe the error you are having is related to how you import the library.
For example, don't do this `import printJS from 'print-js'` and try to use the function `printJS` in the same file. The library already assigns the global variable `printJS`, and this import will create a conflict. Either do your package imports in a separate file, or just change the import name, for ex.: `import print from 'print-js'`.

If you still need help, please post more information how you import and use the package, and we can try to help find the issue.

**Comment by crabbly** [comment]
@ahawary92 Another look at this issue, you are passing `print-items` as the element id. Based on this name, it looks like you are using the same id for multiple elements. This will fail since the library expects one element only. Also, element IDs should be unique within the entire document.
