### ISSUE TITLE
override iframe styles

### ISSUE THREAD

**Issue by romanlex** [crabbly/Print.js#155]
Hello. How I can override style for body in iframe inside printjs library?

Example I build multiple svg elements on the page, when I use default print dialog all work properly
But when I call printjs with parameters
```js
printJS({
          printable: target.attributes['data-target'].value,
          type: 'html',
        })
```
I see black background and page margins
## this is printjs function
![image](https://user-images.githubusercontent.com/3369304/38500368-e569b950-3c12-11e8-90ea-31d0e0aecc21.png)

## this is default print dialog 
![image](https://user-images.githubusercontent.com/3369304/38500515-512a0a28-3c13-11e8-9fee-ffff12121eeb.png)

I think what iframe element inside printjs use custom styles for this and it's not work as expected

**Comment by crabbly** [comment]
Try using the `targetStyle` and `targetStyles` parameters. 
I would first test with`targetStyles: ['*']` to see if that works.
http://printjs.crabbly.com/#configuration

**Comment by crabbly** [comment]
@romanlex Have you played with this? 
Did `targetStyles: ['*']` make any difference?
