### ISSUE TITLE
Not Working in Chrome

### ISSUE THREAD

**Issue by jmcarswell** [crabbly/Print.js#158]
It was working fine when I initially implemented (FEB 2018), but just noticed it produces a blank page in Chrome. Have tested Firefox and Safari on Mac OS 10.12.6, works fine. Have also tested Safari on iPhone and iPad, seems to be working fine. However, Chrome on iPhone not triggering at all.

Example: http://ndiof.com/elements-laminate-suites/suite-plt202

**Comment by crabbly** [comment]
Hi @jmcarswell , 
It was a bug with the latest version of Chrome v65, which has already been fixed. 
Refer: #137 

Please update your printJS lib to the latest version. 
https://github.com/crabbly/Print.js/releases/latest

**Comment by jmcarswell** [comment]
Thanks!

**Comment by sainisagar310** [comment]
Still not working in Ipad (Chrome).

PrintJs version: 1.0.47
Chrome Version: 68.0.3440.83
