### ISSUE TITLE
Image printing on the demo site not working.

### ISSUE THREAD

**Issue by optone** [crabbly/Print.js#16]
The preview shows blank page when I click a print icon on any of the images. I'm having a similar issue on my site. Was this intended?

http://printjs.crabbly.com/#image

**Comment by crabbly** [comment]
Hey @optone , what browser are you using? Windows or MAC? Include version.

**Comment by optone** [comment]
Hey crabbly, thanks for the quick response.

I'm using Google Chrome Version 55.0.2883.87 m on Windows 10.

**Comment by crabbly** [comment]
Cool, thx. It was supposed to show the preview of the image, not a blank page. I'll look into this.

**Comment by optone** [comment]
Great, thanks a lot! By the way, this is an awesome plugin :)

**Comment by crabbly** [comment]
Glad to hear. If you can, please star the project. :)

**Comment by optone** [comment]
Done!

**Comment by crabbly** [comment]
@optone This issue should be fixed now. Please try the latest release and let me know how it goes.
Thx
https://github.com/crabbly/Print.js/releases/latest

**Comment by optone** [comment]
I can see the images in print preview now. Thanks!
