### ISSUE TITLE
Extra data in image

### ISSUE THREAD

**Issue by desarrollo-nodriza** [crabbly/Print.js#162]
Hi, I need remove the extra tags how title, page number and date form my image.

**Comment by crabbly** [comment]
Hi Nodriza, these are controlled by the user's browser settings. We can't change / remove them using javascript. I would recommend creating a pdf file with the image, then printing that pdf would not show the page title.

Also, keep in mind that you can manipulate the document title by passing the `documentTitle` parameter. 
http://printjs.crabbly.com/#configuration
