### ISSUE TITLE
Pdf to blob etc 

### ISSUE THREAD

**Issue by Brown3246** [crabbly/Print.js#163]
Hi - great work on this!

Is it possible to get hold of the pdf as a blob or equivalent before it is downloaded?

I need to pass it through a crypto tool to get a hash value before it is made available to the user.

I know base64 isn't available but can we grab it as bytes or blobs?

**Comment by crabbly** [comment]
Hi @Brown3246 , the library does not support blobs, unfortunately. I may be adding support for base64 in the future. Maybe we could add blob support as well. 
I'll close this issue and keep #160 opened. 
Thank you.
