### ISSUE TITLE
Image printing does not work but produce two requests

### ISSUE THREAD

**Issue by bearshunter** [crabbly/Print.js#169]
I have tested new version (1.0.43) and can see that there are 2 requests for 'image' print type and print window does not appear at all.
Usage is pretty simple
`printJS({printable: 'link', type: 'image'})`
also I have tried
`printJS('link', 'image')`
Is it possible to fix and have only one request as it was done for PDF?

**Comment by bearshunter** [comment]
I enabled cache and it works but is it possible have one request with no cache? The problem is about logging - I have to log each print on server side and check security stuff before send image. With cache only first request is logged.

**Comment by crabbly** [comment]
The problem with not preloading the images before printing, is that the iframe `load` hook may trigger before the images are loaded inside the iframe. Therefore, printing blank pages.

Could you update the image cache lifetime to a one minute or so?

This way, if the user comes back to that interface and tries to print the image again. The cache will have expired and a new request will be sent to the server.
