### ISSUE TITLE
Printer dialog opens but doesn't show pdf

### ISSUE THREAD

**Issue by Inkperial** [crabbly/Print.js#17]
Hi, I am having the problem that I get the printing dialog but it doesn't display the pdf I want to print in the preview of the dialog.

That's my code:
`$(function(){
			$("#print").click(function(){
				var pdf_link = "invoice/RE_<? echo $variable;?>.pdf";
				printJS(pdf_link);
			});
		});`

It's not because of a wrong pdf_link, cause if I use a wrong link, it shows an error in the printing dialog preview. So I assume that the link is found, but the pdf isn't displayed.
Looking forward to your help!!
Thanks!

**Comment by crabbly** [comment]
Hey @Inkperial , what browser are you using? Windows or MAC? Include version.

Also, please make sure you are using the latest version of the library:
https://github.com/crabbly/Print.js/releases/latest

**Comment by Inkperial** [comment]
Doesn't work here: Mac - Safari 9.1.1
Works like a charm in chrome...

**Comment by crabbly** [comment]
Got it. Thx.
I'll take a look at this as soon as I can.

**Comment by crabbly** [comment]
@Inkperial I'm testing this on a Mac, with Safari 10.0, and it works as expected. Unfortunately, at this time, I won't support older versions for any browser. Could you try to update your Safari? 
And if you can, please let me know if it fixed the issue for you. 

Also, which MAC OS are you using (version)?

**Comment by crabbly** [comment]
@Inkperial Help please!

**Comment by crabbly** [comment]
I can't replicate this issue.
