### ISSUE TITLE
e.printable.charAt is not a function while trying print multiple pdf

### ISSUE THREAD

**Issue by RodrigoZanotta** [crabbly/Print.js#170]
Hi there, first of all thanks for this amazing library.

I'm trying to print multiple pdf generated by the server, but it gives me a "e.printable.charAt is not a function" error.

My code is:

`printJS({
                        printable: files,
                        type:'pdf'
                    });`

each position in the array files contain the url path direct to the file .pdf

Any ideas?

**Comment by crabbly** [comment]
Hi Rodrigo,

The library doesn't support multiple pdf files. The browser would try to preview each file independently. 

Unfortunately I don't know of any solid javascript solution for this.
If you are trying to print multiple files at once, I recommend merging them together into one, on the server side, before sending it to be printed.

**Comment by RodrigoZanotta** [comment]
Hi Rodrigo, thank you for your answer.

No problem, will merge the files now, and use your lib. Thank you :)




www.rodrigozanotta.com.br - (51) 99693-4385


Em seg, 21 de mai de 2018 às 15:27, Rodrigo Vieira <notifications@github.com>
escreveu:
