### ISSUE TITLE
performance: duplicate element style will be added

### ISSUE THREAD

**Issue by zonggang** [crabbly/Print.js#171]
for (let i = 0; i < style.length; i++) {
      for (let s = 0; s < targetStyles.length; s++) {
        if (targetStyles[s] === '*' || style[i].indexOf(targetStyles[s]) !== -1 || targetStyle.indexOf(style[i]) !== -1) {
          elementStyle += style[i] + ':' + style.getPropertyValue(style[i]) + ';'
        }
      }
    }

items in targetStyle will be added 6 times. move the `elementStyle +=` block out of the for loop.

**Comment by crabbly** [comment]
Thank you for pointing this out, Madison.
Just pushed a commit with changes to that loop.
https://github.com/crabbly/Print.js/commit/5f75dbdcee37c8ed597afdfc3a9c2914c1466030
