### ISSUE TITLE
can't add styles and remove top-left margin

### ISSUE THREAD

**Issue by eldosnarbay** [crabbly/Print.js#172]
here is my fiddle: https://jsfiddle.net/L2bpcwaw/17/, 
I am using this library for printing barcodes but I couldn't removed margins and border when printing, 
Any suggestion, Thanks

**Comment by crabbly** [comment]
Hey @eldosnarbay ,
The CDN version wasn't updated. I just pushed the latest version to it. Sorry about that.

Here is your fiddle updated showing the print result without border or margin.
https://jsfiddle.net/L2bpcwaw/19/

**Comment by eldosnarbay** [comment]
but even in this case styles pointed in 'style' attribute doesn't affect to printing element
https://jsfiddle.net/L2bpcwaw/22/

**Comment by crabbly** [comment]
Sorry, the syntax was wrong. 
Here is the correct way to pass the styles:
https://jsfiddle.net/L2bpcwaw/23/

I'll add an example to the documentation soon.

**Comment by Aaqu** [comment]
> Przepraszamy, składnia była nieprawidłowa. Oto prawidłowy sposób przekazywania stylów: https://jsfiddle.net/L2bpcwaw/23/
> 
> Wkrótce dodam przykład do dokumentacji.

Not working for pdf file. Can it be used for pdf?
