### ISSUE TITLE
Print.js not breaking table accordingly

### ISSUE THREAD

**Issue by emilianodelvalle** [crabbly/Print.js#173]
I have a table with thead section. I'm expecting it to be repeated in each page. 
However, that's not happening when sending the table to printjs.
Am I doing something wrong? Isn't that the expected behavior?

**Comment by emilianodelvalle** [comment]
oh, you close it. I understand the workaround, but we are losing original styles.

**Comment by crabbly** [comment]
Just pass your stylesheet using the `css` property.

**Comment by cameronrll** [comment]
Could you please provider an example of how to pass the stylesheet in vue using the css property?
