### ISSUE TITLE
[TypeScript] not allow parameter JSON in printable

### ISSUE THREAD

**Issue by dreamid27** [crabbly/Print.js#174]
hi, thank for your awesome library.
but I get some error when I running your library in my project ( I'm using: angular, typescript).

![image](https://user-images.githubusercontent.com/22621375/40710045-d339de7c-6421-11e8-9ccb-3f9f14af69ce.png)

I try to follow your code below. but when I implement my code , I'm getting this error.

![image](https://user-images.githubusercontent.com/22621375/40710166-25734bc4-6422-11e8-8ae3-952208a6bc2f.png)

the error says **'Types of property printable are Incompatible'**  and I found the problem in your Interface Configuration, which is the interface not apply type JSON. 

![image](https://user-images.githubusercontent.com/22621375/40710380-abd03678-6422-11e8-9559-697386629c6e.png)

Thanks, sorry for my bad English. I hope you understand.

**Comment by crabbly** [comment]
@dreamid27 I just published v1.0.44 to npm. Run `npm update print-js` to get it.
It should allow `printable` as an array of objects.
Reopen this if you are still having issues.
