### ISSUE TITLE
Zoom in browser , effected to result of print preview.

### ISSUE THREAD

**Issue by dreamid27** [crabbly/Print.js#177]
Hi, Thank for your awesome plugin.

but I need help, how I can set off, the zoom of the browser. cause the zoom browser effected to result of the print preview?

Do you have a solution or this is an issue?

Zoom 25%  - Plugin : 

![image](https://user-images.githubusercontent.com/22621375/40897746-0d27d710-67e7-11e8-88a3-7f5c9f5634da.png)

default print function of Browser : 
![image](https://user-images.githubusercontent.com/22621375/40897770-3c210dde-67e7-11e8-88a3-f3a54b9420f1.png)

Zoom 150% - Plugin : 
![image](https://user-images.githubusercontent.com/22621375/40897795-5996aa04-67e7-11e8-88c2-830af25fb513.png)

Default Print function of Browser : 
![image](https://user-images.githubusercontent.com/22621375/40897823-76236bb2-67e7-11e8-9287-c1878a13425a.png)

As you can see, the result of the default print function has the same result. but the plugin has the different result. 

Do you have a solution? where the result still same in any zoom?

Thank you, regards Al Faris.

Sorry for my bad English, I hope you understand.

**Comment by crabbly** [comment]
Hey @dreamid27 , I never realized that changing the browser zoom would affect the print layout, however, I guess it does make sense. When we change the browser zoom, some html elements my move around the properly fit the page, specially if we have a responsive layout. The print result of an html document / element should reflect as much as possible what we see on screen (unless we use print media queries).

When it comes to the issue above, targeting a specific html element will probably have different behavior than printing the entire document (assuming that is `Default Print function of Browser`). If you post complete html and css we could try to dig further into this. Creating a fiddle would be better.

However, I honestly wouldn't try to fix this specific issue with html. I see that you are trying to create an invoice, I would just create a pdf file on the server side, and print that file instead.

**Comment by dreamid27** [comment]
@crabbly ahh thank, you explain very very well. 

previous I'm trying to use **'vw' or '%'** not **'px'**  as unit width or height, to make it responsive.

but it does work just for the view, not for printing document, so I change use px as unit width or height and work well dan not the problem when I zoom browser.

and why I do not use server-side for creating pdf, cause I need edit some data in Invoice, where it can not be done when we already convert to pdf.

But thanks, I will close this issue.

**Comment by crabbly** [comment]
Thank you for the response, Muhammad  :)
