### ISSUE TITLE
performance: duplicate 'margin', 'padding' in targetStyles

### ISSUE THREAD

**Issue by zonggang** [crabbly/Print.js#179]
the style margin and padding will be add many times in params.targetStyles!
the following code will be called every time when invoke the func collectStyles. there will be too many duplicate 'margin', 'padding' in the targetStyles when the honorMarginPadding switch is true.
unfortunately the params.honorMarginPadding is true by default.

if (params.honorMarginPadding) params.targetStyles.push('margin', 'padding')
if (params.honorColor) params.targetStyles.push('color')

**Comment by crabbly** [comment]
Hi Madison, thank you for pointing this out. It didn't make sense to have that logic inside the `collectStyles` function. It was moved to the `print` method in `html.js`. 
https://github.com/crabbly/Print.js/commit/f687160f6056320a736a7085f2c83e5f0e0ddc3b

The `targetStyles` array will be updated before the trying to collect the computed styles.

I'll publish this with the next release.
