### ISSUE TITLE
Print PDF/Image without borders

### ISSUE THREAD

**Issue by awiedemann** [crabbly/Print.js#18]
Hi,

I'm trying to use Print.js to print pictures without border.
I tried both, printing images and PDFs but with no luck, also setting honorMarginPadding to false does not seem to help.
`printJS({printable: "../images/print.pdf", honorMarginPadding: false})`

![screen shot 2017-01-24 at 14 32 53](https://cloud.githubusercontent.com/assets/915125/22249289/a761143a-e242-11e6-959b-e7d291d55c09.png)

Is there a way I can print borderless or is this just not supported?

Thanks,
Andy

**Comment by crabbly** [comment]
Hi @awiedemann The `honorMarginPadding` is for HTML elements styling settings (CSS). Meaning that, if you are printing any element on the page, and that element has a styling setting, for ex. `margin-top: 20px`, you can choose to keep it when printing that element.
However, what you are trying to do is to control the default browser margin settings, which we can't control via javascript (unfortunately).

**Comment by awiedemann** [comment]
Hi @crabbly Thanks for sharing this. In this case I need to continue my search for an alternative way to get it printed borderless.
Thanks!

**Comment by jack-fdrv** [comment]
var style = '@media print { body { margin: 0; color: #000; background-color: #fff; } img {width:100%;} }';
			printJS({
				printable: ['https://printjs.crabbly.com/images/print-02.jpg', 'https://printjs.crabbly.com/images/print-03.jpg'],
				type: 'image',
				style: style,
			});

**Comment by kinguru** [comment]
It doesn't help for me. I've 2 pages in preview - 1st page is my image, 2nd page is completely blank. :(
When printing PNG image directly with same printer parameters it looks correct

**Comment by SeeSharpDeveloper** [comment]
```js
const dataURL = canvas.toDataURL();
printJS({
    printable: dataURL,
    type: 'image',
    style: '@media print {body {margin: 0px; } img { height: 100vh; display: block; }}',
});
```

I had the same Problem for printing a canvas and was able to solve it by adding display:block to the img
