### ISSUE TITLE
Canvas content is not printed

### ISSUE THREAD

**Issue by KingRial** [crabbly/Print.js#181]
If you have a canvas inside the printable DOM element, only its DOM structure is cloned but it won't be printed since the canvas content is not [cloned](https://stackoverflow.com/questions/3318565/any-way-to-clone-html5-canvas-element-with-its-content).

**Comment by crabbly** [comment]
Hi Riccardo, thank you for reporting this.

We will have to add this functionality to the library, when processing html.

I created a fiddle for test purposes:
https://jsfiddle.net/crabbly/kenhtxqo/

**Comment by ice6** [comment]
@KingRial I encountered same problem when I print a qrcode, then I change the qrcode's placeholder from canvas to img(base64).
Just for reference. Not for solving this problem.

**Comment by crabbly** [comment]
For ref: https://github.com/crabbly/Print.js/issues/267

**Comment by crabbly** [comment]
We will have to create a new implementation to process and clone the HTML without using `cloneNode`.

**Comment by crabbly** [comment]
The latest version has now support for html print with canvas elements. It should print canvas content as expected.

Run `npm update print-js` to get it.

Please let me know if any issues.

**Comment by crabbly** [comment]
I have updated the fiddle with the new code:
https://jsfiddle.net/crabbly/kenhtxqo/

Also, the repo has a test file with multiple HTML examples in it, there is a canvas element, checkbox and other form elements there as well. The lib will copy the user state for checkboxes and select (option selected) when printing, which wasn't supported before as well.

Please reopen this if necessary. Thank you guys.

**Comment by crabbly** [comment]
The latest version of the library does now support html print with canvas elements. It should print canvas content as expected.

Run `npm update print-js` to get it.

Please let me know if any issues. Thank you.
