### ISSUE TITLE
unable to reload page when print pop up is opened

### ISSUE THREAD

**Issue by sanals** [crabbly/Print.js#183]
what prevents current page say 'page_1' from reloading when crabbly's print pops up in 'page_1'? The same reason prevents me from reloading the parent page say 'page_0', since i am loading 'page_1' from 'page_0' with window.open('page_1'). I am unable to do any  task in the parent(page_0) page when the print window is opened within the child(page_1) page.

**Comment by crabbly** [comment]
Hi @sanals , I'm not sure I understand what you are talking about. 
Could you please post some code here? 
Thx.
