### ISSUE TITLE
can Print multi page html support quickly

### ISSUE THREAD

**Issue by WwJoyous** [crabbly/Print.js#184]
thank 's author

i want to print  multi(about 20-30 page) page html, but open very very slow. What should I do? used type pdf? can preview the first few pages and  print all

**Comment by crabbly** [comment]
Hey @WwJoyous , 

For this many pages, is better not to have the library process the html style. Try passing your stylesheets using the `css` property. And disable the style processing by passing `scanStyles` as `false`.

Ex.:
`printJS({ printable: 'myHtmlElement', type: 'html', scanStyles: false, css: '/my_stylesheet.css' })`

**Comment by WwJoyous** [comment]
Thank's for getting back to me , can i ask your a question? please.
I do this  OK，scanStyles as false is quickly. but html layout  is different scanStyles as true,the style is effective. this html layout
like flex. this is not what I want, what can i doing

**Comment by crabbly** [comment]
I has to help without looking at your code. Try not to write any in-line style in your html, and instead, create classes and use one or more stylesheet files. Then, pass these files in using the `css` parameter.
Another thing, if your html print job has 20-30 pages, you may be printing some kind of data table. If that is the case, I recommend creating a pdf file on the server side and print that instead.

**Comment by WwJoyous** [comment]
Thanks very much.
I have fix this question. may be my project  js framework  cause，now test html print 150-200 pages also very quickly. It's really good. You are really good

**Comment by crabbly** [comment]
Glad to hear that you got it working :)
