### ISSUE TITLE
When printing a DIV with a SVG, the SVG is not rendered

### ISSUE THREAD

**Issue by robpal94** [crabbly/Print.js#185]
When trying to print a `DIV` element which has an `SVG` Element inside it, the svg is not rendered. It is only displayed as a black rectangle, which fills the dimensions specified in the `svg` root attribute. 

For printing Im using:

```
print.default({
    printable: 'myDiv',
    type: 'html'
});
```

**Comment by robpal94** [comment]
Hey, thanks for your comment. 
Here is a very simple example which describes the issue. 
http://jsfiddle.net/7cdh4Lew/1/

If you can see, the coloured square is just black in the printed document. 

**Some Screenshots**

The rendered SVG:
<img width="486" alt="screen shot 2018-06-29 at 09 10 23" src="https://user-images.githubusercontent.com/38498731/42078335-5361b932-7b7c-11e8-95fa-4c8c1cb0591c.png">

The chrome print preview
<img width="1002" alt="screen shot 2018-06-29 at 09 10 31" src="https://user-images.githubusercontent.com/38498731/42078344-59851886-7b7c-11e8-85fe-4781d17ce35d.png">

**Comment by crabbly** [comment]
Hey Robin, thanks for the fiddle.

I passed `targetStyles: ['*']` and that seems to have fixed the problem.
Give it a try:
http://jsfiddle.net/7cdh4Lew/3/

**Comment by crabbly** [comment]
Hi Robin, I'm closing this since I believe the solution above fixes the issue. Please reopen if you are still having problems. Thx.
