### ISSUE TITLE
checkbox checked is not printed

### ISSUE THREAD

**Issue by gil2gm** [crabbly/Print.js#187]
i have a problem with icons and checkbox checked, it is no print, please some help

i use:
onclick="printJS({printable: 'printableDocInscription', targetStyles:['*'], type: 'html', documentTitle:'Ficha de Isncripción' })

on html:

<input type="checkbox" id ="1" value="1" checked>

**Comment by crabbly** [comment]
Hi Gilberto, thanks for reporting this.

It looks like checkboxes are not printing properly. I created a fiddle for us to play with it and hopefully implement a fix soon.
https://jsfiddle.net/crabbly/2mob0psy/

**Comment by crabbly** [comment]
Just an update...this issue is due to the use of `cloneNode` in `html.js`. https://github.com/crabbly/Print.js/blob/master/src/js/html.js#L18

It won't "copy" any `select` or `checkbox` user selected / state to the iframe cloned html, when printing.

**Comment by crabbly** [comment]
Checkbox state is now supported by the library. Please run `npm update print-js` to get the latest version.

Feel free to reopen this if any issues. Thank you.
