### ISSUE TITLE
Can't get pseudo-elements

### ISSUE THREAD

**Issue by Shmaur** [crabbly/Print.js#190]
.first_three {
      position: absolute;
      top: 5px;
      right: 10px;
    }

td[class="first"] {
    width: 100px;
  }
  td[class="first"]::before {
    content: "";
    position: absolute;
    width: 1px;
    height: 137px;
    top: 0;
    left: 110px;
    background-color: #dfdfdf;
    display: block;
    transform: rotate(-64deg);
    transform-origin: top;
    -ms-transform: rotate(-70deg);
    -ms-transform-origin: top;
  }
  td[class="first"]::after {
    content: "";
    position: absolute;
    width: 1px;
    height: 235px;
    top: 20px;
    left: 0;
    background-color: #dfdfdf;
    transform: rotate(-80deg);
    transform-origin: top;
    -ms-transform: rotate(-45deg);
    -ms-transform-origin: top;
  }

**Comment by crabbly** [comment]
Hi @Shmaur , to print pseudo elements, pass your stylesheet files using the `css` parameter or the style directly using the `style` parameter.
http://printjs.crabbly.com/#configuration

Here is a fiddle with an example:
https://jsfiddle.net/crabbly/x8t76k3c/

**Comment by OlesyaKlochko** [comment]
@crabbly Hi again! I have the question about this issue.. I also have pseudo elements in my printable reports, and for now I've added styles to `style` parameter, what is not very nice for me.., that means I need to duplicate styles, because all styles are scoped in my vue components. So are you going to implement pseudo elements with styles in the feature? 🤔  😄

**Comment by crabbly** [comment]
Hi @OlesyaKlochko, I'm not how we could add support for pseudo elements. The `getComputedStyle` accepts a second param which is a string to target the desired pseudo element, however, we wouldn't know what to target. 
https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle
Ideas?

Having your CSS scoped to single file vue components will indeed force you to duplicate the style (at this moment). However, extracting this style into its own style sheet (ex.: independent sass files outside your vue components), would allow you to pass the compiled stylesheet into the print function, eliminating the duplication.
