### ISSUE TITLE
Uncaught DOMException error in console

### ISSUE THREAD

**Issue by meshorti** [crabbly/Print.js#192]
For some reason the print pdf isn't working for me. I see this error in the console when clicking the print button:

`Uncaught DOMException: Blocked a frame with origin "https://blog.myfitnesspal.com" from accessing a cross-origin frame.`

This is happening here when you click on the print icon next to the "4-Week" poster:

https://blog.myfitnesspal.com/your-ultimate-4-week-core-strength-plan/

Any ideas why this is not working?

**Comment by crabbly** [comment]
Hey Luke,
I'm not sure why you are getting this message, since the pdf is coming from the same hosting server.
Anyways, you can quickly fix this by passing the `showModal` parameter as `true`. This will force the library to preload the pdf with an ajax call, which will then create a local blob file, preventing any cross site error messages.
You can customize the modal message with the `modalMessage` parameter.
Here is the configuration with all the available parameters: 
http://printjs.crabbly.com/#configuration

And here is an example printing external pdf files: 
http://plnkr.co/edit/kxn1TuoP9Dxj75jrdl5W?p=preview

Let me know if this works for you.

**Comment by meshorti** [comment]
Thanks crabbly! This didn't seem to fix it, but I just remembered we are using a CDN to deliver assets. So it's probably trying to print from:

https://1y2u3hx8yml32svgcf0087imj-wpengine.netdna-ssl.com/wp-content/uploads/2018/05/UACF-4-week-core-strength-PDF.pdf

Is there a way around this?

Really appreciate your quick responses. Sorry for my delay over the weekend. :)

**Comment by crabbly** [comment]
Got it.
Like I have mentioned, if you set the `showModal` parameter as `true`, it will probably work. 
Or, you could use the `onLoadingStart` parameter instead, for more customization. 

Either way, they should bypass the `cross-origin` warning.

ps.: `showModal` demo with an external file: http://plnkr.co/edit/kxn1TuoP9Dxj75jrdl5W?p=preview

**Comment by meshorti** [comment]
Gotcha. So here's what I have. It shows the "Loading PDF..." message, but still getting same error:

```
<a onclick="printJS({
    printable: '/wp-content/uploads/2018/05/UACF-4-week-core-strength-PDF.pdf',
    type: 'pdf',
    showModal: true,
    modalMessage: 'Loading PDF...'
  })">Print PDF</a>
```

How would I use onLoadingStart?

**Comment by crabbly** [comment]
How are you loading the library into the project?

**Comment by meshorti** [comment]
In an external file in the <head> section.

**Comment by crabbly** [comment]
Are you using the CDN? If not, please download and use the latest version:
https://github.com/crabbly/Print.js/releases/latest

I think you may have an outdated version of the library.

Here is a test printing your document using the lib CDN:
http://plnkr.co/edit/QJ1uBylDECvhNSkzWfLQ?p=preview

**Comment by meshorti** [comment]
Ok looks like it might be a server configuration. Having WPEngine look at this.

**Comment by crabbly** [comment]
It seems the problem is with your code. I'll close this now. Feel free to reopen if necessary.

**Comment by marketmi** [comment]
Using above example with Chrome on Android (Version 74.0.3729.157) still throws the DOMException. Trying to print it with Chrome on Windows works fine.
Do you have any idea on how to fix it?

**Comment by matyasbach** [comment]
> http://plnkr.co/edit/QJ1uBylDECvhNSkzWfLQ?p=preview

This doesn't work anymore in Chrome (ver. 76, Windows) :/

**Comment by budthapa** [comment]
Doesn't work in Chrome Version 77.0.3865.90 (Official Build) (64-bit) Ubuntu 18.04.
Uncaught DOMException: Blocked a frame with origin "http://localhost:8080" from accessing a cross-origin frame. Works in Opera

http://plnkr.co/edit/QJ1uBylDECvhNSkzWfLQ?p=preview doesn't work as well.

**Comment by happy4upa** [comment]
Hi, the same issue is on the printjs website now:

print.js?v1.0.61:1 Uncaught DOMException: Blocked a frame with origin "https://printjs.crabbly.com" from accessing a cross-origin frame.
    at d (https://printjs.crabbly.com/print.js?v1.0.61:1:2207)
    at HTMLIFrameElement.o.onload (https://printjs.crabbly.com/print.js?v1.0.61:1:2015)
