### ISSUE TITLE
Printing Array of PDF's or Word documents

### ISSUE THREAD

**Issue by Jayaharshak** [crabbly/Print.js#193]
Need to print batch of PDF documents or Word documents with Single function call. 
As of now i can see multiple images printing, But Multiple documents or files printing is needed.

**Comment by crabbly** [comment]
Hi Jayaharshak, the library can't merge pdf files. It also doesn't support word documents. I recommend manipulating the documents on the server side and sending one final pdf out, to be printed in the front end.
