### ISSUE TITLE
Can't Show Image In HTML Type

### ISSUE THREAD

**Issue by h4rm41n** [crabbly/Print.js#194]
Black space is Image content in HTML Tag

```
printJS({
     printable:'data_print', 
     type:'html', 
     showModal:true
})

```

![screenshot from 2018-07-13 09-18-35](https://user-images.githubusercontent.com/19913777/42667379-c35f5706-867d-11e8-8f45-74ee92739a59.png)

**Comment by crabbly** [comment]
Hey Ahmad, 

There is not way to know what's going on without your html and css code here.

Please try passing `targetStyles` as `['*']` to see if that does the job.
Here is a fiddle with the library printing html with images.
https://jsfiddle.net/crabbly/mLyqnLr1/

**Comment by h4rm41n** [comment]
Solved, i try added this code
```
printJS({
         printable:'data_print', 
         type:'html', 
         showModal:true,
         targetStyles: ['*']
      })
```
