### ISSUE TITLE
Printing does not work on chrome

### ISSUE THREAD

**Issue by XardasLord** [crabbly/Print.js#195]
Printing does not work on chrome while to the printable array I add few API GET requests which return a link to the image.

On the other browsers (IE, Firefox) it works fine. Only on Chrome just nothing happens. No errors.
When I put direct links to images the printable array it works fine. It seems, that this delay or something is making this issue.

**Comment by crabbly** [comment]
Hi @XardasLord , 

Could you please write some code here?
As well include what kind of image size you are trying to print. 
Thank you.

**Comment by XardasLord** [comment]
Each image is about 400kB size. I try to print 5 images.

I call print method like this: 
```
printJS({
          printable: this.files, 
          type: 'image', 
          documentTitle: 'DocumentTitle'
        });
```
And my this.files array is something like this:
```
(...)
this.files.push(${API_URL}/attachments/${attachmentId}/page/0);
this.files.push(${API_URL}/attachments/${attachmentId}/page/1);
this.files.push(${API_URL}/attachments/${attachmentId}/page/2);
this.files.push(${API_URL}/attachments/${attachmentId}/page/3);
this.files.push(${API_URL}/attachments/${attachmentId}/page/4);
```

As I mentioned before on the other browsers it works fine, even on IE.

**Comment by crabbly** [comment]
Thank you for posting the code.

For your code to work, `${API_URL}/attachments/${attachmentId}/page/page_number` must return an image. Please confirm the api response header content type.

I created a fiddle to print multiple remote images, and it works fine in Chrome. I tested the latest version v68 in Windows 10 and MacOS.
https://jsfiddle.net/crabbly/oqea0rLm/

What OS and version are you using? Are you testing this in Chrome's latest version?

**Comment by XardasLord** [comment]
My Chrome version: **67.0.3396.99** I don't have access to update my Chrome version, cause this option is blocked by the administrator.
OS: **Windows 10 Pro**

My API endpoint, which gets the image looks like this:

```
var model = _attachmentsService.GetAttachment(id);

            if (model == null)
                return NotFound();

            var responseMessage = new HttpResponseMessage(HttpStatusCode.OK);
            responseMessage.Content = new StreamContent(model.AttachmentStream);
            responseMessage.Content.Headers.ContentType = new MediaTypeHeaderValue("image/png");
            responseMessage.Content.Headers.ContentDisposition = new ContentDispositionHeaderValue("attachment");
            responseMessage.Content.Headers.ContentDisposition.FileName = model.OriginalFileName;

            return ResponseMessage(responseMessage);
```

It does return an image, when I just paste the URL in the browser it shows me an image. But it does work on the other browser :/ But when I add to files array directly images URLs it works. It has some problem retrieving image from the API.

**Comment by XardasLord** [comment]
Yes it works on my machine.

**Comment by crabbly** [comment]
Hey @XardasLord , 
I looked into this again and I don't think there is anything we could change in the library. Looks like the issue is with your api response. 

Looking at your api code and response, I would recommend removing the `Content-Disposition` header, since you don't want the user to download your file.

In your api endpoint, remove these two lines of code and see if it works.

```
responseMessage.Content.Headers.ContentDisposition = new ContentDispositionHeaderValue("attachment");
responseMessage.Content.Headers.ContentDisposition.FileName = model.OriginalFileName;
```

**Comment by XardasLord** [comment]
@crabbly 
Really strange situation. The funny thing is that it works on the other browsers except Chrome. Here is my API GET endpoint on which it still does not work with Chrome.
![image](https://user-images.githubusercontent.com/29070326/42986758-28100dde-8bf7-11e8-868f-1786e4d74872.png)

I really have no idea what is wrong.

**Comment by crabbly** [comment]
Sweet!
I have no idea why you had to do that, however, it seems like a very specific issue with the api response and Chrome. Doesn't look like an issue we should tackle in the library.

Thanks for posting the update here. :)
