### ISSUE TITLE
no dist in bower installation?

### ISSUE THREAD

**Issue by jahrralf** [crabbly/Print.js#197]
Would be great to find the dist files after adding the package via bower. Thanks!

**Comment by crabbly** [comment]
Hey @jahrralf , thanks for pointing this out. 
Looks like bower uses the git repo with doesn't have the dist files.
I recommend using yarn or npm instead, since `.npmignore` is configured to include the dist files. 

Any idea how we can accomplish this with bower? 
Thx.

**Comment by crabbly** [comment]
I gave up on supporting bower, mostly because of the limited time I can dedicate to the library. 
If anybody wants to write a script for bower releases, I PR would be welcome. Thank you.
