### ISSUE TITLE
JSON Type Custom Styles

### ISSUE THREAD

**Issue by AlwaysAbhl001** [crabbly/Print.js#198]
Thanks for the wonderful plugin.

In our use case we print `JSON` data but we don't want to represent in table form. Is there any chance of customising the styles for `JSON`.

{name:'x', id: 1, reason: 'abc'},{name: 'y', id: 2, reason: 'pqr'}

**expect:**
abc
1  x

pqr
2 y

As well as is there any chance of customising document title size and remove the date on top left corner?

**Comment by crabbly** [comment]
Hi @AlwaysAbhl001 , the JSON print feature is a quick way to print JSON data in table / grid format. You can customize the table style, but what you want to do, is a very specific layout. 

What you can do here, is to create a hidden html element/ template, display your data in it however you want, and them print that html element. You can control the hidden element style when sending it to printJS, forcing it to show when printing. 

About the date at the top left corner, that's a user browser setting, and it cannot be controlled with Javascript.
