### ISSUE TITLE
Printing is Not working 

### ISSUE THREAD

**Issue by rcdosado** [crabbly/Print.js#2]
line 293 of print.js
        //append iframe element to document body
        documentBody.appendChild(this.printFrame);

is saying 
       Uncaught TypeError: Cannot read property 'appendChild' of undefined

on inspection using chrome debugger, this.printFrame is returning undefined, maybe somethings wrong with getting printFrame? thanks

**Comment by crabbly** [comment]
I found a possible scope issue. 
Just pushed a fix for it. 
Try using this release: https://github.com/crabbly/Print.js/archive/v1.0.3.zip
Please let me know how it goes.

**Comment by rcdosado** [comment]
it works. thanks!

**Comment by crabbly** [comment]
@rcdosado YW! :)
