### ISSUE TITLE
Website Documentation`

### ISSUE THREAD

**Issue by TechTrain** [crabbly/Print.js#20]
All of the code samples on the printjs website (http://printjs.crabbly.com/) are not showing because the HTML "<" and ">" characters have not been escaped. Instead of showing the code, the browser is attempting to parse the code and the boxes that are supposed to provide documentation are just blank.

**Comment by crabbly** [comment]
Hey @TechTrain , I'm not getting that. Which browser and OS are you using? Please include version.
Thank you.

**Comment by crabbly** [comment]
@TechTrain Help please.

**Comment by TechTrain** [comment]
Version 55.0.2883.87 (64-bit) running on Windows 10. Works in IE 11.

**Comment by TechTrain** [comment]
There are 3 boxes that populate correctly, the rest are empty. The first that populates is the code that comes after "We have the following data set in our javascript code. This would probably come from an AJAX call to a server API:", the next that populates is the code that comes after "To install using npm:" and the last is the code that comes after "CDN is also available, thanks to KeyCDN:".

**Comment by TechTrain** [comment]
In a side-by-side code inspection, I can see that in Chrome, the `<code>` element is not being populated with the same contents as in IE.

![image](https://cloud.githubusercontent.com/assets/11021564/22748562/71044f08-edf8-11e6-9a24-28b8f0f5a8e4.png)

**Comment by crabbly** [comment]
Perfect. I haven't noticed this problem with IE, but will double check and hopefully get it fixed.
Thank you for all the info @TechTrain

**Comment by TechTrain** [comment]
Just to be clear... It works in IE. It's Chrome where there is a problem.

**Comment by crabbly** [comment]
Whoops, that's what I meant.
I use Mac, and the library works well in Chrome. I believe the problem is with Chrome in Windows. I have a Windows VM and will run some tests soon. 
That's why your information helps a lot. Thanks again. I'll post updates here.

**Comment by TechTrain** [comment]
Ok, but (just to be clear again), the problem isn't with the library, it's with your website.

**Comment by crabbly** [comment]
haha. That's right. Sorry, multitasking big time here. Thx.

**Comment by crabbly** [comment]
@TechTrain I couldn't replicate the issue with Chrome (v56) in Windows 10. However, I escaped the html code used on the documentation page. 
Whenever you have a chance, could you please check if this fixes the issue?

**Comment by TechTrain** [comment]
All the boxes now show code EXCEPT the last two (the "Getting Started" section):
![image](https://cloud.githubusercontent.com/assets/11021564/22792108/a0333034-eeb9-11e6-96ae-f06e1dc14fa3.png)

**Comment by crabbly** [comment]
Perfect! I just escaped those as well.
Thank you for your help @TechTrain :)

**Comment by TechTrain** [comment]
Yup. Looks good now!

**Comment by crabbly** [comment]
Hey @TechTrain , if you like the library, please start the project. Thank you again for your help.
