### ISSUE TITLE
input checkbox break into new line

### ISSUE THREAD

**Issue by cahyowhy** [crabbly/Print.js#201]
something strange here. 

// actual
![image](https://user-images.githubusercontent.com/18083469/43568059-da480be4-965d-11e8-8887-8624f1ba448a.png)

// printed
![image](https://user-images.githubusercontent.com/18083469/43567938-8a7da664-965d-11e8-93b7-2ef1a1abcefb.png)

tested in chrome browser

**Comment by crabbly** [comment]
Hey cahyo, 
Thank you for reporting this.

There is an issue when printing checkboxes and select elements (dropdowns). I haven't had the time to work on a solution yet.

I'll close this issue in favor of #187 , to prevent duplication. 
Once a solution has been pushed to npm, I'll post an update here as well.

**Comment by crabbly** [comment]
Checkbox state and previously unsupported elements are now supported by the library.
Please run `npm update print-js` to get the latest version.

Feel free to reopen this if any issues. Thank you.
