### ISSUE TITLE
image not showing up or resize 

### ISSUE THREAD

**Issue by k8martian** [crabbly/Print.js#203]
I am using react and printing html invoice with 2 images in it. Top image has disappeared and bottom image got resize to smaller image. Anyone with problem like this? Thanks

**Comment by crabbly** [comment]
Have you tried using the targetStyles parameter?
Please post your printJS function usage here. Thx

**Comment by k8martian** [comment]
I change my function 
printJS({
	printable: 'invoice', 
	type: 'html',
	showModal: true,
	targetStyles: ['*'],
})

now its working thanks
