### ISSUE TITLE
set own header and footer

### ISSUE THREAD

**Issue by k8martian** [crabbly/Print.js#206]
Hi, I wonder if this library able to let us setup our own header and footer so it will know where to break up the content itself to multiple pages with the same header and footer. Thanks

**Comment by crabbly** [comment]
Hi @k8martian , this can be done with CSS media queries. The library is compatible with it. As far as instructions, there are a lot of content online. 

A quick search ...
https://stackoverflow.com/questions/1360869/how-to-use-html-to-print-header-and-footer-on-every-printed-page-of-a-document#4121962

For data tables, you don't even need that:
https://stackoverflow.com/questions/8356881/print-header-footer-on-all-pages-print-mode

**Comment by raymart17** [comment]
Hi sir, i'll just ask if you have made a version of this with header and footer feature? Thank you in advance.
