### ISSUE TITLE
print.min.js works print.js dosent work

### ISSUE THREAD

**Issue by yogevge** [crabbly/Print.js#208]
Hi, I am using the library print.js 
http://printjs.crabbly.com
installed it by NPM with command

> npm install print-js --save

and added the print.js file to the library.
The line `printJS("pdf/QR_Sticker.pdf");` is undefined.
I then downloaded manually https://github.com/crabbly/Print.js/releases/tag/v1.0.47 the print.min.js and the line `printJS("pdf/QR_Sticker.pdf");` worked fine.
Of course, this is not idle, because all the team needs to download it manually etc... 
anyone else had this problem?

p.s its all in Chrome

**Comment by crabbly** [comment]
Hi @yogevge , did you import the library somewhere in your code?

ex.: `import print from 'print-js'`

**Comment by yogevge** [comment]
Hi @crabbly  that's the whole difference.
both files are in my project, the only thing I change is the import (from print.min.js which works to print.js that doesn't)

**Comment by crabbly** [comment]
You shouldn't be targeting any `.js` file directly. 
Please post your import code here. 

Also, please check if you have the latest lib version in your package.json.

**Comment by yogevge** [comment]
package.json:
`    "print-js": "^1.0.47",`
my code:
`    <script type="text/javascript" src="~/js/print.min.js"></script>
    <script type="text/javascript">
    app.controller('receptionist', ['$scope', '$http', function ($scope, $http) {
        $scope.tests = @Html.Raw(Json.Serialize(@ViewBag.vbTests));
        printJS('pdf/QR_Sticker.pdf');`  
when I replace it with:
`    <script type="text/javascript" src="~/js/print.js"></script>
    <script type="text/javascript">
    app.controller('receptionist', ['$scope', '$http', function ($scope, $http) {
        $scope.tests = @Html.Raw(Json.Serialize(@ViewBag.vbTests));
        printJS('pdf/QR_Sticker.pdf');`  it dosent work.

**Comment by crabbly** [comment]
I'm not sure were you are getting `print.js` from. However, you should either import the library with npm or use the minified file.
http://printjs.crabbly.com/#download
