### ISSUE TITLE
font weight style not applying after latest version

### ISSUE THREAD

**Issue by formaldehydeson** [crabbly/Print.js#209]
Updated my app using the following printJS line to v1.0.47, and the font-weight styles are not applying throughout the document:

printJS({printable:'legal-text-en', type:'html', font: 'Arial', showModal: true, targetStyles: ['*'], style: 'h6 {font-size: 20px; font-weight: bold;}'})

when I reverted to v1.0.45 the issue was resolved

**Comment by crabbly** [comment]
Hi @formaldehydeson , thanks for reporting this. I will take a look at it whenever I have a chance.

**Comment by crabbly** [comment]
Hey @formaldehydeson , I finally got this. I ran some tests and cannot replicate the issue.

Here is a sandbox using the latest version of the library, showing that using the `style` parameter, I was able to change the font weight of one of the paragraphs in the example.
https://codesandbox.io/s/x72j429vr4

Try updating the lib to the latest version (1.0.52 at this moment). Also, maybe the element in your code already had a `font-weight` property applied, and that could be creating the issue. You may want to pass `!important` just to force the print style.

Please reopen this if you can reproduce the issue with either a codesandbox or fiddle.
Thank you.
