### ISSUE TITLE
IE 11 considers webpack bundle invalid

### ISSUE THREAD

**Issue by EricLease** [crabbly/Print.js#21]
![image](https://cloud.githubusercontent.com/assets/11588015/22711953/02de4594-ed51-11e6-8bc4-a9c4fe34442a.png)

![image](https://cloud.githubusercontent.com/assets/11588015/22711982/297828e6-ed51-11e6-90f5-f5eb5f414d92.png)

This can be resolved by adding semicolon, and `function`, like so...

![image](https://cloud.githubusercontent.com/assets/11588015/22712226/0b3f9c64-ed52-11e6-8288-8d28f842e6ce.png)

Tested
- IE 11.0.9600.18537 Update Version 11.0.38
- FF 51.0.1 (32-bit)
- Chrome 55.0.2883.87

This may be related to the version of webpack (`"webpack": "^1.13.2"`) that I'm using.  I don't know.  Pull request incoming.

**Comment by crabbly** [comment]
It could be. I use webpack version 2 and have no issues with this. As you can check on http://printjs.crabbly.com. It uses a bundle file created with webpack. 
I'll merge the commit since it works with webpack 2.x as well. Thank you @EricLease

**Comment by crabbly** [comment]
@EricLease If you like the library, please star the project. Thank you.

**Comment by EricLease** [comment]
Starred.  I know I should be migrating to webpack 2, but I just have other higher priority tasks right now and really would like to use your library.  This change is simpler than dealing with webpack 1->2 migration right now.  Thank you for accepting.

**Comment by crabbly** [comment]
Yea, is hard to keep everything up to date. Thank you for contributing. :)
