### ISSUE TITLE
is printing multiple divs as multiple pages possible?

### ISSUE THREAD

**Issue by Khaled-KR1204761** [crabbly/Print.js#212]
I know you can do it with pictures but it seems like you can't with divs? Thanks.

**Comment by crabbly** [comment]
Hi Khaled, that's correct. The library has no such feature. 
However, you can create your own html layout, in a hidden element. Then when printing the hidden element, use the `style` parameter to show the element when printing. You can also use CSS print media queries as well, using the `css` parameter.
http://printjs.crabbly.com/#configuration
