### ISSUE TITLE
Broken for IE11, expected ':'

### ISSUE THREAD

**Issue by divspace** [crabbly/Print.js#214]
Works fine in other browsers, but the latest release about 5 hours ago breaks in IE11 now. Looks to be from `src/js/init.js` but hard to tell. See attached.

![image](https://user-images.githubusercontent.com/10470082/44608942-9d4abd00-a7aa-11e8-8868-57f6437e9f83.png)

![image](https://user-images.githubusercontent.com/10470082/44608954-ab004280-a7aa-11e8-95fc-ba9e18fb4d03.png)

**Comment by crabbly** [comment]
Hi @divspace , 
Thanks for reporting this issue. I will look into it.

**Comment by crabbly** [comment]
This has been fixed. Just run `npm update print-js` to get the latest version.
