### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by worawutboy** [crabbly/Print.js#216]
When print
ERROR Error: Uncaught (in promise): TypeError: print_js__WEBPACK_IMPORTED_MODULE_2___default(...) is not a function

**Comment by crabbly** [comment]
Hi @worawutboy , 
Make sure to correctly import the library into your project:
`import print from 'print-js'`

If you are still having issues, reopen this issue but please post more information here, like how you are importing the library, where, etc..

**Comment by crabbly** [comment]
Just published a new version to npm which has proper support for module import.
The library will still expose a global variable `printJS`, but the recommend usage now should be to import the package at the same file where it will be used:

For ex.:

`import printJS from 'print-js'`

`printJS('path-to.pdf')`

Run `npm update print-js` to get the latest version.
