### ISSUE TITLE
Remove header and footer of pdf (page size, date, url)

### ISSUE THREAD

**Issue by ibecir** [crabbly/Print.js#218]
Hello,

When creating PDF from html is it possible to remove header and footer data as shown in picture below?

Thank you in advance

![image](https://user-images.githubusercontent.com/15219309/44723843-6d185c80-aad1-11e8-989e-26ef6b259b1a.png)

**Comment by crabbly** [comment]
Hi @ibecir ,
Unfortunately we can't control the print job header and footer with Javascript.
This is controller by the user's browser settings.

To accomplish that, you can create a PDF file on the server side, and have the user print that file instead. When printing PDF documents, the browser won't attach any header or footer.

Refer to #145, #161, #162, #205, #211

**Comment by BugaySarikaya** [comment]
Try, 
@page { margin-top: 30px; margin-bottom: 30px;}

**Comment by Connum** [comment]
> 
> 
> Try,
> @page { margin-top: 30px; margin-bottom: 30px;}

This didn't work for me, but after adding the following to the HTML, it works like a charm!

```html
<style type="text/css" media="print">
	@media print
	{
		@page {
		margin-top: 0;
		margin-bottom: 0;
		}
		body  {
		padding-top: 72px;
		padding-bottom: 72px ;
		}
	} 
</style>
```
(found at https://stackoverflow.com/questions/585254/how-to-remove-the-url-from-the-printing-page#answer-48439708)
