### ISSUE TITLE
connecting to vuejs error

### ISSUE THREAD

**Issue by bifjhh** [crabbly/Print.js#221]
import printJS from 'print-js'
startPrint() {
        printJS({ printable: 'printForm', type: 'html' })
      }
![image](https://user-images.githubusercontent.com/29394439/45077609-2ef9e900-b120-11e8-8e45-9fe19ba8ae00.png)

**Comment by crabbly** [comment]
Hi @bifjhh ,

When you import the lib inside the same file you are writing your code (same scope, in your case, inside your Vue component), using `import printJS from 'print-js'` is a problem, since the variable `printJS` will be overwritten.

Use `import print from 'print-js'` instead. Or just `import 'print-js'`.

The library automatically exposes a global variable `printJS`.

Ref #217

**Comment by crabbly** [comment]
Just published a new version to npm which has proper support for module import.
The library will still expose a global variable `printJS`, but the recommend usage now should be to import the package at the same file where it will be used:

For ex.:

`import printJS from 'print-js'`

`printJS('path-to.pdf')`

Run `npm update print-js` to get the latest version.

**Comment by piotrorlowski** [comment]
sorry, how to use it with Vue.use()? because I am getting error here 

import printJS from 'print-js';
Vue.use(printJS);

`Unexpected argument type! Expected "string" or "object", got function`

**Comment by crabbly** [comment]
Hey @piotrorlowski, `Vue.use` is meant to use with Vue.js plugins. Print.js is not a Vue plugin, is a plain javascript library.
https://vuejs.org/v2/guide/plugins.html

You can just import the library inside the vue component that you are trying to implement a print option.

If you are using single file components in vue, the `.vue` files, you can just import print-js inside your script tag, right before you export your vue component:

`import printJS from 'print-js'`

**Comment by piotrorlowski** [comment]
After I install it with `yarn add print-js`, I import in `.vue` template as 

`import printJS from 'print-js';`

in script tag.

If I do this

`    printExternal(url) {
      this.printJS(url, 'html');
    },`

I get

`this.printJS is not a function`

If I use `printJS` in template like 

`@click="printJS(path/to/html, 'html')"`

I get 

![image](https://user-images.githubusercontent.com/23028687/57875424-37f49b80-7813-11e9-9296-14baaca4b7ea.png)

**Comment by piotrorlowski** [comment]
`this` was unnecessary I think... I got this working, thanks.
