### ISSUE TITLE
Error print in IE

### ISSUE THREAD

**Issue by avoronkoff** [crabbly/Print.js#222]
Error message in IE in this function
`isFirefox: () => {
    return typeof InstallTrigger !== 'undefined'
}`
i`m using npm module print.js
please fix it, thanks

**Comment by crabbly** [comment]
Could you please post the error message and IE version? Thx.

**Comment by avoronkoff** [comment]
Syntax error, IE version 11, i`m using Angular and added npm module print.js

**Comment by crabbly** [comment]
Got it. Can you confirm that you have added the module `print-js` and not `print.js`

**Comment by avoronkoff** [comment]
yes, I added "print-js": "^1.0.50",

**Comment by crabbly** [comment]
I justed the lib with IE11 and can't seem to replicate the issue. What type of data are you trying to print (html/pdf/json/image)?

**Comment by avoronkoff** [comment]
![screenshot_9](https://user-images.githubusercontent.com/20255736/45322510-2440b900-b551-11e8-895e-7d829d7bd106.png)

**Comment by crabbly** [comment]
The error you are getting is because this line is using ES6 syntax, which is not supported by IE.
`isFirefox: () => { return typeof InstallTrigger !== 'undefined' }`

However, the package is being shipped (to npm) transpiled to ES5 syntax. You can confirm that by going into your node_modules folder, print-js, dist, and open the `print.js` file there.

How are you importing the package? Could you post your import code here?

**Comment by avoronkoff** [comment]
yes, sure
import, usage, path
![screenshot_10](https://user-images.githubusercontent.com/20255736/45323158-fd838200-b552-11e8-9bc3-bd74b475677c.png)
![screenshot_11](https://user-images.githubusercontent.com/20255736/45323159-fd838200-b552-11e8-8e24-78f693484101.png)
![screenshot_12](https://user-images.githubusercontent.com/20255736/45323160-fd838200-b552-11e8-8b97-0de939a5d436.png)

**Comment by crabbly** [comment]
Looks like the problem is with your import. I have no idea why you used the `src` path. Please change it to `import 'print-js'`

And then use the `printJS` function to print (the library automatically exposes this global variable):
`printJS(this.printSettings)`

**Comment by avoronkoff** [comment]
changed the way to `import 'print-js'`
but the error has remained..((

**Comment by crabbly** [comment]
I don't know why you are getting this error.

Here is a live example importing the npm package and using the `printJS` function:
https://codesandbox.io/s/x2yrj0kwww

**Comment by avoronkoff** [comment]
i solved this problem like this
(<any> window).printJS(this.printSettings);
thanks!

**Comment by crabbly** [comment]
Just published a new version to npm which has proper support for module import.
The library will still expose a global variable `printJS`, but the recommend usage now should be to import the package at the same file where it will be used:

For ex.:

`import printJS from 'print-js'`

`printJS('path-to.pdf')`

Run `npm update print-js` to get the latest version.
