### ISSUE TITLE
Image printing on the demo site not working.

### ISSUE THREAD

**Issue by maltitco** [crabbly/Print.js#23]
Demo image printing preview shows blank page.
OSX 10.11.6
Safari 10.0.3

**Comment by crabbly** [comment]
Hi @maltitco , I confirmed the issue. Will look into this. Thank you.

**Comment by crabbly** [comment]
The latest version now supports printing images in Safari.
https://github.com/crabbly/Print.js/releases/latest
http://printjs.crabbly.com#image
