### ISSUE TITLE
There is a problem when print multiple pages

### ISSUE THREAD

**Issue by WilliamTsee** [crabbly/Print.js#231]
![image](https://user-images.githubusercontent.com/42863273/45794445-57114c80-bcc9-11e8-8200-d65c7234b470.png)
![image](https://user-images.githubusercontent.com/42863273/45794465-698b8600-bcc9-11e8-968f-31dde6501296.png)
when it wants to separate the form to multiple pages,the style in page top will be chaos.
How i fix it?

**Comment by crabbly** [comment]
Hi @WilliamTsee , 

The library does not manage page breaks. You should do this yourself with either a CSS (ex. [`page-break`](https://css-tricks.com/almanac/properties/p/page-break/) properties) or table headers ([`<thead>`](http://www.terminally-incoherent.com/blog/2009/10/12/repeating-html-table-headers-on-each-printed-page/))
