### ISSUE TITLE
Importing library

### ISSUE THREAD

**Issue by balinskia** [crabbly/Print.js#233]
To use this library with Angular 6 I have to do:
```
import print from 'print-js/src';
print('path-to.pdf');
```
Why not just:
```
import print from 'print-js';
print('path-to.pdf');
```
https://github.com/crabbly/Print.js/issues/48

**Comment by crabbly** [comment]
You shouldn't import from `print-js/src`. 
The library exposes a global variable `printJS` which you can use.
You can import and use it like this:
`import 'print-js'`
`printJS('path-to.pdf')`
or 
`window.printJS('path-to.pdf')`

However, @gabrielmdeal fixed the issue with the import here #230
It will be available in npm soon.

**Comment by balinskia** [comment]
Thanks for the fix!

**Comment by crabbly** [comment]
Just published a new version to npm which has proper support for module import.
The library will still expose a global variable `printJS`, but the recommend usage now should be to import the package at the same file where it will be used:

For ex.:

`import printJS from 'print-js'`

`printJS('path-to.pdf')`

Run `npm update print-js` to get the latest version.
