### ISSUE TITLE
ignoreElements are not working when we set scanstyles to false

### ISSUE THREAD

**Issue by KeerthanaNP** [crabbly/Print.js#239]
ignoreElements are not working when we set scanstyles to false. Is there any particular problem with this?

**Comment by crabbly** [comment]
Hi @KeerthanaNP ,

Thank you for reporting this issue. 
What version of the library are you using?

**Comment by KeerthanaNP** [comment]
Hi, 
I am using v1.0.52 version.

**Comment by twitcher07** [comment]
I'm experiencing this same issue. I'm using version 1.0.50.

**Comment by crabbly** [comment]
I still haven't had to the time to test this. It would be helpful is someone could create a fiddle replicating the issue.

@KeerthanaNP The library accepts an array with multiple ids to be ignored. However, you can always expand this by using a CSS print media query. Hiding and showing any elements you may want. The query can be passed directly into the `style` parameter, or written in your stylesheet file, which then needs to be passed using the `css` parameter. In fact, until we find and fix this issue, this may be a solution you could implement right away.

**Comment by crabbly** [comment]
FYI: https://codesandbox.io

**Comment by twitcher07** [comment]
Here's jsfiddle of basically what i've been trying to do. https://jsfiddle.net/wukct8s6/

**Comment by crabbly** [comment]
Thank you, Tyrel.

**Comment by twitcher07** [comment]
Understood.

For now i'm just using the CSS in order to hide elements with `display: none;`. So that's a work around for now.

**Comment by crabbly** [comment]
Hey guys, 
The library has now a custom html processing method which fixed the issue with ignoring element when scanStyles is set to false. 
Please run `npm update print-js` to get its latest version.

Feel free to reopen this if any issues.
Thank you!
