### ISSUE TITLE
Page break support for type html

### ISSUE THREAD

**Issue by EricLease** [crabbly/Print.js#24]
I have implemented basic page-break support for html printing in a branch ([break-support](https://github.com/EricLease/Print.js/tree/break-support)) of my fork.  The need arises from trying to control page-breaks when printing large sections of html.

I have tested this on Chrome, FF, and IE.  Support for `page-break-*` and `break-*` is not uniform across all browsers, and even more so when it comes to the supported values for `page-break-*`.  In my case I have strict control over use of `page-break-*/break-*` (I'm only using `always` and `avoid`), and I could see how a more robust implementation of this feature could become quite cumbersome.  So this may not be a road you want to travel down, but just wanted to let you know it's there if you'd like to take a look.  Let me know if you'd like a pull request.

For cross-browser support of page breaks, for example, I would apply a class like the following:

```
.page-break {
    page-break-after: always;
    page-break-inside: avoid;
    page-break-before: avoid;
    break-after: always;
    break-inside: avoid;
    break-before: avoid;
}
```

**Comment by crabbly** [comment]
@EricLease  Cool. I'll take a look at it as soon as I have a chance.

**Comment by crabbly** [comment]
Hey @EricLease , I had never take the time to look into this untill now. You branch looks great. I do however, want to keep using es6 `let` for variables. 
I know it is been a while, but if you could do a pull request for the page-break support, that would be great. Thank  you.

**Comment by crabbly** [comment]
I added support for page break with commit 163548d
Thank you @EricLease

**Comment by chocomail** [comment]
so i already read this and try to add css page-break as the same as @EricLease 
but, it seems like im doing it wrong,
the html that i write is like this

> <table>**content**</table>
> <div class="page-break"></div>
> <table>**content2**</table>

but when i print it, it doesnt do the page-break.
am i doing it right?

**Comment by crabbly** [comment]
Hey @chocomail , did you create the class `page-break` in your project?

**Comment by chocomail** [comment]
uhm
do you mean create the class `page-break` is create the css containing page-break?
i tried both, (create css page-break and not create), and not one of them is working.
am i already doing it right for the html?
if so, im afraid i must my other component in my project.

**Comment by crabbly** [comment]
Glad you figured it out. 
You can just pass `break` and it should works as well:
https://codepen.io/anon/pen/ZRbMMW

I'm not sure why `targetStyles: ['*']` is not working. It must be a bug. I'll check on that.
Thank you.

**Comment by crabbly** [comment]
I found the issue with `targetStyles: ['*']` not responding. It has been fixed and pushed to npm.

**Comment by thomazette** [comment]
Hey @crabbly , 
Your example on https://codepen.io/anon/pen/ZRbMMW
not working, maybe same update from Chrome?

**Comment by boldfaces** [comment]
@crabbly your posted example on Codepen doesn't seem to work, have also followed other guide posted. Please advise mate? Thanks.
