### ISSUE TITLE
print JSON has a small bugger

### ISSUE THREAD

**Issue by mingBee** [crabbly/Print.js#240]
properties: [
        {field:'shopName',displayName:'店铺名称',columnSize:'40%'},
        'orderNum'
      ],
when print JSON ,if item of properties is an Object as {field:'shopName',displayName:'店铺名称',columnSize:'40%'}, the grid style is not work,but if it's an String as  'orderNum',work well.

**Comment by crabbly** [comment]
Hi @mingBee ,
Could you please replicate the issue with a fiddle? Thank you.

You probably just need to pass the correct field you want to be printed in the grid. If the library tries to print an object, its obvious that the layout will break.

Here is a fiddle showing how to print nested objects data:
https://jsfiddle.net/crabbly/bLq52fyu/

**Comment by crabbly** [comment]
Thank you for explaining. There was a bug when passing properties as objects.

I just pushed a fix for it: https://github.com/crabbly/Print.js/commit/c527122e6ab7f5fe32f8c35b593c416eb7039250

I'll post an update here once its available in npm.

Here is the updated fiddle:
https://jsfiddle.net/crabbly/bLq52fyu/

**Comment by mingBee** [comment]
Greate.
Solving problems is so efficient.
It helped me a great deal.
Thank you.

**Comment by crabbly** [comment]
The new version is now available in npm which has the fix for this. 
Just run `npm update print-js` to get it.

Thank you guys.
