### ISSUE TITLE
Printable attribute ignores server port leading to 404 error

### ISSUE THREAD

**Issue by GiddyNaya** [crabbly/Print.js#241]
Tried setting up on a server running on port 81
**My working domain root** = `localhost:81/`
**attachmentLink**  = `"../files/uploads/2018/10/5/3202439769577745/63132397.pdf"`

Script was called like this `printJS({printable:'" & attachmentLink & "', type:'pdf', showModal:true})`
The domain "localhost" was being accessed instead of "localhost:81"
![screenshot_8](https://user-images.githubusercontent.com/16220887/46667981-1bc8b600-cbc3-11e8-9e54-8dc0fe684216.jpg)

**Comment by crabbly** [comment]
Hi @GiddyNaya , just pass the full url with `attachmentLink`.
