### ISSUE TITLE
Issue with printing in Safari

### ISSUE THREAD

**Issue by sacki5** [crabbly/Print.js#242]
I'm running version 1.0.52. And having problem with printing html in safari. 
I'm getting this error: `typeError: undefined is not an object (evaluating 'value.indexOf')` from print.js:222

I tried setting "targetStyles: ['*']" but then it worked but my styling was wrong.

Here is my code:
``` js
printJS({
    type: 'html',
    printable: 'ExportPostsList',
    targetStyles: [
        'font-family',
        'text-transform',
        'display',
        'justify-content',
         'white-space',
         'color',
     ],
     documentTitle: this.channelName + `-export-${moment().format('D-MM-YYYY')}`
});
```

**Comment by sacki5** [comment]
Tested around a bit with the code and find a fix that works for me locally. Appreciate if you could fix this so it works on my deployment too. 

Changed this code. 

function.js:222

```js
function targetStylesMatch (styles, value) {
  for (let i = 0; i < styles.length; i++) {
    if (value) { // Added if statement to first check if value exists. 
      if (value.indexOf(styles[i]) !== -1) return true;
    } 
  }
  return false
}
```

**Comment by crabbly** [comment]
Hi Isac, thank you for reporting this issue.

I just pushed a change to fix it: https://github.com/crabbly/Print.js/commit/f692da7f7e412c2fb0df5efc070b3ac47fc86484

I'll publish a new version to npm soon and post an update here.

**Comment by crabbly** [comment]
The new version is now available in npm which has the fix for this. 
Just run `npm update print-js` to get it.

Thanks again, Isac.
