### ISSUE TITLE
How to add this library to my Laravvel-vue js app. Please guide.

### ISSUE THREAD

**Issue by sk23628** [crabbly/Print.js#243]
As given in the documentation, added this to web page <script src="print.js"></script> <link rel="stylesheet" href="print.css"> and 'import print from 'print-js'' to app.js

Error - Uncaught ReferenceError: Print is not defined

**Comment by crabbly** [comment]
Hi Shubham,

Please do some research on how to import and use npm packages.

In the meantime, just use the CDN instead:

`<script src="https://printjs-4de6.kxcdn.com/print.min.js"></script>`

The `printJS` function should then be available in your app.js. Good luck!

**Comment by sk23628** [comment]
Thanks.
But, this did not work.
why the library is not getting added in vendor like other libraries?
Documentation needs to be more detailed.

**Comment by crabbly** [comment]
The documentation can be more improved, indeed. However, I'm pretty sure that's not the problem here.

Did you run `npm install print-js` ?

Once you have done that, here is how you import and use the lib:
https://codesandbox.io/s/x2yrj0kwww

**Comment by sk23628** [comment]
Thanks.
Will try that.
