### ISSUE TITLE
Interface Configuration are missing properties

### ISSUE THREAD

**Issue by DouglasOGarrido** [crabbly/Print.js#244]
Hi,

Some properties are missing from interface Configuration on file "index.d.ts". 

Example of some:
`onPdfOpen`
`onPrintDialogClose`
`onError`
etc.

I'm using printJS in an Angular 6 Project and calling the method thus:
`printJS({ 
  printable: URL.createObjectURL(blobObj), 
  type: 'pdf', 
  showModal: false
});`

When I try to add some of those properties, I received an error that property doesn't exist on the `interface Configuration`. I'm doing this correctly? Or there is another way?

Tks!

**Comment by crabbly** [comment]
Hi Douglas, thanks for reporting this. 

Some of these properties were just added to the library and they were not yet added to the interface. I'll add them soon. A PR is also welcome. :)

**Comment by DouglasOGarrido** [comment]
Hi @crabbly. Tks for the update. And sorry I can't send a PR right now.

**Comment by crabbly** [comment]
Finally pushed a new version. It includes the interface update. 
Just run `npm update print-js` to get it.

Thank you for your help, Douglas.
