### ISSUE TITLE
Downloads PDF file instead of print preview

### ISSUE THREAD

**Issue by sadevio** [crabbly/Print.js#247]
I am using the last version .25 and if I call the printJS() function, the pdf file will be downloaded and not shown in the print preview ?

Using latest Chrome.

Does it check specific response headers ?! What are the requirements of the respone ?!

**Comment by ajay-bal** [comment]
Facing similar issue. If filename is sent from the sever, it downloads the file.
Otherwise print preview is opened with some some string and not the pdf file contents.
Am I missing something?

**Comment by sadevio** [comment]
@crabbly I do use the latest version. What is a valid URL for you ? The URL must be valid in my opinion, because the pdf will be downloaded.

Does it has to look like 

https://mydomain.com/something/myfile.pdf

Could it be 

https://mydomain.com/something/myfile

**Comment by crabbly** [comment]
Sorry. What I meant by valid is to check if the response headers are not telling the browser to download the file. 
The library does not force the download of the PDF document.

**Comment by crabbly** [comment]
When you open the document directly, can you view it in the browser or does it asks you to download the file?

Also, take a look at this #219

**Comment by sadevio** [comment]
Ok we do set actually 

response.header("Content-Disposition", "attachment; filename=\""+attachment.getFileName()+ "\"");  

Let me check if I take it out, if that works then.

**Comment by sadevio** [comment]
This was the issue. If we dont set the header it will work fine.

**Comment by crabbly** [comment]
Cool. I'm glad to hear :)

**Comment by kennylbj** [comment]
Same issue to me
Just pass a downloadable url to print and it will download that file instead of print it.

```js
print({ printable: url, showModal:true, type });
```

And the backend pseudo code is :
```js
 const target = path.join(this.config.baseDir, 'app/public/upload', filename);
 ctx.attachment(filename);
 ctx.set('Content-Type', 'application/octet-stream');
 ctx.body = fs.createReadStream(target);
```

Am i missing something or should I change the response' header?

**Comment by kennylbj** [comment]
Thanks @crabbly 
Now I serve those files as static resources and everything works fine.

**Comment by ajay-bal** [comment]
@crabbly Not passing content-disposition as application/pdf did the trick. So if we pass the content-disposition, download happens else normal print preview of pdf document. I have used onPrintDialogClose also successfully.
Thanks a lot @crabbly!

**Comment by crabbly** [comment]
Thanks for the feedback @ajay-bal 
I think you meant content-disposition as attachment.

I use `Content-Disposition: attachment; filename=my_document_name.pdf` whenever I want to force a document download.

However, we can still pass `Content-Type: application/pdf` to indicate the media type, without forcing the download.

**Comment by kraravind167** [comment]
Hi I also need to Download as ODF insted of taking to Print Preview Page
In which Js i need to change those response header?

Pls explain in detail

**Comment by kraravind167** [comment]
> @crabbly Not passing content-disposition as application/pdf did the trick. So if we pass the content-disposition, download happens else normal print preview of pdf document. I have used onPrintDialogClose also successfully.
> Thanks a lot @crabbly!

Hi ajay
Where do I change those response headers?
