### ISSUE TITLE
Two-page output occurs when printing a4 format pages

### ISSUE THREAD

**Issue by mehfatih** [crabbly/Print.js#248]
I am developing angular application and the application has some printable forms([A4 format](https://github.com/cognitom/paper-css/blob/master/paper.css)). I used print.js to print forms but while print.js is creating html data of 'iframe', it creates 'body' with 8px margin(default) then A4 format forms always have two page (one page blank).

**Comment by crabbly** [comment]
Hi @mehfatih, the library isn't adding an 8px margin to the body, the browser is (default settings).

You could use the `style` parameter to control the iframe body margin. 

Ex.:

```js
printJS({
  printable: 'myElementId',
  type: 'html',
  style: 'body: { margin: 0; }'
})
```

**Comment by mehfatih** [comment]
Thanks @crabbly  for answer and it solved.

**Comment by mehfatih** [comment]
Thanks @crabbly  for answer and it solved.
