### ISSUE TITLE
Add the ability to print HTML contents returned from an expression

### ISSUE THREAD

**Issue by jasonirwin** [crabbly/Print.js#25]
For certain rich text editors, such as CKEdtior, the iframe containing content does not have an ID. Instead, content is accessed using a call like:

`CKEDITOR.instances['my_editor'].getData()`

It would be beneficial to allow an expression to be evaluated and its result printed

`printJS({printable: CKEDITOR.instances['my_editor'].getData(), type:'html'})`

If this is something of value we can discuss design and I can likely find time to work on it and issue a pull request.

**Comment by crabbly** [comment]
Hey @jasonirwin , I like the idea, and would love to see a PR for that. 
Let's try to get on the same page for this.

To keep the code organized, we could create a new "type" for this new behavior. Maybe name it "customHtml", or something like that. It will be a new method in our PrintJS class. 
Ex.: `PrintJS.prototype.customHtml = function () { ... `

To execute the code, we would specify not to get the element by its ID, but instead, evaluate an expression:
Ex.:
`printJS({printable: CKEDITOR.instances['my_editor'].getData(), type:'customHtml'})`

Doing this, we would keep its current behavior / api. Where by default, using `pdf`, `html` or `image` types, printJS will get the element by its ID.

What do you think?

**Comment by jasonirwin** [comment]
Yup. I think you and I had the same concern (whether to use a new or existing type). Should be fairly straightforward. I will follow up with a PR soon.

**Comment by crabbly** [comment]
Awesome!

**Comment by crabbly** [comment]
Hey @jasonirwin , just following up. Let me know if I should keep this open. Thank you.

**Comment by crabbly** [comment]
Unfortunately i don't have enough time to implement this feature. I'll close this issue for now. If necessary, please open it again. Pull requests are welcome. Thank you.
