### ISSUE TITLE
Print image is empty on Chrome

### ISSUE THREAD

**Issue by tonysmz** [crabbly/Print.js#253]
Use the command printJS(url, 'image'); to print png(barcode) file on chrome but the printing preview is empty, Chrome version is 70.0.3538.77 and jQuery version is 1.12.4, the same page work fine on Edge.

**Comment by crabbly** [comment]
Hi @tonysmz, that's strange. I just tested it (image print) with Chrome v70 and it works fine. Both MacOS and Windows 10.

Which OS are you using? Did you check the console for any errors?

Also, can you try printing images from the documentation page and let me know if you still get the same issue?
http://printjs.crabbly.com/#image

Thank you.

**Comment by tonysmz** [comment]
Hi @crabbly ,
My OS version is WIN10 and your sample is running well on my browse, the console didn't show any error, and I can see the Image was downloaded with status 200, maybe there are any conflict with other scripts?

I'm using jQuery && jQuery easyui && bootstrap.

**Comment by MacroYau** [comment]
I am encountering a similar issue on Chrome v70 too (but works fine on Firefox and Safari).

My brief diagnosis after looking at the DevTools network requests: Chrome sends a request to the image URL as soon as `printJS(url, 'image')` is called and shows the print preview dialog, but there is no response until that dialog is closed.

**Comment by crabbly** [comment]
Sorry for the delay guys. This is strange, I can't replicate the issue. The library preloads images to prevent the exactly issue you are describing. The print job shouldn't fire until the image is available in the browser cache. 

If you print the image examples from the documentation page, do you get the same problem?
http://printjs.crabbly.com/#image

**Comment by crabbly** [comment]
Could you guys give me feedback on this please?
Are you getting the same issue when printing the documentation examples?
http://printjs.crabbly.com/#image
Thx

**Comment by andreacris** [comment]
same problem.
I tired from e documentation page and it works fine


> 
> 
> Could you guys give me feedback on this please?
> Are you getting the same issue when printing the documentation examples?
> http://printjs.crabbly.com/#image
> Thx

**Comment by crabbly** [comment]
Unfortunately I can't replicate this issue. Seems like the problem could be related to the server response. I recommend playing with that.

I'll close this since it probably isn't an issue direct related to the library. If you can create a fiddle replicating the problem, please reopen this issue.

Thank you.
