### ISSUE TITLE
Cannot print in Safari yet again?

### ISSUE THREAD

**Issue by cbsteh** [crabbly/Print.js#254]
I am testing my website via LambdaTest, a cross-browser testing platform, and noticed I am unable to print in all Safari versions (v8 onwards).  The error in the console is this:

`TypeError: undefined is not an object (evaluating 't.indexOf')`

This error occurs at file `print.min.js:1:2981`.

I know you recently rectified a similar issue (#238), but am I getting a new problem? Your `print.js` works fine in all other browsers I have tested so far.

**Comment by cbsteh** [comment]
The culprit was the code in `print.min.js`:
```
-1 !== t.indexOf(e[n])
```
So, just modifly slightly to

```
typeof t === 'object' && -1 !== t.indexOf(e[n])
```

This solved the print problem in Safari. Not sure this  code change completely solves the problem, but so far so good in my tests.

**Comment by crabbly** [comment]
Hi Christopher, 

This has been fixed already.
https://github.com/crabbly/Print.js/commit/f692da7f7e412c2fb0df5efc070b3ac47fc86484

What version are you using? Try running ` npm update print-js` .

**Comment by crabbly** [comment]
Closing this since it has been fixed. Try using the latest version. If you are still having issues, please reopen this. Thx.
