### ISSUE TITLE
Chrome detection not working

### ISSUE THREAD

**Issue by tvdeyen** [crabbly/Print.js#256]
The code for checking for Google Chrome is broken for recent Chrome versions (Version 71.0.3578.53 in my case). Because of that the `onPrintDialogClose` callback is not working properly.

It assumes that `window.chrome` and `window.chrome.webstore` are defined. While the first one is an `object` the second one is `undefined`. I actually don't know why the second one was necessary in the first place.

I can provide a PR with a fix if this is considered a valid bug that's worth fixing.

**Comment by crabbly** [comment]
Hey Thomas, a PR would be awesome. 
I agree that `window.chrome` should do it.
Thank you.
