### ISSUE TITLE
Print in orientation landscape

### ISSUE THREAD

**Issue by edyrkaj** [crabbly/Print.js#258]
Using these options is not possible to print in orientation landscape.
      printable: 'print-section',
      type: 'html',
      targetStyles: ['*']
even that placed css attributes for page like:
@page {
 size: A4 landscape;
}
.print-section {
 width: 900px;
}

**Comment by kenanyildiz** [comment]
@edyrkaj I have same issues, there is no way to do that. @crabbly ?

**Comment by kenanyildiz** [comment]
Hi @edyrkaj thanks for info. How do you do that? Because when i try to do that by using old way **browser block pop-up** How to handle that?

**Comment by crabbly** [comment]
Hey guys, you have to pass your stylesheets to the `printJS` function, using the `css` property. Otherwise, you can just pass the page orientation directly using the `style` property.

```js
printJS({
  printable: 'print-element',
  type: 'html',
  style: '@page { size: Letter landscape; }'
})
```

Here is a working fiddle:

https://jsfiddle.net/crabbly/Lvktrb5n/

**Comment by kenanyildiz** [comment]
I already pass style attribute for sizing. Page size auto i gived. Now, i try your solution it does not work. Mobile first..

**Comment by kenanyildiz** [comment]
Okay, you can see on http://www.istifaet.org fill the form and print automatically will trigger. (Mobile)

**Comment by crabbly** [comment]
As you see, the library is passing the page orientation to your print job (confirmed when printing from a desktop). Therefore, not a library issue. 

However, I confirmed that using the @page css query isn't being respected on mobile. Wrap it inside a @print query and give it a try.

Ex.: 
```css
@media print {
    @page {
        size: landscape
    }
}
```

If that doesn't work, search the web for help as this seem related to CSS and not JS. If you can, post any updates here to help anybody else with the same issue. Thank you.

**Comment by xydiva** [comment]
I got the same doubt with the print content width. It's not adaptive when I change the page orientation. Then I found the maxWidth defaults to 800 in the [documentation](http://printjs.crabbly.com/).
Just set it to `auto` and try it.
```javascript
printJS({
    printable: 'print',
    type: 'html',
    maxWidth: 'auto'
})
```

**Comment by crabbly** [comment]
The default value for `maxWidth` was supposed to make print jobs more "printer friendly" out of the box. However, I think we should just remove that. We can use the `style` property or `css` to pass in any desired style. Including "printer friendly" settings.
