### ISSUE TITLE
Mobile Chrome Print on the same page but not the link

### ISSUE THREAD

**Issue by midmike** [crabbly/Print.js#26]
When I using the code :
`printJS({printable:'http:\\example.edu\print',type:'pdf', showModal:true'});`

printable link to and other php page to print. When it is on Chrome PC everything is working fine but when on mobile, page print on the current page but the not page that we have link on printable.

Thanks.

**Comment by crabbly** [comment]
Hey @midmike , I confirmed the issue with Chrome for mobile. It won't print. However, when using Safari (for mobile), it works just fine. I don't know why Chrome mobile fails.

**Comment by crabbly** [comment]
I'll close this issue and keep #33  as they are both related to browser support. Please update #33 with any browser test results you may have. Thank you.
