### ISSUE TITLE
Can not print canvas in html

### ISSUE THREAD

**Issue by bahmansh** [crabbly/Print.js#261]
I have a document that contains some charts (chartjs).
When I want print document canvas will print empty.

![ashampoo_snap_ 19 1397_11h56m48s_004_](https://user-images.githubusercontent.com/19801131/49719655-09c2cc80-fc73-11e8-9513-6a93fc1d4510.png)

![ashampoo_snap_ 19 1397_11h57m47s_005_](https://user-images.githubusercontent.com/19801131/49719659-0deeea00-fc73-11e8-8b9b-0b767b36edf5.png)

**Comment by crabbly** [comment]
Hi @bahmansh, thanks for reporting this. We already have an open issue for this: #181. So far there isn't a fix yet.

I'm closing this to eliminate duplication. 

Please follow the open issue to receive any updates on it.
Thanks again.

**Comment by crabbly** [comment]
The latest version has now support for html print with canvas elements. It should print canvas content as expected.

Run `npm update print-js` to get it.

Please let me know if any issues.
Thank you.
