### ISSUE TITLE
print not respond and Google Chrome will shut down.

### ISSUE THREAD

**Issue by lxk0301** [crabbly/Print.js#262]
### When I print in Google Chrome, the print does not respond and Google Chrome will shut down. and it also happens in Firefox
![image](https://user-images.githubusercontent.com/21308593/49845280-01000100-fe01-11e8-8a04-bc9c93fab8d3.png)

Google Chrome version is 71.0.3578.80
![image](https://user-images.githubusercontent.com/21308593/49845344-3efd2500-fe01-11e8-90cc-53cf74a3d5aa.png)

**Comment by crabbly** [comment]
Hi @lxk0301, what OS and version? Thx

**Comment by lxk0301** [comment]
> Hi @lxk0301, what OS and version? Thx

I'm sorry to reply you so late. My computer OS is windows 10, 1803
![image](https://user-images.githubusercontent.com/21308593/50127275-765d4d00-02ab-11e9-9714-32239a2bfa77.png)

**Comment by crabbly** [comment]
@lxk0301 I agree with  Arash here, this doesn't look like a bug wit the library. I was unable to replicate it. Tested in Windows 10 and Chrome. 

Please read @gharibi comments above. Could indeed be a print driver or network issue. 

Closing this for now. Feel free to reopen if you disagree. Thx.
