### ISSUE TITLE
Unable to download pdf in mobile.

### ISSUE THREAD

**Issue by barik14706** [crabbly/Print.js#265]
I am trying to implement printjs.js in my website, which download pdf in browser in desktop as well as mobile site.
Desktop is working fine but it's not open pdf in mobile, hence  giving information message:
 "print.js?v1.0.54:1 Resource interpreted as Document but transferred with MIME type application/pdf: " 

This appear in printjs official site as well : http://printjs.crabbly.com

**Comment by crabbly** [comment]
Hi @barik14706, you should be getting the same message on desktop as well. Its a warning.

About the mobile issue, please post your mobile OS and browser. Thank you.
