### ISSUE TITLE
Cross browser printing (HTML => Canvas => image) or (Canvas => image)

### ISSUE THREAD

**Issue by sezmars** [crabbly/Print.js#267]
Hey, Guys 
@crabbly, @bahmansh, @zhuyinjing, @KingRial, @ice6, @jaycbrf4, 
I came up with an easy **cross browser** html print bypass with styles.
You need to use [**Print.js**](https://github.com/crabbly/Print.js) with [**html2canvas**](https://github.com/niklasvh/html2canvas)
This approach is also suitable for **printing canvas**.

```
public printTable() {
    html2canvas(document.querySelector('#table')).then(async (canvas: HTMLCanvasElement) => {
      const toImg = canvas.toDataURL();
      printJS({printable: `${toImg}`, type: 'image', imageStyle: 'width:100%'});
    });
  }
```

```
public printCanvas() {
    html2canvas(document.querySelector('#canvas')).then(async (canvas: HTMLCanvasElement) => {
      const toImg = canvas.toDataURL();
      printJS({printable: `${toImg}`, type: 'image', imageStyle: 'width:30%'});
    });
  }
```

Reproduction [**stackblitz**](https://stackblitz.com/edit/angular-mtdc7c)

**Comment by crabbly** [comment]
Hey @sezmars, thank you for posting this here. :)

Its an interesting work around that fixes issues when trying to print elements like canvas, select or checkboxes.

**Comment by crabbly** [comment]
Closing this in favor of #181

**Comment by crabbly** [comment]
The latest version has now support for html print with canvas elements. It should print canvas content as expected.

Run `npm update print-js` to get it.

Please let me know if any issues. Thank you.
