### ISSUE TITLE
sharp character

### ISSUE THREAD

**Issue by onrozcn** [crabbly/Print.js#27]
my pdf file name: my pdf # 11-1111.pdf
when I using the code 
`printJS('uploads/pdf/my pdf # 11-1111.pdf');`

didnt work, can you check?

Thanks.

**Comment by crabbly** [comment]
Hi @onrozcn , `printJS` accepts an url as the default printable (pdf) parameter. Urls can't have spaces in it, and thats where you have a problem. If you want to keep using spaces in your pdf filenames, you will have to encode the url first (https://tools.ietf.org/html/rfc3986#section-2.1).
I would, instead, just name my files without spaces, for example, change your pdf filename to `my-pdf#11-1111.pdf`, and to print it:
`printJS('uploads/pdf/my-pdf#11-1111.pdf')`
