### ISSUE TITLE
Can't set maxWidth with image.

### ISSUE THREAD

**Issue by Kishan033** [crabbly/Print.js#271]
I set Print.js with base64 image.
It works fine but not working with maxWidth property.
I wrote as below.

`printJS({printable: url, type: 'image', maxWidth: 300, imageStyle: 'width:200px;'})`

Please suggest any idea.
Thanks in advance.

**Comment by crabbly** [comment]
Hi @Kishan033, 

Try using the `imageStyle: 'width:200px !important;'`

Also, this property has been deprecated. I recommend using `css` or `style` instead. Something like this:

```js
printJS({
	printable: url,
	type: 'image',
	style: 'img { width:200px !important; }'
})
```

or

```js
printJS({
	printable: url,
	type: 'image',
	style: '.my-image-class { width:200px !important; }'
})
```

**Comment by crabbly** [comment]
Closing this since I don't think there is an issue with the library setting the image style. Please reopen if necessary. Thank you.
