### ISSUE TITLE
Print multiple pdf

### ISSUE THREAD

**Issue by frolli** [crabbly/Print.js#273]
Hi, how can i print multiple pdf?
For example:
printJS({
 printable: 
  ['https://pdf1.pdf', 'https://pdf2.pdf']
  type: 'pdf',
  showModal:true
})

Thank you.

**Comment by centexdabull** [comment]
This would be a great feature.

**Comment by SaschaAusUlm** [comment]
Yep, would be nice indeed.

**Comment by alex-dokienko** [comment]
voting for this feature, would be awesome to have such option

**Comment by kylejrp** [comment]
I've got a bit of a workaround to make multiple PDF printing work in Chrome:
```
printJS({
    printable: 'First.pdf',
    type: 'pdf',
    onPrintDialogClose: function() {
        printJS('Second.pdf');
    }
})
```

Doesn't seem to work in IE11/Firefox though. Would be cool to see workarounds for IE11/Chrome or official support.

**Comment by crabbly** [comment]
Hey guys, the library doesn't merge multiple pdf files into one, therefore, we would need to either merge the files before dispatching the print job, or dispatch a job per file.

It would indeed be nice to add this feature, but its currently outside the library scope. Thank you.

Ref.: #462, #458, #215, #403
