### ISSUE TITLE
targetStyles:['*'] dose't work as expected in vue

### ISSUE THREAD

**Issue by jordandc1** [crabbly/Print.js#274]
The web shows the print area as follow:
![image](https://user-images.githubusercontent.com/19319558/51373695-ba0dd580-1b3b-11e9-80e4-03af5bc1cae8.png)
However, in the print preview
![image](https://user-images.githubusercontent.com/19319558/51373738-d3168680-1b3b-11e9-9d9e-52ea089102c2.png)

HTML
`<div id='ticket' class="ticket_container">
            <div class="ticket_img">
              <img src="../../../../static/logo/receipt_logo.png" alt="gpaplus">
            </div>
            <div class="ticket_box">
              <div class="ticket_date">
                <h1>JAN 15</h1>
              </div>
              <div class="ticket_day">
                <h1>Day</h1>
                <h1 class="ticket_day_number">15</h1>
              </div>
              <div class="ticket_year">
                <h1>2019</h1>
              </div>
            </div>
            <div class="ticket_hello">
              <h1>很高兴与你再次见面</h1>
              <h1>GOOD TO SEE YOU AGAIN</h1>
            </div>
            <div class="ticket_info">
              <div class="ticket_info_detail">
                <h1>手机号：6474726666</h1>
                <h1>姓名：赵二狗</h1>
                <h1>课程：ADMS2500</h1>
                <h1>课节：TERMTEST1SESSION2</h1>
              </div>
            </div>
            <div class="ticket_require">
              <h1>出示此凭条领取课程材料</h1>
              <h1 class="ticket_require_last">视 频 课</h1>
            </div>
          </div>`

METHOD
`    print() {
        printJS({
          printable:'ticket',
          type:'html',
          targetStyles:['*']
        });
    }`

STYLE
`<style scoped>
.ticket_container
{
  height:945px;
  width:591px;
  border-style:solid;
}
.ticket_img
{
  padding: 30px;
}
.ticket_box
{
  border-style: solid;
  border-width: 10px;
  display:flex;
  height:200px;
  width:500px;
  margin: auto;
}
.ticket_date
{
  transform-origin: left;
  transform: rotate(90deg) translateX(-40px) translateY(40px);
}
.ticket_day
{
  width:300px;
}
.ticket_day_number
{
  font-size:100px;
  font-weight: bold;
}
.ticket_year
{
  transform-origin: right;
  transform:rotate(270deg) translateX(30px) translateY(70px);
}
.ticket_hello
{
  padding-top: 30px;
  padding-bottom: 30px;
}
.ticket_info
{
  padding-top: 30px;
  padding-bottom: 60px;
}
.ticket_require_last
{
  margin: auto;
  background-color: black;
  color: white;
  width: 200px;
  word-spacing: 20px;
}
</style>
`

**Comment by crabbly** [comment]
Hey @jordandc1, have you tried the suggestion above? Thx
