### ISSUE TITLE
JSON print column aligning

### ISSUE THREAD

**Issue by pingmouren** [crabbly/Print.js#275]
I want set the first column text-align: left,and the other column text-align: right.
What should i do.

**Comment by crabbly** [comment]
Hi @pingmouren,

You can target the column through css.
https://css-tricks.com/how-nth-child-works/

You can pass it directly using the `style` property.
http://printjs.crabbly.com/#configuration

**Comment by nesic998** [comment]
I tried adding different background color for odd/even rows but it's not working. All other css are working. Any help?

This is my code:

             style: `
              tr:nth-child(even) {
                background-color: #f2f2f2; /* Light grey background for even rows */
              }
              tr:nth-child(odd) {
                background-color: #ffffff; /* White background for odd rows */
              }
            `,

**Comment by nesic998** [comment]
I found solution. I found on some other issue

Just added: -webkit-print-color-adjust: exact;
