### ISSUE TITLE
Change the date format on page in case JSON printing 

### ISSUE THREAD

**Issue by pomazandre** [crabbly/Print.js#277]
Hi, change the date format on page ?
Can I use CSS Page Module and CSS Media query 
@media print ? 
Thank you.

**Comment by crabbly** [comment]
Hey @pomazandre, I'm guessing you want to format one of the fields in your JSON data, a date field, is that correct?

If yes, you could just manipulate this data before sending it to the `printJS` function / print.

**Comment by pomazandre** [comment]
I want to change the date format in the header, in left corner.

**Comment by crabbly** [comment]
Hey @pomazandre,

You are talking about the print header set by the browser. That can't be controlled with javascript alone. For security reasons.
Please refer to #79
