### ISSUE TITLE
Minified files not included in latest release

### ISSUE THREAD

**Issue by algodave** [crabbly/Print.js#278]
I have the following in my `package.json`:

```
    "print-js": "1.0",
```

which is resolved like this in my `yarn.lock`:

```
print-js@1.0:
  version "1.0.54"
  resolved "https://registry.yarnpkg.com/print-js/-/print-js-1.0.54.tgz#f15df027951e9a9165b6d39420d362ba7f0fc130"
  integrity sha512-tZkwoHJCTS6jqj0UuxhUY9xF8v0rOuAgIZRlfZBOg9D1R4saxznRANkVlAsLW+D4GOOsLq5Zd/OgVk58IfESXA==
```

If you look into the `tgz` file linked above, you'll notice that it doesn't include minified versions of both JS and CSS files

**Comment by crabbly** [comment]
Hi @algodave, 

The minified files are not included on purpose. It's better for debugging. Each developer can bundle and minify the lib as needed.

For anybody that is not using npm or does not have an bundler setup with minifying options, I have been adding the minified files to each release, as a downloadable option.
https://github.com/crabbly/Print.js/releases/latest

Is there a good reason why we should include minified files with the shipped package? 
Thank you.

**Comment by algodave** [comment]
@crabbly Thanks for answering! I only asked because on some earlier version, minified files were included in the dist folder.

**Comment by crabbly** [comment]
Cool! Thank you for the feedback.
