### ISSUE TITLE
Is there any bower package soon.

### ISSUE THREAD

**Issue by JinnaBalu** [crabbly/Print.js#28]
Expecting for bower package, as this is a front package. we can have this at front end.

**Comment by crabbly** [comment]
@JinnaBalu You can install it using npm (`npm install print.js`). I wasn't planning on making this available through bower, but I'll publish it. I'll post an update here whenever this is done. Thx.

**Comment by crabbly** [comment]
Hey @JinnaBalu , you can now install the library using bower:

`bower install print.js`

If you like the library, please star the project. Thank you.
