### ISSUE TITLE
How to use with StencilJs?

### ISSUE THREAD

**Issue by victorcarvalhosp** [crabbly/Print.js#280]
Can someone please provide an example of how I can use printJs with StencilJs? I tried in many ways, but I simply don't know if this is possible...

Thanks!

**Comment by crabbly** [comment]
Hi @victorcarvalhosp, the library should work the same way. Please create a sandbox showing the issue you are having and what you have tried.
https://codesandbox.io

**Comment by victorcarvalhosp** [comment]
After disabled shadowDOM it worked! I have no clue how to make it work with shadowDom, but it's ok for now.

To make it work, on my .tsx file I first imported printJS like this:

`import printJS from 'print-js'
`
create a method like this:
`
  printElem(){
    printJS({printable: 'section-to-print', type: 'html', honorColor: true, targetStyles: [
        '*'
      ]});
  }`

and my render() function like this:

 ```
render() {
    return (
        <div id="printjs-form">
          <button onClick={() => this.printElem()}>Imprimir PrintJS</button>
          <div id="section-to-print">
                <p> Print only this
          </div>
      </div>
```

**Comment by crabbly** [comment]
Nice! I'm glad you got it working :)
