### ISSUE TITLE
Can I pass Request Headers to obtain pdf by URL?

### ISSUE THREAD

**Issue by lyanetgp** [crabbly/Print.js#281]
Hello, I need to pass request header (authentication) to open a pdf file by url, exist a way to do this? Thank you

**Comment by crabbly** [comment]
Hi @lyanetgp, it's better to do these things outside the library. What I mean is that we could retrieve the file first, save it in local memory, and then pass it to the library.
Take a look at this: https://github.com/crabbly/Print.js/issues/160

**Comment by lyanetgp** [comment]
That is what I ended up doing. Works like a charm. Thank you very much for
your answer, and advice. I appreciate it.

**Comment by crabbly** [comment]
You are welcome! :)

Rod


On Feb 20, 2019, at 10:55 PM, lyanetgp <notifications@github.com<mailto:notifications@github.com>> wrote:

That is what I ended up doing. Works like a charm. Thank you very much for
your answer, and advice. I appreciate it.
