### ISSUE TITLE
Invalid HTML element id when using Shadow DOM

### ISSUE THREAD

**Issue by victorcarvalhosp** [crabbly/Print.js#282]
Hello! I'm using printJS on a stenciljs project, and when I activate the shadow DOM property, the lib can't find the id anymore...

Is there a way to workaround this? Or maybe a way to pass all Element that I want to print instead of just the id?

So I can do something like this:

```
printJS({
      printable: this.el.shadowRoot.querySelector('#section-to-print').innerHtml, type: 'html', honorColor: true, targetStyles: [
        '*'
      ]
    });
```

?

Thanks!

**Comment by crabbly** [comment]
Hey Victor, 

I'm not familiar with stenciljs. The print-js library uses `document.getElementById` to grab the target printable element. I would assume there is a work around with stenciljs to target elements even when the shadow DOM property is enabled. 

What we could do in print-js however, is to add an option to accept raw HTML. It would require you to pass the stylesheets url through the `css` property or the whole styling through the `style` property.

I'm not sure how often this option would be used. It may be very specific to some scenarios only. I'll take a look at implementing this. As long it doesn't add a lot of new code to the lib, it may be a nice option to have.

**Comment by crabbly** [comment]
I just pushed a commit with a new option to print raw html.
https://github.com/crabbly/Print.js/commit/f74c24dfcad885f28f49e29e5ad060983649111f

It will be available on the next release.

**Comment by crabbly** [comment]
Hey @victorcarvalhosp,
The newest version has a new `raw-html` option.
Run `npm update print-js` to get it.
Hope it will be useful.

**Comment by JCs3lma** [comment]
I have issue like this. 

```
print.js:294 Invalid HTML element id: <table id="tableToPrint" class="w-full overflow-x-scroll divide-y divide-gray-200 border-4"><thead class="bg-violet-400"><tr><th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-slate-50 uppercase">
                    Order #
```

I am using nuxt js
