### ISSUE TITLE
Website documentation

### ISSUE THREAD

**Issue by JandersonConstantino** [crabbly/Print.js#283]
Hi, I suggest updating the documentation website about JSON print.
Today, the documentation doesn't have information about print with custom table header.

Example:
```javascript
someJSONdata = [
  { name: 'John Doe', email: 'john@doe.com', phone: '111-111-1111' },
  { name: 'Barry Allen', email: 'barry@flash.com', phone: '222-222-2222' },
  { name: 'Cool Dude', email: 'cool@dude.com', phone: '333-333-3333' }
]

printJS({
  printable: someJSONdata,
  properties: [
    { field: 'name', displayName: 'Full Name' },
    { field: 'email', displayName: 'E-mail' },
    { field: 'phone', displayName: 'Phone' }
  ],
  type: 'json'
})
```

**Comment by crabbly** [comment]
Hi Janderson,

Thank you for pointing this out. The documentation does need a few updates for sure. I'll try to get this done soon.

Also, the documentation is open source and hosted here at this same repository, under the gh-pages branch. Just in case you want to help with that :)
Thanks again.
