### ISSUE TITLE
How to add this using NUXT ?

### ISSUE THREAD

**Issue by jaasaria** [crabbly/Print.js#286]
Anyone already integrate this to nuxtjs? 
Locally and CDN ?

**Comment by crabbly** [comment]
Hi @jaasaria, I haven't used Nuxt yet, therefore, I don't have any input with using the lib with it. 
Shouldn't you be able to import it just like any other package though?

**Comment by jaasaria** [comment]
Hi @crabbly , thanks for the quick reply.
The package is working but after refreshing the page. It gives me this error.

> Window is not defined

**Comment by crabbly** [comment]
Interesting. The library does a check to see if `window` is available:
https://github.com/crabbly/Print.js/blob/master/src/index.js#L6

Are you sure this error is coming from `print-js`?

If yes, could you please setup a codesandbox, using nuxt and importing printjs to replicate the issue?
I could then jump on it and try to figure this out with you. Thank you.

https://codesandbox.io/

**Comment by jaasaria** [comment]
@crabbly check this 
https://codesandbox.io/s/3y52v3ywpp?fontsize=14

go to about page

**Comment by crabbly** [comment]
Thank you, @jaasaria 

I'm not getting the error here. It is working fine for me. :/
So far tested in Chrome and Safari. 
MacOS Mojave.

What are you using it on?

**Comment by jaasaria** [comment]
Did you hit the refresh? 
![image](https://user-images.githubusercontent.com/5240819/53997796-91d44780-4178-11e9-98c5-e3cdb2548019.png)

Im using Windows and Chrome

**Comment by crabbly** [comment]
Yea. It didn't happen before, but now it's happening every time. It doesn't make much sense.
Anyways, I don't know why it is happening, but I can play with it now. Thx.

Initially, it looks like a conflict when webpack is compiling everything together.

**Comment by jaasaria** [comment]
Alright, please let me know if anything i can help from my side. 
Thanks for the quick support.

**Comment by sppera** [comment]
Possible solution: https://codesandbox.io/s/1q52zvkyy3

User dynamic import when page mounts.

Or try to inject print as a global :
https://nuxtjs.org/guide/plugins#inject-in-root-amp-context
https://nuxtjs.org/guide/plugins#client-side-only

**Comment by crabbly** [comment]
Awesome!
Thank you, @sppera 

Hey @jaasaria, could you take a look at @sppera's solution?
It fixed the issue for me. I'm not getting that error anymore.

**Comment by jaasaria** [comment]
Yes it works! Thanks @sppera  and @crabbly for the time.

**Comment by N0SYS73M1SS4F3** [comment]
@sppera  where is ur solution now, bro??
