### ISSUE TITLE
SCRIPT1002: 语法错误 in IE

### ISSUE THREAD

**Issue by mingmLiang** [crabbly/Print.js#288]
![image](https://user-images.githubusercontent.com/22100065/54260989-82546480-45a5-11e9-86d9-fa4665c6a57f.png)
![image](https://user-images.githubusercontent.com/22100065/54260942-52a55c80-45a5-11e9-9926-b8fa67ec9bbb.png)

**Comment by crabbly** [comment]
Hey @mingmLiang, 
Please create a proper issue by asking a question or describing an issue. 
Thank you.
