### ISSUE TITLE
How do i print Nested JSON data using printjs

### ISSUE THREAD

**Issue by anupampahari** [crabbly/Print.js#29]
anyone tried using nested JSON data??

**Comment by crabbly** [comment]
Hey @anupampahari , the library supports single level JSON data only. Handling nested JSON data could bring more complexity to the `printJS` api, which is not the goal with this library. However, I may consider adding support for it.
Could you please explain your use case / need for this?
Thank you.

**Comment by crabbly** [comment]
@anupampahari I still would like to hear more about the need and required layout for nested JSON data. Any input will be appreciated. Thx.

**Comment by crabbly** [comment]
For now I can't see a reason why to implement this.

**Comment by crabbly** [comment]
The latest release supports nested objects:
https://github.com/crabbly/Print.js/releases/latest

Reference #116
