### ISSUE TITLE
How to make explicit breakdown of pages when printing html?

### ISSUE THREAD

**Issue by grantorin** [crabbly/Print.js#294]
Hi, I need to explicitly set the pagination of my html div. Is this somehow possible?

**Comment by crabbly** [comment]
Yes. Use CSS page breaks. Pass that info through the `style` property. Or even better, setup a print media query in your stylesheet, and pass the stylesheet through the `css` property.

**Comment by grantorin** [comment]
Thank you very much, you helped me a lot, everything turned out well!)

**Comment by crabbly** [comment]
Awesome! :)
