### ISSUE TITLE
Print multiple pages by identify html class

### ISSUE THREAD

**Issue by crossRT** [crabbly/Print.js#3]
Hi there, 
Thank you for creating this awesome library to make printing HTML so easily.
I tried it and printed a div with id only, it works very well.
But it will be really great if you can add another feature that allows us to print multiple pages?
For example, I have a list of results. Each result is a container, and it can shows as a page when printing.

``` html
<!DOCTYPE html>
<html>
<body>
    <div class="results">
        <div class="result">
            <h1>Student Name: student 1</h1>
            <p>Score: 100%</p>
        </div>
        <div class="result">
            <h1>Student Name: student 2</h1>
            <p>Score: 90%</p>
        </div>
        <div class="result">
            <h1>Student Name: student 3</h1>
            <p>Score: 80%</p>
        </div>
        <div class="result">
            <h1>Student Name: student 4</h1>
            <p>Score: 70%</p>
        </div>
    </div>
</body>
</html>
```

So can we use the library like this:

``` javascript
<button type="button" onclick="printJS('.results, 'html')">
    Print Results
 </button>
```

Once again, sincerely appreciate for your contribution to web world.
Please do let me know any updates regarding this ya.

**Comment by crabbly** [comment]
@crossRT The browser takes care of multiple pages when printing a long list or records. However, I believe what you want is to do is to print multiple html elements with the same class. For ex. `.results`. That is an interesting idea. I'll definitely take a look into it.

**Comment by khanh703** [comment]
If you just want to force a page break per each result container, you can do pure css.

@media print {
    .result {page-break-after: always;}
}

**Comment by crabbly** [comment]
@crossRT I just added page break support with the latest release.
https://github.com/crabbly/Print.js/releases/latest
All you have to do now, is to give your main div `<div class="results">` an id, and pass this id to the `printJS` function. Then, as @khanh703 mentioned, add `page-break` to your `result` class, for printing. It should work as you expect. :)

**Comment by crossRT** [comment]
oh thanks @crabbly 
Will give it a try soon!
