### ISSUE TITLE
Print rich text,   but  "color" is lost

### ISSUE THREAD

**Issue by devindo** [crabbly/Print.js#300]
Print rich text, but  "color" is invalid . Before send to iframe, has "color" property.

**Comment by crabbly** [comment]
Try using the `css` and `style` properties to pass your style, and disable the JavaScript processing (`scanStyles: false`).

**Comment by crabbly** [comment]
Hey @devindo, problem fixed?

**Comment by crabbly** [comment]
This should be a style issue and passing the proper style to the lib should work as expected.
Fee free to re-open this if necessary.
