### ISSUE TITLE
Hidden forms cause indentation to disappear when printing HTML forms

### ISSUE THREAD

**Issue by jingnianrecall** [crabbly/Print.js#301]
When I use hidden or display:none, the indentation disappears (no typography). Cancel display:none becomes correct, what is the problem? thanks

**Comment by jingnianrecall** [comment]
I temporarily use the `style="position: absolute;"`to achieve the effect I want ~, hide the form and make the layout normal

**Comment by crabbly** [comment]
Hey @jingnianrecall, 
Try to disable the JavaScript style processing with `scanStyles: false` and pass your styles using the `css` or `style` properties.

**Comment by jingnianrecall** [comment]
@crabbly Ok, thank you, let me try.

**Comment by crabbly** [comment]
Hey @jingnianrecall, problem fixed?

**Comment by crabbly** [comment]
This should be a style issue and passing the proper style to the lib should work as expected. 
Fee free to re-open this if necessary.
