### ISSUE TITLE
Use CSS Selector instead of IDs

### ISSUE THREAD

**Issue by mansouryaacoubi** [crabbly/Print.js#302]
Hello,

I think it might be better to use CSS selectors instead of IDs. Is that a planned feature or is there a reason why you are using IDs?

I can see where this can come in handy:

```js
printJS({
        printable: '#order_information',
        type: 'html',
        header: 'Test Order',
        ignoreElements: ['.no-print']
      });
```

instead of

```js
printJS({
        printable: 'order_information',
        type: 'html',
        header: 'Test Order',
        ignoreElements: ['order-completion-bttn', 'order-info-collapse', 'order-foo-bar', 'order-barry-allen', 'order-batman', 'order-stuff']
      });
```

Thanks

**Comment by crabbly** [comment]
Not a planned featured. I did think about it before, but I'm not sure this would really bring a lot of value.
Grabbing multiple HTML elements just doesn't seem like something useful. The library wouldn't know how to properly position them together. 

Thoughts?

**Comment by crabbly** [comment]
Closing this for now. I'm not sure if many people would be looking for something like this. 
Feel free to reopen. Thx.
