### ISSUE TITLE
Websocket Connection Lost while print modal is open

### ISSUE THREAD

**Issue by mansouryaacoubi** [crabbly/Print.js#303]
Hello,

I am using socket.io and print.js in my project.
socket.io is using websockets to establish connections to a server.
Now what I found out if I just press `Ctrl` + `P` to print out a page, the socket is still working in the background and messages can still be received.
But using print.js the connection to the socket is lost after a few seconds and no further messages can be retrieved.

Using `Ctrl` + `P` => Modal opens; Messages can still be retrieved
Using `printJs` => Modal opens; Messages can not be retrieved and after a few seconds connection is lost

So this cannot be a socket.io issue because it does still work using the default browser Print Dialog.

Browser: **Chrome Version 73.0.3683.103 (Official Build) (64-Bit)**
System: **Windows 10**
Latest Version of `socket.io` and `print.js` using CDN.

I look forward to any answer. 
Thanks in advance.

**Comment by mansouryaacoubi** [comment]
This does work on firefox, but on Chrome it disconnects the socket.
Seems like a Bug. Either in Chrome or in print.js

**Comment by crabbly** [comment]
Hey Mansour, 
First, thank you for reporting this.

It's a weird behavior. All the library is doing, is to create an iframe, prepare some data in it, then print normally. Nothing special. Just saving us from writing some repetitive code. Therefore, I have no idea why it would conflict with web socket connections.

I have used the library in projects using web sockets before without any issues. I didn't use socket.io though.

That said, if you could replicate the problem into a codesandbox or fiddle, I could play with and try to find out the cause of this behavior. Thank you.

**Comment by mansouryaacoubi** [comment]
Hello @crabbly.
I already reported this issue to Google. This seems to be a Chrome Browser Issue.
I already checked out what printjs does and indeed it just creates an iframe that should not be a problem.
The websocket issue does not occurr using Firefox or Edge.

This was my bug report to Google:
__________________________________
Calling the Print Dialog does not have the same result when opening it via a keyboard shortcut or via Javascript.
Pressing Ctrl+P does open the Print Dialog and any websocket in the background is still working.
Using window.print() opens the Print Dialog as well but the websocket connection is being lost and no messages can be retrieved.
Calling window.print() on Firefox does not result in a disconnection of the socket.
Chrome Version 73.0.3683.103 (Official Build) (64-Bit)
socket.io - Latest Version using CDN
print.js - Latest Version using CDN
Tested with Chrome, Firefox, Edge. Problem does only occurr on Chrome.

**Comment by crabbly** [comment]
Got it! Thank you for the update, Mansour.

**Comment by pepongucte266** [comment]
Have any solusion?

**Comment by AlexZalez** [comment]
I have the same problem, and I've already tried edge and firefox and it's still the same.
