### ISSUE TITLE
i18n: The css property `direction: RTL` property is not respected

### ISSUE THREAD

**Issue by Juni4567** [crabbly/Print.js#307]
Hi, I wanted to print a simple html page which is set to RTL but when the PDF is saved it's LTR

**Comment by crabbly** [comment]
Hey @Juni4567 , 

Did you pass your print style to the library through the `style` or `css` property?
Please post some code here showing how you used the lib. Thx.

**Comment by Juni4567** [comment]
Hi @crabbly , Thank you for your quick response. I was doing it wrong:

`style: 'direction: rtl'` assuming that it will be applied as the style property of the element.

**The correct way is as following**
`style: 'body { direction: rtl; color: red; }'`


Note for anyone watching this issue:
The style is not the <div `style`="direction: rtl"> but it's treated as following:
`<style>
.your-element-class{
    direction: rtl;
}
</style>`
can also be found on the documentation:
![image](https://user-images.githubusercontent.com/9845119/57011949-87d14100-6c1d-11e9-92e2-f2a7835dd5c0.png)


@crabbly is it a good idea to call it `embeddedStyle` instead of just `style`?

**Comment by Juni4567** [comment]
I was expecting it to take the style from the stylesheet though because I set the styles of the page as:
`
html,
body {
  direction: rtl;
}
`

**Comment by crabbly** [comment]
Hey @Juni4567, 
Thank you for all the info.

I see the misunderstanding. Changing the property name is not necessary. And not friendly since people are already using. We can definitely improve the documentation and make that more clear.

**Comment by crabbly** [comment]
A new documentation site is on the way. Thank you for the feedback.
