### ISSUE TITLE
Multiple Images Print Out of Order

### ISSUE THREAD

**Issue by RoughneckCoder** [crabbly/Print.js#309]
Hi, thank you so much for this very useful library.

I have an issue when I try to print multiple images (in an array) the order of the array is not respected.  The images print in a different order.  I've tried several sorting methods to sort my array before passing it to printJS, it has some affect on the order but never the actual order of the images based on the array indices.  Here is an example of my code:

                printJS({
                    printable: [
                        String.raw `..\..\assets\pngs\icfm\129.png`,
                        String.raw `..\..\assets\pngs\icfm\130.png`,
                        String.raw `..\..\assets\pngs\icfm\131.png`,
                        String.raw `..\..\assets\pngs\icfm\132.png`

                    ],
                    type: 'image'
                });

Any thoughts on why this might be happening?

**Comment by crabbly** [comment]
Hi @RoughneckCoder, thank you for reporting this.

Its probably because of the logic in `image.js` to pre-load images. The images are probably being added to the print job in the order that they are being loaded. Which isn't necessarily the passed array order. It will probably depend on the size of the image.

We will have to update this logic to use the original array index when building the print job after the images are loaded. 

My initial thoughts are... within the image `onload` event, instead of attaching the loaded image to the printable element, we could add it to an indexed data structure first. Once that is complete, we should then append all images in order. 

https://github.com/crabbly/Print.js/blob/master/src/js/image.js#L61

**Comment by RoughneckCoder** [comment]
@crabbly,
Thank you for getting back to me.  Yes, I definitely think this is due to the different times it takes the images to load.  That is consistent with what I am seeing as the images with the largest pictures are always last regardless of the original order.

Do you think you'll have time to make these changes?  I am going to give it a shot myself but I still have much to learn about dealing with JS promises.  Where would you suggest putting the code to take the indexed data structure and append the images in order?

**Comment by crabbly** [comment]
Hey @RoughneckCoder, I didn't have time to look into this yet. I'll do as soon as I have a chance.

If you want to play with it, this has be be handled in `image.js`, inside `loadImagesAndAppendToPrintableElement`.

**Comment by RoughneckCoder** [comment]
@crabbly,
Thank you so much.  I was actually able to figure out something that worked.  Here is my code:

`    // Load images and append
    loadImagesAndAppendToPrintableElement(printableElement, params).then(() => {
      // Check if we are adding a header
      if (params.header) addHeader(printableElement, params.header, params.headerStyle);

      // Sort images in original order
      var sorted = document.createElement('div');
      $(printableElement).children().sort(function (a, b) {
        return parseInt($(a).find('img')[0].id.replace(/\D/g, '')) - parseInt($(b).find('img')[0].id.replace(/\D/g, ''));
      }).each(function () {
        sorted.append(this);
      });

      // Store html data
      params.htmlData = sorted.outerHTML;


      // Print image
      Print.send(params, printFrame);
    });
`

It could probably be a little cleaner but it's a start.

**Comment by Yxliam** [comment]
> @crabbly,
> Thank you so much. I was actually able to figure out something that worked. Here is my code:
> 
> ```
>     // Load images and append
>     loadImagesAndAppendToPrintableElement(printableElement, params).then(() => {
>       // Check if we are adding a header
>       if (params.header) addHeader(printableElement, params.header, params.headerStyle);
> 
>       // Sort images in original order
>       var sorted = document.createElement('div');
>       $(printableElement).children().sort(function (a, b) {
>         return parseInt($(a).find('img')[0].id.replace(/\D/g, '')) - parseInt($(b).find('img')[0].id.replace(/\D/g, ''));
>       }).each(function () {
>         sorted.append(this);
>       });
> 
>       // Store html data
>       params.htmlData = sorted.outerHTML;
> 
> 
>       // Print image
>       Print.send(params, printFrame);
>     });
> ```
> 
> It could probably be a little cleaner but it's a start.

Because the library uses promise. All, you can change it to this
 ```
 // Load images and append
    loadImagesAndAppendToPrintableElement(printableElement, params).then((imageWrappers) => {
      imageWrappers.forEach(imageWrapper => {
        printableElement.appendChild(imageWrapper);
      });
    ...
```
and then modify the method,end resolve the imageWrapper 

```
function loadImageAndAppendToPrintableElement (printableElement, params, img, index) {
  return new Promise(resolve => {
    img.onload = () => {
      // Create image wrapper
      let imageWrapper = document.createElement('div')
      imageWrapper.setAttribute('style', params.imageStyle)

      img.setAttribute('style', 'width:100%;')
      img.setAttribute('id', 'printableImage' + index)

      // Append image to wrapper element
      imageWrapper.appendChild(img)

      // Append wrapper element to printable element

      // printableElement.appendChild(imageWrapper)

      resolve(imageWrapper)
    }
  })
}
```

**Comment by crabbly** [comment]
Thank you guys. 
One note, the library doesn't use jQuery, we want to keep it lean.

We are now preloading the images inside the iframe, which was added to support raw-html with images. I'm wondering if we can just get rid of the pre-load inside `image.js`. This would fix the sort order and give us a performance boost.

**Comment by crabbly** [comment]
I removed the image `onload` usage from `image.js`. This fixed the issue.
https://github.com/crabbly/Print.js/commit/a975f75b183516d1f66d22febc9fdbfaa9d2d5ac

I also added an example to the manual test `index.html` document.
I'll let you know once this has been published to npm. Thank you.

**Comment by crabbly** [comment]
The new version has been published to npm with the fix for the image order issue.
https://github.com/crabbly/Print.js/releases/latest

Run `npm update print-js` to get it.

Feel free to reopen this if any issues.
Thank you guys!
