### ISSUE TITLE
base64 option is not working

### ISSUE THREAD

**Issue by supachailllpay** [crabbly/Print.js#311]
I try to use with base64 data but nothing happens:

```
let base64 = 'JVBERi0xLjMKJcTl8uX...'

printJS({
  printable: base64,
  type: 'pdf',
  base64: true
})
```

Then I look into the source code, It seems it has to pass `ArrayBuffer` rather than `String`. So I try:

```
let base64 = 'JVBERi0xLjMKJcTl8uX...'
let bytes = Uint8Array.from(atob(base64), c => c.charCodeAt(0))

printJS({
  printable: bytes,
  type: 'pdf',
  base64: true
})
```

And it works. Not sure this intended or bug or I missed something?

Thank you.

**Comment by crabbly** [comment]
Hey @supachailllpay, 

This is not intended, we should change it. Thank you for reporting this.

The base64 feature is new, and it tried to reuse the same `createBlobAndPrint` that was already available to cache PDF documents that were retrieved through the XMLHttpRequest in pdf.js.

In pdf.js, whenever we use base64, we should create the bytes array from the base64 string right before it calls `createBlobAndPrint`.

**Comment by crabbly** [comment]
@supachailllpay 
Added the change as well a test example to the repo. Will be releasing this soon.
https://github.com/crabbly/Print.js/commit/374b6840a8055052f1eb3b69007e321f84b4fc1e
Thank you 💯

**Comment by crabbly** [comment]
This was released / published to npm. 
Just run `npm update print-js` to get it. Thx.
