### ISSUE TITLE
Printing from iOS Chrome prints entire page not target

### ISSUE THREAD

**Issue by andy2708** [crabbly/Print.js#312]
If you visit printjs.crabbly.com and scroll down to Print Styled  JSON Data you will see the following screen shot. This is on iOS 12.1 and chrome 74.0.
Works for me in Safari and android chrome too

![IMG_0001](https://user-images.githubusercontent.com/3003904/57201192-583a7580-6f4a-11e9-9c7e-611bed31deb1.PNG)

**Comment by andy2708** [comment]
I did some digging and fould that in `iframeElement.contentWindow.print()` line 64 print.js, `iframeElement.contentWindow` appears to be referencing just the json data, but when called it prints entire window, like its using window.print or something similar.

**Comment by crabbly** [comment]
Hey @andy2708,
Thank you for reporting this.

Seems to be a compatibility issue with Chrome in IOS.

We are calling the print method on the iframe, but Chrome mobile in IOS seems to treat as if the method is being called on the actual document.
Here is the call: https://github.com/crabbly/Print.js/blob/master/src/js/print.js#L64

I don't really have a response for this right now. Hopefully we can figure it out. :/

**Comment by crabbly** [comment]
Closing this in favor of #33.
We should add mobile versions to our browsers compatibility table:
http://printjs.crabbly.com#browsers
