### ISSUE TITLE
Printing fontawesome icons

### ISSUE THREAD

**Issue by jankapunkt** [crabbly/Print.js#315]
I have fontawesome included as npm module and it's css is merged with other css into one large css file whose name is an ID generated when building the app. Can I display fontawesome icons without using the `css` property?

Edit: added some fiddle: https://jsfiddle.net/j6gtfdvr/

**Comment by crabbly** [comment]
Hey @jankapunkt, good question. Right now, the best way is to pass the stylesheet in the `css` property.

I'm working on a new version of the library that will do this for us automatically, but I'm not sure when that will be out yet. You can take a look how I'm doing this here:
https://github.com/crabbly/Print.js/blob/v2/src/js/init.js#L133

You could use the same technique to grab your dynamic stylesheets and pass to the lib. This will guarantee that the print job has all the necessary css.

Hope this helps.

**Comment by jankapunkt** [comment]
Thanks a lot @crabbly this fixed some bootstrap-related css bugs because we internally use a highly modified bootstrap, which is now applying correctly. However the icons are still not present. I think this has to do something with fontawesome (4.7) being a font that has to be loaded somewhere in one of our packages.

I think this is fixed with font awesome 5 where icons can be loaded as svg, too, but until then I will have to find a workaround by loading the font.

**Comment by crabbly** [comment]
Interesting. If you pass the same css used to display, it should work as expected. Here is your fiddle updated:
https://jsfiddle.net/v30br61c/

As long you pass all your css, you can also set `scanStyles` as false to prevent the lib from processing each html element. This is recommended.
https://jsfiddle.net/v30br61c/1/

**Comment by crabbly** [comment]
Printing SVGs would work as well:
https://jsfiddle.net/crabbly/eoxo57jo/

**Comment by crabbly** [comment]
I think the issue you are having maybe indeed related to fonts. If the css is trying to import a font, if that is not already cached by the browser, it could take too long for it to load, and the print job will fire before the font is available. Just a guess here.

**Comment by crabbly** [comment]
Closing this for now as there isn't a related issue to the library. Passing the `css` property is currently required in v1, for this scenario. Feel free to reopen if necessary.
