### ISSUE TITLE
Can't load the image

### ISSUE THREAD

**Issue by FateCycle** [crabbly/Print.js#317]
I called printJS('cat.jpg', 'image') as described in the documentation, but did not display the image in print preview.

**Comment by crabbly** [comment]
Please post more information about your environment, library import, if the image is cached or not, etc...

**Comment by FateCycle** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://printjs-4de6.kxcdn.com/print.min.css"/>
    <script src="https://printjs-4de6.kxcdn.com/print.min.js"></script>
    <title>Document</title>
</head>
<body>
    <image src="test-01.jpg"/>
    <button type="button" onclick="printJS('test-01.jpg','image')">
        Print
     </button>
</body>
</html>

**Comment by FateCycle** [comment]
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://printjs-4de6.kxcdn.com/print.min.css"/>
    <script src="https://printjs-4de6.kxcdn.com/print.min.js"></script>
    <title>Document</title>
</head>
<body>
    <div>woshotiancai</div>
    <image src="test-01.jpg"/>
    <button type="button" onclick="printJS('test-01.jpg','image')">
        Print JSON Data
     </button>
</body>
</html>
```

**Comment by FateCycle** [comment]
the picture and the HTML file are placed in the same directory

**Comment by crabbly** [comment]
Are you getting any errors?

**Comment by FateCycle** [comment]
the console didn't report errors

**Comment by FateCycle** [comment]
cat.jpg:1 GET http://127.0.0.1:5500/%E2%80%AA/cat.jpg 404 (Not Found)
I got the error just now,but i didn't know what does %E2%80%AA mean

**Comment by crabbly** [comment]
Hey @FateCycle I wish I could help you more. This issue is not related to the library.
You can run image print tests in the documentation page: https://printjs.crabbly.com/#image

Try passing the full page to the image, probably something like this:
`printJS('http://127.0.0.1:5500/cat.jpg', 'image')`

**Comment by FateCycle** [comment]
After using  http://127.0.0.1:5500/cat.jpg as url,the request can get a response on the network tab,but the image still don't display in the print preview.As a test,I only wrote a HTML files and added a picture in the same folder and try to run the HTML to get the result. Do I  need a more complicated environment configuration?

**Comment by crabbly** [comment]
The lib doesn't require anything special. Your HTML document should work fine. 
The repository has an example for manual tests:
https://github.com/crabbly/Print.js/blob/master/test/manual/index.html

**Comment by crabbly** [comment]
Closing this as I don't think there is an issue with the library. 
Feel free to reopen if necessary. Thank you.
