### ISSUE TITLE
Images can't loading & image no defined in HTML (in Official example)

### ISSUE THREAD

**Issue by wuanyang** [crabbly/Print.js#319]
![image](https://user-images.githubusercontent.com/31607719/57742901-7b58e800-76f5-11e9-99b8-f8065f8d6acc.png)
![image](https://user-images.githubusercontent.com/31607719/57742923-8f9ce500-76f5-11e9-8b9e-d43a05c9283b.png)

**Comment by JandersonConstantino** [comment]
Hi @wuanyang,
Could you publish your example in [codesandbox](https://codesandbox.io/) for us to understand what's happening?

**Comment by crabbly** [comment]
Hi @wuanyang, thank you for reporting this.
I'll take a look at it and post an update here.

**Comment by wuanyang** [comment]
I tried to introduce PrintJS into my project, but the path to the image must be base64。

**Comment by crabbly** [comment]
The issue with images not being loaded has been fixed. Please run `npm update print-js` to get the library latest version. Or run a git pull to get the updated repository.

About the base64 image, the library doesn't currently have that feature. That's something we could implement though. We just added base64 support for PDF documents. There is a new example on the documentation page:
http://printjs.crabbly.com#pdf

I'm closing this ticket related to the image loading issue. 
Feel free to open a new one to request a feature. Thank you.
