### ISSUE TITLE
Can you advice what I'm doing wrong

### ISSUE THREAD

**Issue by vlamic** [crabbly/Print.js#320]
Hi,

First of all, thank you so much for such an amazing library. 

I'm trying to use it with my project to print base64 data, however the print dialog shows the actual page instead of my base64 data (PDF file). Can anyone advice me what am I doing wrong? Thank you!

Code:
```
require('print-js');

printButton.addEventListener('click', async data => {
       const pdfFile =  'JVBERi0xLjcKJf.....';
        print({
              printable: pdfFile,
              type: 'pdf',
              base64: true,
              fallbackPrintable: 'data:application/pdf;base64,' + pdfFile
        });
});
```

Library version: 1.0.56

**Comment by crabbly** [comment]
Hi @vlamic, 

What's your environment? OS and Browser including version.
Thank you.

**Comment by vlamic** [comment]
@crabbly I'm on macOS Mojave 10.14.4 and experienced the same issue with both Safari Version 12.1 and Chrome Version 74.0.3729.131.

**Comment by crabbly** [comment]
Interesting. I don't know why it would print the actual page. But here is some info though, we found a problem with the base64 print where it would just print a blank page (again, not your actual page). The fix has already been pushed to the repository, but it wasn't published to npm yet. 
For ref: https://github.com/crabbly/Print.js/commit/374b6840a8055052f1eb3b69007e321f84b4fc1e

I will rush with this and let you know once the fix has been published. 
Thank you.

**Comment by vlamic** [comment]
Thank you so much! I’ve tried manually applying the fix you’ve mentioned, but without any luck - it’s still printing the whole page.

**Comment by crabbly** [comment]
If you replicate this issue in a fiddle, I could help you further. Right now, I'm unable to replicate it locally. Chrome on MacOS.

**Comment by crabbly** [comment]
Also, try downloading the latest version, currently v1.0.57.

**Comment by crabbly** [comment]
Hey @vlamic, 
I have added an example printing base64 pdf on the documentation page:
http://printjs.crabbly.com#pdf

Take a look at it, hope it helps.
Don't forget to run `npm update print-js` to get the latest version.

If you still think there is a problem with the library, please replicate the issue in a fiddle and reopen this.
Thank you.
