### ISSUE TITLE
Print.JS adding its own inline style?

### ISSUE THREAD

**Issue by mearleycf** [crabbly/Print.js#322]
Hey, I noticed within the iFrame that there is a DIV with some inline style that is pretty aggressive, and overwriting some other code of ours. Is it actually coming from print.js or from somewhere else? 
```
style="font-family:TimesNewRoman !important; font-size: 12pt !important; width:100%;"
```
Within that <div> is the actual content that I selected using the element ID in the JS call.

**Comment by crabbly** [comment]
Yes. These can be overwritten by you using the `font` and `font_size` parameters.

They do indeed create problems and will be removed from the library. They were already marked as deprecated in the documentation:
https://printjs.crabbly.com/#configuration

**Comment by crabbly** [comment]
Closing this since it isn't really an issue / bug. Parameters are available to customize the print format and v2 will eliminate this behavior and not impose a print default style.
