### ISSUE TITLE
Trying to print a hidden element

### ISSUE THREAD

**Issue by wunderdojo** [crabbly/Print.js#323]
I'm using it to print a receipt to a thermal printer using Vuejs as part of a point of sale application. The idea was to generate a receipt in a hidden element as the cart is being filled and then when the order is submitted print out the receipt. 

Got it all working with one caveat: No matter what I tried I couldn't get it to print with a hidden dom element. I tried everything I could possibly think of:
* Use style to pass a string overriding visibility or display, ex: #el{ visibility: visible; }
* Set scanStyles to false and pass through the style properties I needed -- worked for visibility but most of the styles didn't come through;
* Defined @media print -- totally ignored;
* Use css to pass a stylesheet -- couldn't find any documentation on what it is expecting in terms of URL (absolute, relative) and testing multiple ways locally I couldn't seem to get that;
* Tried absolute positioning to just move it offscreen but that blew out most of the styles;

Ended up doing it a really hacky way. I left the receipt visible, added a spacer element to push it far off the page and then removed that via ignoreElements when printing. Works with the exception that some of the styles applied after the spacer element disappear. Ex: without the spacer element an H1 prints a certain way. With the spacer (which then gets removed) some of the styles drop from the H1, like font-size, and even specifying them specifically in CSS doesn't seem to affect it.

I may well be missing something obvious and what I've got now works just fine. Really appreciate your work on this, managed to get a functional solution completed in a day thanks to it.

**Comment by crabbly** [comment]
Hey @wunderdojo, 

The library should be able to print hidden elements without any issues, as long you pass the correct style updates with either `style` or `css` properties. 

You can also use CSS print media queries to manipulate this. It's actually not a bad idea to create a print media query to properly setup your expected print layout, keeping it separate from your screen display layout.

Ex.: 
```
@media print { 
 #el { visibility: visible; }
}
```

That said, you can also use the `style` parameter as mentioned above. Try confirming that the element id is correct. Also, try using `!important` and see if that helps.
Ex.: `#elelement_id { visibility: visible !important; }`

**Comment by crabbly** [comment]
I created a codesandbox example printing hidden elements:
https://codesandbox.io/s/printjs-html-lf0u1

Feel free to reopen this if necessary.

**Comment by wunderdojo** [comment]
Hi sorry for the slow response, really appreciate you taking the time to answer this and put together the example code.  Turns out the issue is with tagetStyles. If passed as below the style property seems to be ignored. Tested with your code as well and got the same result -- visibility remains hidden.

`printJS({
     printable: 'receipt',
     type: 'html',
     targetStyles: [ '*' ],
     style: ' .receipt { visibility: visible!important; } ',
})`

Get rid of targetStyles and it works as you documented but then I lose all the Vuejs styles. If you pass specific styles instead of the wildcard it also works but a number of things don't format correctly, ex: font-size and font-family.

`printJS({
     printable: 'receipt',
     type: 'html',
     targetStyles: [ 'width' ],
     style: ' .receipt { visibility: visible!important; } ',
})`

**Comment by crabbly** [comment]
Hey @wunderdojo,

With `targetStyles: [ '*' ]`, the library will process all applied styles to the DOM element, and use them when printing. If passing `style: ' .receipt { visibility: visible!important; } ',` doesn't work, it must be a css conflict.

Once you fire the print job, the library will leave a hidden iframe on the page document body. Use your dev tools to inspect that iframe document and check for the element that you are missing in your print job. You should be able to figure out what's going on there. Hope this helps.

**Comment by wunderdojo** [comment]
I guess I wasn't clear in that reply when I said I tested with your code. I mean I edited the codesandbox adding targetStyles: [ '*' ] and it doesn't work there either.  When you hit print the .special-element div remains hidden and doesn't show up on the print out.

Here's a fork that shows it: https://codesandbox.io/s/printjs-html-6dwnd

Am I just misunderstanding something here or is that not the expected behavior? 

Thanks.

**Comment by crabbly** [comment]
Hey @wunderdojo, if you pass the css `!important` flag, it should force the style sent with the `style` parameter. 
Here is an updated condesandbox:
https://codesandbox.io/s/printjs-html-moj7s

**Comment by wunderdojo** [comment]
Finally figured it out. In Vuejs all of the parent styles are cascading down to the child elements. Ex:
```
<div class='receipt'>
  <h3>The Tap Room</h3>
  <ul>
    <li>Item One: Price $X</li>
   </ul>
</div>
```
Using `style: ".receipt { visibility: visible!important; }`  wasn't working because the h3, ul and li all had their visibility set to hidden as well. I had to specific each element within the parent dom in the style rule.

Hope that saves anyone using Vuejs some headaches.

**Comment by crabbly** [comment]
I'm glad to hear you were able to figure it out.

Keep in mind that Vue allows you to scope the component style so that it won't get applied to other components. If you are using single file components, add `scoped` in your style tag:

```css
<style scoped>
  ... styles here will be applied to this component only...
</style>
```

https://vuejs.org/v2/style-guide/#Component-style-scoping-essential
