### ISSUE TITLE
It contains base64 format images，If the data format is an array, it is not printed in the array order

### ISSUE THREAD

**Issue by Yxliam** [crabbly/Print.js#324]
printable:[‘1.jpg’,’base64’,’2.jpg’,’3.jpg’]，It contains base64 format images，If the data format is an array, it is not printed in the array order，

**Comment by crabbly** [comment]
Hey @Yxliam,

About base64 images, the library won't do any special processing with them. They will be attached to a `img` element `src`. I believe that if you prefix the base64 string with `data:image/png;base64, ` or `data:image/jpeg;base64`.

Ref: https://stackoverflow.com/questions/8499633/how-to-display-base64-images-in-html

About the order issue, this has been already reported here: #309
Closing this to prevent duplication. Thank you.
