### ISSUE TITLE
print-Custom head and tail issues?

### ISSUE THREAD

**Issue by cokecole** [crabbly/Print.js#325]
How to customize the text in the header and footer, and how to add a qr code such as the service number at the bottom right of each page? I hope you can help me. Thank you

**Comment by crabbly** [comment]
Hey @cokecole,

About the header and footer, I think you mean the ones printed by the browser. This is a user setting and cannot be manipulated with Javascript alone.

Refer to #145, #161, #162, #205, #211, #218 

About the QR code, just pass it as an image within your HTML print. To repeat it for each page however, the library doesn't have a feature for this. 
Refer #96 

You can try using an HTML table, either with `<thead>` or `<tfoot>` to repeat data on every page.

Feel free to reopen this if I miss understood you. Thank you.
