### ISSUE TITLE
Some CSS selectors don't seem to work when included in style parameter.

### ISSUE THREAD

**Issue by ChuckWaltz** [crabbly/Print.js#326]
It seems that some CSS selectors like below don't apply when being put into the style parameter:

input:checked ~ .custom-checkbox
{
   ...
}

**Comment by crabbly** [comment]
Hey @ChuckWaltz, 

The library will attach the `style` value to a style tag in the iframe document, before firing the print job. If the CSS is valid it should get applied as expected. There is no special processing on this parameter.

If you replicate this in a fiddle or codexandbox, I may be able to help a bit further.

**Comment by bartolomeukuma** [comment]
maybe I'm wrong, but I think you're replacing some styles.
when I try to print some raw-html I have this kind of error but a quick look at my css and I got it fixed

**Comment by crabbly** [comment]
@bartolomeukuma The lib doesn't replace anything in the `style` value. 
Take a look on how it is handled:
https://github.com/crabbly/Print.js/blob/master/src/js/print.js#L27

**Comment by ChuckWaltz** [comment]
Thanks for the help guys. I'm still not sure exactly what I was doing wrong here and wasn't really sure how to replicate in a fiddle, but I found a workaround for getting the styles I needed to show up in the print.

The only thing I really noticed is that in the iFrame there was no <input> element from what I could tell, which would explain why the input:checked prefix wasn't affecting anything.

Not sure if this will help anyone but I wrote this javascript to create the styles based on their parent's IDs beforehand and then added to the styles parameter in printjs:

              $(
                  ".control-container:has(input[type='checkbox']:checked)"
                ).each(function() {
                  checkedCheckboxIDs.push(this.id);
                });
                let checkedStyles = "";
                checkedCheckboxIDs.forEach(id => {
                  checkedStyles =
                    checkedStyles +
                    "#" +
                    id +
                    ` .custom-checkbox:after
                    {
                      display:block !important;
                    }`;
                });
                let checkedRadioIDs = [];
                $(".control-container:has(input[type='radio']:checked)").each(
                  function() {
                    checkedRadioIDs.push(this.id);
                  }
                );
                checkedRadioIDs.forEach(id => {
                  checkedStyles =
                    checkedStyles +
                    "#" +
                    id +
                    ` .custom-radio:after
                    {
                      display:block !important;
                      background-color: var(--control-checkmark-color) !important;
                    }`;
                });

**Comment by crabbly** [comment]
Thank you for the feedback, @ChuckWaltz.

The library uses `cloneNode` to copy the target HTML into the iframe. This method is not perfect. We will have to copy each element manually. 
There is already an open issue for this if you want to follow: #187 

Thx again guys.

**Comment by crabbly** [comment]
We implemented a custom deep clone method into the library.
Checkbox state, select element user selection, canvas and other previously unsupported elements  are now supported by the library. 
Please run `npm update print-js` to get the latest version.

Feel free to reopen this if any issues. Thank you.
