### ISSUE TITLE
base64 option not available in Configuration interface

### ISSUE THREAD

**Issue by penniath** [crabbly/Print.js#329]
Hi,

I am trying to print a base64 encoded PDF file. Following the steps described at the site, TS compiler is not finding the base64 option in Configuration interface. I am trying to include this library in my Angular CLI app.
I have tried 1.0.55, 1.0.56 and 1.0.57 versions. Is any of these releases completely OK?

Thanks in advance.

**Comment by crabbly** [comment]
Hey @penniath,

The `base64` option is missing in the TypeScript interface. This is a new feature and we forgot to add it in there. I'll be pushing it soon and update here once it has been published to npm.

Thank you for reporting this.

**Comment by crabbly** [comment]
This has been added and published to npm. 
https://github.com/crabbly/Print.js/releases/latest
run `npm update print-js` to get it.

Feel free to reopen this if any issues.
Thank you.

**Comment by mahadoang** [comment]
base64 Error

```
printJS({
                            printable:result.pdf,
                            type:'pdf',
                            base64:true,
                            fallbackPrintable:`data:application/pdf;base64,${result.pdf}`,
                        });
```

DOMException: Failed to execute 'atob' on 'Window': The string to be decoded contains characters outside of the Latin1 range.
