### ISSUE TITLE
Why is the style messy when printing a table?

### ISSUE THREAD

**Issue by edon92** [crabbly/Print.js#332]
![Uploading bug.png…]()
<img width="438" alt="bug2" src="https://user-images.githubusercontent.com/29009955/58383604-63de0100-800b-11e9-9241-f5fbef20ad3a.png">
hello! how to solove this problem?

**Comment by edon92** [comment]
<img width="889" alt="bug" src="https://user-images.githubusercontent.com/29009955/58383618-8243fc80-800b-11e9-8c68-3341cb4167d3.png">

**Comment by edon92** [comment]
my code:

  printJS({ printable: className,
  type: 'html',
  scanStyles: false,
  style: 'td { border: 1px solid #d9d9d9 !important;}' });

**Comment by crabbly** [comment]
Hey @edon92, 
Thank you for reporting this. I'm not sure what the issue is. Will look into it.

Are you using an css stylesheets to style your table or are you using inline styling?

**Comment by edon92** [comment]
Thank you for your reply。
I'm using Vue and ElementUI to write my project. stylesheets 、inline styling，i use both.

**Comment by crabbly** [comment]
Yea, I would go that route. Disable the lib style processing, pass all the stylesheets through the `css` property. 

First, make sure you have the latest version by running `npm update print-js`

Then give that a try. Let me know how it goes.

**Comment by edon92** [comment]
I change my code, like that:
      printJS({
        printable: 'printJS-form',
        type: 'html',
        scanStyles: false,
        css: ['https://unpkg.com/element-ui/lib/theme-chalk/index.css'],
      });
the stylesheets it work,but the overall look does not match。
maybe elementUI.css not suitable for printing like this，i guess...
![image](https://user-images.githubusercontent.com/29009955/58427142-5ab76780-80d1-11e9-8f83-42217f2de894.png)

**Comment by crabbly** [comment]
I'm not sure if the issue is related to your css. I'll be running more tests with html grids to see what we can do to improve this.

**Comment by crabbly** [comment]
Hey @edon92, please update the library to its latest version and try this again. Also, remember you can pass any custom styles using the `style` property. This is useful when printing HTML from tables that are nicely formatted inside containers, but that may need some help to display well when displayed on their own.
If necessary, please reopen this again with a fiddle or codepen replicating the issue. Thank you.
