### ISSUE TITLE
Symbol Error  for  IE 11

### ISSUE THREAD

**Issue by GuoSirius** [crabbly/Print.js#335]
![image](https://user-images.githubusercontent.com/48358523/58408532-94bc4580-80a0-11e9-9315-773301fa644c.png)

在 IE 下打印时 一直报错

**Comment by crabbly** [comment]
@GuoSirius Please post more information about your issue. What are you printing for example, including your `printJS` code usage. Thank you.

**Comment by GuoSirius** [comment]
![image](https://user-images.githubusercontent.com/48358523/58442708-8c571f80-811f-11e9-868b-e328e19eb0cd.png)


1.0.59及其以前的版本都可以，之后的就不行

**Comment by crabbly** [comment]
I don’t think I can help you with all this code. If you remove all these hooks, including the onBreforePrint, and the style as well, do you still get the same error?

Also, is the same error happening when you print the docs examples? Thx

**Comment by GuoSirius** [comment]
删除也一样，这个使用传统jQuery做的项目，另一个使用的vue，直接用的是原始版本，没做任何改动和onBeforePrint

**Comment by crabbly** [comment]
English only please.
Thank you.

**Comment by zcr01** [comment]
@crabbly same error happens in the html form print of the docs examples.

**Comment by natalan** [comment]
Same error in IE11 on my side:

```
TypeError: Object doesn't support property or method 'Symbol(Symbol.iterator)_9.fsnr8huaty0'
  at Anonymous function(./node_modules/print-js/dist/print.js:1048:1)
  at r.onload(./node_modules/print-js/dist/print.js:1040:1)
```

![image](https://user-images.githubusercontent.com/276187/58715062-1e675e00-8394-11e9-9203-92733b5e061b.png)

**Comment by rob24g** [comment]
Yes I get this same error as well. Even when I try the doc examples console throws the same error.

'Symbol' is undefined

**Comment by jblotus** [comment]
Same error. Any ideas?

**Comment by jblotus** [comment]
Ended up switching to https://www.npmjs.com/package/printd for printing raw html and it seems to work pretty well across browsers.

**Comment by natalan** [comment]
v1.0.57 doesn't have this issue. My guess something should have changed in the recent versions around babel preset config that prevented injecting polyfill for `Symbol`

**Comment by crabbly** [comment]
This is good to know. We should rollback the changes since 1.0.57 and release them under the 2.0 branch.
