### ISSUE TITLE
Styles no longer being applied to printed HTML

### ISSUE THREAD

**Issue by GrumpyCrouton** [crabbly/Print.js#338]
I've used printJS for a while now for a specific page in my project, which contains multiple tables that should all be printed on their own page. Today, one of my users reported that it is no longer applying any styles to the printed sheet. The tables are being formatted properly on the page, but not in the print.

I haven't changed anything, but it is no longer working properly.

Here is my (previously working) code:

```
<script src="https://printjs-4de6.kxcdn.com/print.min.js"></script>

<style type="text/css">
	table { page-break-after: always }
</style>

<div id="page_content">
	
	<include href="rc/views/menu.htm"/>
	
	<div class="uk-container">
	
		<button onclick="printJS({printable: 'printTable', type: 'html', maxWidth: 2000, targetStyles: ['*']})">Print</button>
		
		<input type="text" onkeyup="$('.topic').html($(this).val());"/>
		
		<div >
			<div class="" id="printTable">
				<repeat group="{{ @data }}" value="{{ @row }}">
					<h3><span class="topic">Topic</span></h3>
					<table class="uk-table uk-table-divider uk-table-small">
						<thead>
							<tr>
								<th colspan="3">{{ @row[0][label] }}</th>
							</tr>
							<tr>
								<th class="uk-table-shrink">Count</th>
								<th class="uk-table-shrink">Name</th>
								<th>Signature</th>
							</tr>
						</thead>
						<tbody>
							<!-- various rows added here -->
						</tbody>
					</table>
				</repeat>
			</div>
		</div>
		
	</div>

</div>
```

**Comment by GrumpyCrouton** [comment]
Updated my code a bit, now the page breaks are working but the styling is still not.

```
<script src="https://printjs-4de6.kxcdn.com/print.min.js"></script>

<div id="page_content">
	
	<include href="rc/views/menu.htm"/>
	
	<div class="uk-container">
	
		<button id="print_button">Print</button>
		
		<input type="text" onkeyup="$('.topic').html($(this).val());"/>
		
		<div >
			<div class="" id="printTable">
				<repeat group="{{ @data }}" value="{{ @row }}">
					<h3><span class="topic">Topic</span></h3>
					<table class="uk-table uk-table-divider uk-table-small">
						<thead>
							<tr>
								<th colspan="3">{{ @row[0][label] }}</th>
							</tr>
							<tr>
								<th class="uk-table-shrink">Count</th>
								<th class="uk-table-shrink">Name</th>
								<th>Signature</th>
							</tr>
						</thead>
						<tbody>
							<repeat group="{{ @row }}" key="{{ @ikey }}" value="{{ @teammate }}" counter="{{ @ctr }}">
								
								<check if="{{ @ctr == 21 }}">
									</table>
									<h3><span class="topic">Topic</span></h3>
									<table class="uk-table uk-table-divider uk-table-small">
										<thead>
											<tr>
												<th colspan="3">{{ @row[0][label] }}</th>
											</tr>
											<tr>
												<th class="uk-table-shrink">Count</th>
												<th class="uk-table-shrink">Name</th>
												<th>Signature</th>
											</tr>
										</thead>
										<tbody>
										<span style="display: none;">{{ @ctr = 1 }}</span>
								</check>
								
								<tr>
									<td>{{ @ctr }}</td>
									<td>{{ @teammate[name] }}</td>
									<td>Sign Here: </td>
								</tr>
							</repeat>
						</tbody>
					</table>
				</repeat>
			</div>
		</div>
		
	</div>

</div>

<script>
	$(function(){
		$('#print_button').on('click', function() {
			printJS({
				printable: 'printTable',
				type: 'html',
				style: 'table { page-break-after: always }',
				targetStyles: ['*', 'page-break-after']
			});
		});
	});
</script>
```

**Comment by crabbly** [comment]
Hi @GrumpyCrouton, 
I have confirmed the issue when printing grids and tables. I'm trying to figure this out.
Will post an update here as soon as I have one.
Thank you.

**Comment by GrumpyCrouton** [comment]
@crabbly Are you sure that's the problem? To me it looks like the issue is with `targetStyles`. Adding the `style` option fixed the issue with the page breaks, and I was able to fix the rest of the CSS by including it with the `css` option.

**Comment by crabbly** [comment]
Have you tried disabling the style processing?
Pass `scanStyles: false`, then pass an array of all your stylesheets to the `css` parameter. 

Let me know how that goes.

**Comment by GrumpyCrouton** [comment]
@crabbly I've got it working but I didn't need to do that. What is the purpose of targetStyles if I have to include all my css manually?

**Comment by crabbly** [comment]
I don't think you understand what the library is doing. The `targetStyles` property is used when the library process all the applied style to the HTML elements that you are trying to print. It lets you control what styles the library should process. 

You do however, have the option to cancel this processing, and pass your style manually. This allows you to better control your print results. You could, for example, create a print stylesheet, to properly setup your print styles, which may be different from the layout showed on screen. It depends on your environment and elements being printed.

**Comment by crabbly** [comment]
I miss read your previous comment where you mentioned the usage of the `css` property. I'm glad you got it to work. The next version of the library will grab all your stylesheets for you, automatically. It should be coming out in the next month.

**Comment by crabbly** [comment]
For ref: #332

**Comment by chakradarraju** [comment]
Is it possible to include all tailwind styles when printing?
