### ISSUE TITLE
How do I use CSS properties in a vue project

### ISSUE THREAD

**Issue by yizhichenfamily** [crabbly/Print.js#339]
![image](https://user-images.githubusercontent.com/28775684/58744812-6e205500-847a-11e9-91e0-5b65f23d810b.png)
![image](https://user-images.githubusercontent.com/28775684/58744813-7ed0cb00-847a-11e9-8542-1d8aeeae1703.png)
![image](https://user-images.githubusercontent.com/28775684/58744821-9019d780-847a-11e9-9428-d28634b0be50.png)
![image](https://user-images.githubusercontent.com/28775684/58744825-9c059980-847a-11e9-883a-0c86d64e0261.png)

**Comment by yizhichenfamily** [comment]
When I print there are no styles

**Comment by crabbly** [comment]
Hey @yizhichenfamily,

Pass in your compiled css url. 
For example: `http://my_site.com/my_stylesheet.css` or just `/my_stylesheet.css`.

**Comment by yizhichenfamily** [comment]
nothing has changed

**Comment by yizhichenfamily** [comment]
There's still no style

**Comment by chentvtchen** [comment]
我找到解决办法了，你可以先输出为canvas，然后直接打canvas
