### ISSUE TITLE
Avoiding failures when there is a SVG element

### ISSUE THREAD

**Issue by movink** [crabbly/Print.js#34]
According to the https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/children
getting children on SVG element is not supported in IE, however, in printjs has the code

    let children = currentElement.children
    if (children.length) {
      this.loopNodesCollectStyles(children)
    }

and this result a failure as children is null in IE.
Could you please be able to add a null check to the condition so it does not result in failure in IE whenever there is a SVG tag.

**Comment by crabbly** [comment]
Done! You can use the latest release now: https://github.com/crabbly/Print.js/releases/latest
Thanks for pointing this out @movink  :)
If you like the library, please star the project.

**Comment by movink** [comment]
Thank you so much @crabbly for your quick response on this. Yup, you deserve a star for sure :+1:  
I will test the library today.

**Comment by movink** [comment]
Just to confirm, it works great now. Thanks

**Comment by crabbly** [comment]
Awesome! :)
