### ISSUE TITLE
Default scale is breaking the page. 

### ISSUE THREAD

**Issue by Santosh-CodeAstu** [crabbly/Print.js#340]
When I click on print button it loads the pdf from url, but **scale** attribute in print dialogue was set to **Default** and it is breaking the page. But if I set to **Fit to page** it works fine. Can someone help me to get it fixed?

**Comment by crabbly** [comment]
Hey @Santosh-CodeAstu, this is the user's browser setting. 
We can't control it via javascript alone.
About your PDF document having to use the Fit to Page setting, you may want to check your PDF document page size. Good luck!
