### ISSUE TITLE
Different Versions NPM/Github

### ISSUE THREAD

**Issue by DouglasOGarrido** [crabbly/Print.js#341]
Hi,

I was going to do the update of the version, but I realized that in NPM the last reported version is 1.0.61, but in Github, the last release is 1.0.59. What has changed in this upgrade to version 1.0.61?

Thks

**Comment by crabbly** [comment]
Hey @DouglasOGarrido,
Thank you for reporting this. Currently, 1.0.61 is the latest version.
I'll update the documentation soon. Thx again.

**Comment by crabbly** [comment]
Changes will be available under the release notes.

**Comment by crabbly** [comment]
Done :)
https://github.com/crabbly/Print.js/releases/tag/v1.0.61
https://printjs.crabbly.com
