### ISSUE TITLE
iPhoneX Safari - pure html, does not find Print Dialog and therefore fails to print

### ISSUE THREAD

**Issue by andyhill2** [crabbly/Print.js#342]
iPhoneX Safari - pure html, does not find Print Dialog and therefore fails to print.

Works fine on Desktop Chrome.

Please advise

**Comment by andyhill2** [comment]
My framework is UniGUI and I resolved this problem by adding a timing delay.

**Comment by andyhill2** [comment]
My solution worked for Safari and Chrome but NOT EDGE

**Comment by andyhill2** [comment]
My solution worked for Safari and Chrome but NOT EDGE

Can anyone shed light on why ?

**Comment by crabbly** [comment]
Hi @andyhill2, 
I tested html print in Edge on Windows 10 and it worked.
What is your OS and version?

**Comment by andyhill2** [comment]
Firstly Windows 10 Pro (latest update) for the Desktop Edge and Chrome Testing.

I am using the UniGUI Framework (wrapper around Sencha) under Delphi (Object Pascal) for my WebApp.

For Desktop Chrome and Mobile Safari to work I have to add a delay as follows:-

htmFrame.JSInterface.JSCode('Ext.defer(function(){'#1'.iframe.contentWindow.print()}, 100);');

There was some chatter saying the Print function executes before the page is rendered, however no amount of delays allow Desktop Edge to print  (button just blinks when pressed).

htmFrame.HTML.Add('&nbsp;<button type="button" onclick="printJS({printable: [''myTable''], type: ''html''})">Print via: Mobile Safari -or- Desktop Chrome</button>');

**Comment by crabbly** [comment]
Mobile browser support is still quite weak due to different behavior between mobile and desktop browsers Api. Unfortunately.
Closing this is favor of #33. I hope we can eventually improve this.
