### ISSUE TITLE
multiple-image printing needs to be sent to PrintJs twice

### ISSUE THREAD

**Issue by bogal** [crabbly/Print.js#344]
I have a page that loads 1>N images. The images are not directly accessible (ie can **not** be viewed with the url mysite.com/image.jpg) but are loaded through a gateway (ie the src of each image is mysite.com/view-image/54). Each image is 1920x1080 png.

Attaching an event listener to a button finds each image with a particular class, creates an array using the src's, then sends it to PrintJs:

```
$('#btnPrintAll').click(function(){
    var imgArray = [];
    $('img.my-image').each(function(){
        imgArray.push($(this).attr('src'));
    });
    printJS({
        printable: imgArray,
        type: 'image'
    });
});
```

When i pass an array of images to PrintJs, i find that the first time nothing happens. I get the icon in my (windows (10)) taskbar that something has been sent to the printer, but nothing comes out, and there are no pending pages to be printed. The print job just disappears. When i click the button again, it does indeed print out the array of images.

My question is, why do i have to click the button twice? What happens to the first print job?

Using firefox (67.0.1), i have enabled silent printing (print.always_print_silent; true).

**Comment by bogal** [comment]
Just to add i have upgraded to the latest print-js (1.0.61) and the issue remains.

**Comment by crabbly** [comment]
Hey @bogal, 
The library can print multiple images as long you pass a valid array. You can run tests on the documentation page. 

My guess here is that jQuery's `each` method could be synchronous, which would allow the `printJS` function to run before your `imgArray` is ready.

Check if jQuery has something built in for this, similar to their `then` method, or just create a promise to resolve once the array is finished, then call the promise `then` to run `printJS` inside.
Good luck!

**Comment by bogal** [comment]
Thanks for the reply. $(selector).each() is synchronous apparently, but shouldn't that mean the code after the loop isn't run until the loop is finished? Do you have an example of how you can add a promise to the .each iteration?

**Comment by crabbly** [comment]
No. It means the other way around. You can find lots of promise usage examples online.
About the code example above, I can't confirm this. Haven't used jQuery in years.
Try using promises, it should fix your issue.
