### ISSUE TITLE
Printed page shows 'Document' and 'about:xxx' at top and page # and date at bottom

### ISSUE THREAD

**Issue by jimmywinlsow** [crabbly/Print.js#345]
As above.

In HTML head, setting the following will solve the problem:
        <style>
            @page {size: auto; margin: 0mm; }
        </style>

How do I implement this when printing using print.js?

Thanks
Jimmy

**Comment by crabbly** [comment]
Hey @jimmywinlsow,

I think you are talking about the header and footer set by the browser. This is a user browser setting and we can't control that through JavaScript alone.

When it comes to pass the style to the `printJS` function, you can use the `style` property.

```js
printJS({
    printable: 'your-element-id',
    type: 'html',
    style: '@page { size: auto; margin: 0mm; }'
})
```

**Comment by jimmywinlsow** [comment]
Thanks, Rodrigo!

**Comment by Dan-Chiriac** [comment]
Hello @crabbly,

The printJS works wonders on Chrome, but on Firefox and Safari I got the same problem as in this thread. Unfortunately the solution above does not work as per https://developer.mozilla.org/en-US/docs/Web/CSS/@page, this at-rule is not supported on these browsers.

Can something else be done about this?

Thank you,
Dan
