### ISSUE TITLE
Printing address

### ISSUE THREAD

**Issue by malcolmfowler** [crabbly/Print.js#346]
Any idea why the address of the PDF is different on my local LAN to when the page is accessed from the outside?  

See below for the issue
Externally I have to reference the folder where the PDF is located.
Internally I have to reference the top folder and sub-folder off the main website.

I'm running PHP / Apache on Windows 7

 if(document.referrer == "http://192.168.1.10/wms-mfsl/goods_receipt_note.php"){
   var pdf_print = "wms-mfsl/grn_prints/" + rowid + "_labels.pdf";						
 }else{
  //coming from somewhere else externally
   var pdf_print = "grn_prints/" + rowid + "_labels.pdf";			  
  }
 var ret = printJS(pdf_print);

**Comment by crabbly** [comment]
Hey @malcolmfowler,

The library will print whatever PDF document sent to it, no matter where it is coming from. If the document is the same, it should print as expected. The library will also preload the document for you, therefore, network speed should not affect printing results, just the loading time.
Check your documents and how you are exposing them through your urls. Good luck!
