### ISSUE TITLE
Used in vue, how to reference css?

### ISSUE THREAD

**Issue by bnannnn** [crabbly/Print.js#347]
I want to use printJs in vue, only write inline styles will take effect, the style of the reference can not take effect, can you give a detailed example to learn?

**Comment by crabbly** [comment]
Hey @bnannnn, 
Try using `targetStyles: ['*']`

**Comment by bnannnn** [comment]
Already tried, still not working

> 嘿@bnannnn，
> 试试用`targetStyles: ['*']`

hello,Already tried, but still not working

**Comment by crabbly** [comment]
You have posted no code here. How do you expect any help?
We don't even know where your styles are. I'm not sure if you are writing a single file vue component and using the style tag, or if you have your styles in sass / css file.

If you have your styles in stylesheets, try passing them to the `css` property. If ALL your style is done in stylesheets, you can also disable the library style processing by setting `scanStyles: false`. This is recommended as well. 

I hope this helps. Good luck!

**Comment by bnannnn** [comment]
> 您在此处未发布任何代码。您如何期待任何帮助？
> 我们甚至不知道你的风格在哪里。我不确定您是在编写单个文件vue组件还是使用样式标记，或者您是否在sass / css文件中使用了样式。
> 
> 如果样式表中有样式，请尝试将它们传递给`css`属性。如果所有样式都在样式表中完成，您还可以通过设置禁用库样式处理`scanStyles: false`。这也是推荐的。
> 
> 我希望这有帮助。祝好运！

ok,Thank you for your answer.
