### ISSUE TITLE
onPrintDialogClose，This method doesn't work on chrome, but it works on MAC chrome, not Windows

### ISSUE THREAD

**Issue by Yxliam** [crabbly/Print.js#348]
onPrintDialogClose，This method doesn't work on chrome, but it works on MAC chrome, not Windows

**Comment by RickChenCX** [comment]
This method doesn't work on my MAC chrome, I'll test it on Windows later.

**Comment by didagu** [comment]
I am having the same issue. The method does not work on Windows. Is there any fix for this yet ?

**Comment by Sash-OK** [comment]
As a workaround try to use version 1.0.53. It works fine for me.
[Codesandbox example](https://codesandbox.io/s/printjs-onprintdialogclose-r8zgu)

**Comment by ntziolis** [comment]
@Sash-OK This does not seem to work in most current version of chrome. That said I was able to get the most current version to work after monkey patching `performPrint`:
- `print.js` listens to the `focus` event on the `window` to trigger the `onPrintDialogClose`
- in chrome this does not get fired when the print window closes, instead chrome synchronously executes `.contentWindow.print()`, meaning when it returns the print window is closed
- so all I needed to do is dispatch a `focus` event on the `window`which in turns now successfully triggers `onPrintDialogClose`

To make sure this does not break moving forward:
- I lock the `print.js` package version to the current version
- and I'm using using `patch-package` to do make sure the monkey patching is applied on npm install automatically.

```
function performPrint (iframeElement, params) {
  try {
    iframeElement.focus()

    // If Edge or IE, try catch with execCommand
    if (Browser.isEdge() || Browser.isIE()) {
      try {
        iframeElement.contentWindow.document.execCommand('print', false, null)
      } catch (e) {
        iframeElement.contentWindow.print()
      }
    } else {
      // Other browsers
      iframeElement.contentWindow.print()

// ------- This was added - start
      if(Browser.isChrome()){
        window.dispatchEvent(new Event("focus"));
      }
// -------- This was added - end
    }
  } catch (error) {
    params.onError(error)
  } finally {
    cleanUp(params)
  }
}
```

**Comment by simon-woo** [comment]
> As a workaround try to use version 1.0.53. It works fine for me.
> [Codesandbox example](https://codesandbox.io/s/printjs-onprintdialogclose-r8zgu)

i test in windows chrome , it works in 1.0.53 but not works in 1.0.63, in Mac chrome all of this version works well . try to change the version to 1.0.53.

**Comment by GranitBerisha** [comment]
Im having the same issue any fix ?

**Comment by ntziolis** [comment]
FYI the patch provided [above](https://github.com/crabbly/Print.js/issues/348#issuecomment-559414376) still works on recent version of chrome, both on mac + windows

**Comment by GranitBerisha** [comment]
@ntziolis thanks for the comment,
Im using the recent version of Chrome and the patcher but its not working, not sure If Im not patching it correctly or the chrome version, 

If you can help me with more instructions would be great thank you 😊.

**Comment by ntziolis** [comment]
I'm using version 1.0.63 of printjs and this is what my patch file looks like (places in patches folder in root)
https://gist.github.com/ntziolis/f080a92c9fcb7643ab79bd1b452ecb7e

**Comment by GranitBerisha** [comment]
Hi @ntziolis thanks again for the comment really appreciate it.

I copy pasted the patch file from you and after npm install I can see in node_modules the changes but still chrome is not detecting the closing, I have to click some where multiple times to get chrome detection,

Just to be sure for source type Im using html, can you share your printjs method thanks

**Comment by ntziolis** [comment]
That is strange, below you can find the piece of code we use. We are wrapping the call into a promise but i think not having a promise should make no difference:

```javascript
    const printPromise = new Promise<void>((resolve, reject) => {
      printJS({
        printable: url,
        type: 'pdf',
        onPrintDialogClose: () => {
          resolve();
        }
      });
    });
```

**Comment by GranitBerisha** [comment]
Hi again, any update on this?, Im using latest Chrome, Windows 10 and have tthe same issue,
I tried all the things what @ntziolis said and a big thanks from him but couldn't get it working. thanks again

**Comment by ntziolis** [comment]
I have just created a PR request to incorporate the fix into the main lib instead of using patching.

**Comment by mitestainer** [comment]
Same here. I'm printing from a JSON and `onPrintDialogClose` won't work on Chrome unless I switch to other tab and then switch back. I tried @ntziolis's patch and it doesn't work too. It works fine on Firefox without patching though.

**Comment by slebetman** [comment]
FWIW it is not necessary to actually monkey patch printjs to detect print dialog close. I've been able to use @ntziolis's code without patching to make it work on latest Chrome:

    let focuser = setInterval(() => window.dispatchEvent(new Event('focus')), 500);

    printJs({
        printable: url,
        onPrintDialogClose: () => {
            clearInterval(focuser);
            // do your thing..
        },
        onError: () => {
            clearInterval(focuser);
            // do your thing..
        }
    });

**Comment by crabbly** [comment]
Hey guys, I have tested this locally using the index.html file under test/manual (served by running `npm start`), on Windows 10 with the latest version of Chrome, and it seems to be working fine. However, when using the codepen it doesn't work. I also created a fiddle to replicate the same code in a different platform, and it doesn't work either. 
fiddle: https://jsfiddle.net/crabbly/v4m32gLz/5/

At this point I have no idea why it works in the test example but not in the codepen and fiddle, but I thought I would add this information here.

My guess is some kind of conflict with the `focus` event listener. In the fiddle, if you print and them click around the screen multiple times, eventually it will run the callback. 

I hope we can find a stable solution.

**Comment by crabbly** [comment]
This is now fixed in master. I will post an update here once the fix has been published to npm. Thank you guys.

**Comment by crabbly** [comment]
This change was published to npm with v1.5.0. Please run npm update print-js to get it. Thank you

**Comment by Corgis** [comment]
> FWIW it is not necessary to actually monkey patch printjs to detect print dialog close. I've been able to use @ntziolis's code without patching to make it work on latest Chrome:
> 
> ```
> let focuser = setInterval(() => window.dispatchEvent(new Event('focus')), 500);
> 
> printJs({
>     printable: url,
>     onPrintDialogClose: () => {
>         clearInterval(focuser);
>         // do your thing..
>     },
>     onError: () => {
>         clearInterval(focuser);
>         // do your thing..
>     }
> });
> ```

it works well

**Comment by johnknoop** [comment]
Hi! I came here from #368.

`onPrintDialogClose` isn't firing for me in Firefox 96.0.3. Here's a screen recording. Notice how the second breakpoint never gets hit:

![printjs_firefox](https://user-images.githubusercontent.com/3394270/151966076-0a4ad363-70f5-4c55-ab5d-01d3b4560f53.gif)

**Comment by johnknoop** [comment]
Actually, clicking anywhere in the viewport will make the whole thing come alive and `onPrintDialogClose` gets triggered. Really weird:

![activated_on_click](https://user-images.githubusercontent.com/3394270/151966908-28bbd7a7-401a-41de-9f15-825544831821.gif)

**Comment by songjinhu** [comment]
I'm still experiencing this problem with version 1.6.0, Google 86.0.4240.198 ，I've been able to use @ntziolis  's code without patching to make it work on latest Chrome:
