### ISSUE TITLE
iOS Safari printing page url and not the pdf document

### ISSUE THREAD

**Issue by Chaitanya21** [crabbly/Print.js#353]
I have a situation where iOS Safari is printing the document URL as a html page (including footer containing the url) in portrait instead of printing just the PDF in landscape.  This works properly on the desktop, and the pdf document prints just as it should.   The URL is dynamically generated and stored in a hidden variable via code and the printJS library is called as shown below:

var url = $("#hdnPrintPageUrl").val();
printJS({printable:url, type:'pdf', showModal:true});

The page contains the following HTML:

`
&#x3C;!DOCTYPE html&#x3E;

&#x3C;html xmlns=&#x22;http://www.w3.org/1999/xhtml&#x22;&#x3E;
&#x3C;head runat=&#x22;server&#x22;&#x3E;
    &#x3C;title&#x3E;&#x3C;/title&#x3E;
&#x3C;/head&#x3E;
&#x3C;body&#x3E;
    &#x3C;form id=&#x22;form1&#x22; runat=&#x22;server&#x22;&#x3E;
        &#x3C;div&#x3E;
        &#x3C;/div&#x3E;
    &#x3C;/form&#x3E;
&#x3C;/body&#x3E;
&#x3C;/html&#x3E;
`

But then the following .Net code is outputing the PDF as shown:

Response.Clear();
Response.ContentType = "application/pdf";
Response.AddHeader("Content-Disposition", $"{disposition}; filename={fileName}");
Response.BinaryWrite(documentData);
Response.End();
Response.Flush();

disposition is set to "inline".

As mentioned, this works just fine on all other machines it has been tested on, but does not work properly on iOS Safari.   

Any ideas?

Note: I have done the following changes to the system.  I am now pulling a base64 string from the server instead of what is shown above.   This is done via a WebAPI controller and seems to work quite well.  I have also changed the javascript code to:

var url = $("#hdnPrintPageUrl").val();
$.ajax({
     url: url,
     method: "GET",
     success: function(data) {
        printJS({ printable: data, type: 'pdf', base64: true, style: '@page { size: Letter landscape; }' });
     }
});

The problem seems to be that the printing will not switch to landscape mode for the actual printing.   The Url is no longer showing as I am using a base64 string, but I can't get the orientation to change to landscape, which is what the PDF is set to.

**Comment by crabbly** [comment]
Hi @Chaitanya21, the issue may be browser compatibility with safari in IOS. We actually have an issue open #33 with multiple reports.

I'll link and close this issue in favor of #33, and hope we can add better browser support to the library.
Thank you.
