### ISSUE TITLE
 Download the PDF directly without a print screen Library PRINTJS

### ISSUE THREAD

**Issue by mrexptux** [crabbly/Print.js#355]
Well, I would like to download the PDF directly without the print screen appearing in PrintJS

**Comment by crabbly** [comment]
Hey @mrexptux, this is a printing library. If by "download", you meant "print without the preview", this is a user browser setting. Javascript can't bypass that. 

The library eliminates the need of opening the PDF document before printing. This "preview" is also where the user can chose the printer they want to print to, and set any other print settings.

**Comment by mrexptux** [comment]
Okey Tranks! Bro
