### ISSUE TITLE
unable to print huge html contents

### ISSUE THREAD

**Issue by paraself** [crabbly/Print.js#356]
Hi, thanks for making this library.

But it seems that I cannot use it.
original code:
``` javascript
exportPdf() {
PrintJs('my-id', 'html')
}
```
It is not working, all the text are missing, only borders and background colors are there. So I thought it might is because that print-js does not wait for the onload event of the window. So I change the above code to vanilla version.
``` javascript
exportPdf() {
    let mywindow = window.open('', '')
    let doc = mywindow.document
    doc.write(this.pdfHtml)
    doc.close() // necessary for IE >= 10
    mywindow.onload = function(e) {
      mywindow.focus()
      mywindow.print()
    }
  }
```
Then it's working.

**Comment by crabbly** [comment]
Hi @paraself, thank you for posting this. 

What browser are you using?

**Comment by crabbly** [comment]
Hey Yves, please try using a css print media query to adjust the print layout. 
Let me know how it goes. Thx.

**Comment by ffqs** [comment]
Hi @crabbly 
<img width="736" alt="Снимок экрана 2019-11-21 в 10 24 52" src="https://user-images.githubusercontent.com/47789178/69316188-59fb2a80-0c49-11ea-9f51-8da0cb2b1e0f.png">
<img width="625" alt="Снимок экрана 2019-11-21 в 10 25 18" src="https://user-images.githubusercontent.com/47789178/69316189-59fb2a80-0c49-11ea-8f77-bc085643925c.png">

! I have this problem too. Text on printing not showing, but all padding and other formats showing correctly. Reproduced only for Windows, on Mac working is fine

**Comment by paraself** [comment]
> Hey Yves, please try using a css print media query to adjust the print layout.
> Let me know how it goes. Thx.

Sorry I am quite busy on launching our new app these days. Once I am free, I'll try.

**Comment by crabbly** [comment]
Hey guys, when using `targetStyles: ['*'],` with large HTML elements, we can expect all kinds of issues. The best scenario is to pass your stylesheets with the `css` property, or even some custom print style with the `style` property. 
Hope this helps.

If necessary, please reopen this with a fiddle or code pen replicating the issue. Thank you.
