### ISSUE TITLE
print() ignoring settings and printing the whole page

### ISSUE THREAD

**Issue by tomobrien2004** [crabbly/Print.js#358]
I am using this in an Angular application and have imported printJS like so into my component:

//PrintJS
import print from 'print-js';

In the html I have a div with id like so:

    <div id="timesheet">
       ....
    </div>

I have a print button which looks like this:

    <button type="button" id="print-button" onclick="print({printable: 'timesheet', type: 'html', header: 'Hello!', ignoreElements:['print-button']})">Print Timesheet</button>

Which I click the print button it opens the print page, but instead of ignoring elements or just printing the printable element, it prints the entire page.

Even when I set the printable element to be a non-existent element, it doesn't give an error and just prints the entire page.

It also includs the navbar, which is not even contained in the component that print-js is imported into! You can see in the picture that it is containing the print-button element which is in the ignoreElements. It is also not including the header as you can see below.

Any ideas what is causing this behaviour? Thanks.

![bug](https://user-images.githubusercontent.com/13018652/61593895-6c9f1d80-abdd-11e9-95e1-2216af26a5ff.jpg)

**Comment by etillier** [comment]
I am having the same problem when I import the js:
<script src="{{ url_for('static', filename='js/print.min.js') }}"></script>
The whole page is printed not just the div. 

It works fine with the CDN version: 
<script src="https://printjs-4de6.kxcdn.com/print.min.js"></script>

but that version does not respect the ignoreElements.
Thanks

**Comment by tomobrien2004** [comment]
It seems this was happening because of how I was importing the print-js:

    import print from 'print-js';

Instead of calling the printJS function in the code, I was actually using the 'print' function, which I thought was what I should rename the the function instead of printJS due to issues raised here: https://github.com/crabbly/Print.js/issues/57

This was causing the default print() function to be used and not the printJS function.
