### ISSUE TITLE
May I ask if I can print directly in chrome without preview

### ISSUE THREAD

**Issue by Yxliam** [crabbly/Print.js#359]
May I ask if I can print directly in chrome without preview

**Comment by lhj19791428** [comment]
I have the same question, the managers or developers can reply ?

**Comment by mix5003** [comment]
i think only way to do this is open chrome in kiosk mode. (and may be  enable kiosk-printing too)

**Comment by crabbly** [comment]
Hey guys, the preview is a browser feature. We can't disable it with javascript alone. Which is a good thing.

Please refer to #79
