### ISSUE TITLE
Doesn't support barcode print?

### ISSUE THREAD

**Issue by MarkLiagn** [crabbly/Print.js#36]
It seems can't print dynamic generated barcode.

**Comment by crabbly** [comment]
@MarkLiagn How are you creating the barcodes?

**Comment by crabbly** [comment]
@MarkLiagn help please!

**Comment by crabbly** [comment]
I'm closing this issue since you haven't got back with more information. I won't try to play with barcodes for now. If necessary, please open it again. Thx

**Comment by ericdude4** [comment]
I am creating barcodes with https://github.com/lindell/JsBarcode and they just appear as a black blob in the print dialogue
