### ISSUE TITLE
Mismatch between npm package and repo code

### ISSUE THREAD

**Issue by nlucero** [crabbly/Print.js#361]
There seems to be a mismatch between what's been published in `npm` and what's in the repo for that tag:

```
$ npm init
$ npm i print-js@1.0.61
```

If you take a look at your `node_modules` you'll see the code that's been fetched from `npm` is different from what's on the repo for `1.0.61`. For example, if you take a look at `src/js/print.js` (specifically the `loadIframeImages` function):

```js
// node_module/print-js/src/js/print.js

function loadIframeImages (images) {
  const promises = []

  for (let image of images) {
    promises.push(loadIframeImage(image))
  }

  return Promise.all(promises)
}

// node_module/dist/print.js

function loadIframeImages(images) {
  var promises = [];

  var _iteratorNormalCompletion = true;
  var _didIteratorError = false;
  var _iteratorError = undefined;

  try {
    for (var _iterator = images[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
      var image = _step.value;

      promises.push(loadIframeImage(image));
    }
  } catch (err) {
    _didIteratorError = true;
    _iteratorError = err;
  } finally {
    try {
      if (!_iteratorNormalCompletion && _iterator.return) {
        _iterator.return();
      }
    } finally {
      if (_didIteratorError) {
        throw _iteratorError;
      }
    }
  }

  return Promise.all(promises);
}
```

The version of [this file in 1.0.61](https://github.com/crabbly/Print.js/blob/v1.0.61/src/js/print.js#L70) is slightly different:

```js
function loadIframeImages (images) {
  const promises = Array.prototype.slice.call(images).reduce((memo, image) => {
    if (image.src && image.src !== window.location.href) {
      memo.push(loadIframeImage(image))
    }
    return memo
  }, [])

  return Promise.all(promises)
}
```

Since the `npm` version of `loadIframeImages` is using an`for...of` loop, this is breaking in `IE11` without polyfills since `HTMLCollection` doesn't have an iterator defined.

This [was fixed](https://github.com/crabbly/Print.js/pull/343) a while ago but since the `npm` package is using an old version of the code, it's still breaking.

**Comment by nlucero** [comment]
https://github.com/crabbly/Print.js/issues/360

**Comment by petrosmm** [comment]
I can confirm, was using Print.js and installed webpack (please note) as well, it would compile nicely, I was seeing this exact issue with IE. Def something in the release but when I pulled the source (1.0.61) and compiled, worked perfectly! Tried 1.0.63 but it won't compile properly either that or I missed something simple (might be a non-issue).

**Comment by crabbly** [comment]
Hey guys, this has been fixed a few versions ago. Please run npm update to get the latest version. Sorry for the long delay responding this. Thank you.
