### ISSUE TITLE
IE11 —— 1.0.61

### ISSUE THREAD

**Issue by GuoSirius** [crabbly/Print.js#364]
![image](https://user-images.githubusercontent.com/48358523/63237629-54223180-c275-11e9-8b97-9a2fa0d2cd4e.png)

1.0.56 正常

1.0.57开始就是异常

**Comment by DigitalSlim** [comment]
Any word on v1.0.62?  The print html option for 1.0.61 in IE gives a symbol is undefined error.

**Comment by fabo15x** [comment]
@crabbly could you please publish a new version to NPM in order to fix this issue?

**Comment by crabbly** [comment]
Hey guys, I'm sorry for the delay on this. I haven't had much time to support the library.

@natalan The #343 PR is already was already published with 1.0.61. Are you sure this is the same issue?

**Comment by natalan** [comment]
@crabbly yes, you need to publish it as a new patch version

**Comment by crabbly** [comment]
Done. Published 1.0.62. Thank you

**Comment by fabo15x** [comment]
Hi @crabbly thanks for your prompt reply. Unfortunately, the issue in IE11 keeps showing up in a specific case.
The error below appears in when trying to print the content of a bootstrap modal window. 
![Screen Shot 2019-11-15 at 11 40 43 AM](https://user-images.githubusercontent.com/4431815/69060762-eb6a6280-09e5-11ea-8552-e2215f66ea21.png)
This line left in the code: console.log(element.nodeType); which is outputting those numbers seen before the error line might help understand the root of the error.
Before the NPM 1.0.63 release, I was able to fix the IE issues by manually updating the print.js file in the dist folder from version 1.0.61. with @natalan patches I found in #343 . These were the two functions I manually modified in version 1.0.61 for it to work in all cases including the bootstrap modal window: 
`function loadIframeImages(images) {
	var promises = Array.prototype.slice.call(images).reduce(function (memo, image) {
	  if (image.src && image.src !== window.location.href) {
		memo.push(loadIframeImage(image));
	  }
  
	  return memo;
	}, []);
	return Promise.all(promises);
  }`
`function cloneElement(element, params) {
	// Clone the main node (if not already inside the recursion process)
	var clone = element.cloneNode();

	// Loop over and process the children elements / nodes (including text nodes)
	const childNodesArray = Array.prototype.slice.call(element.childNodes);
	for (let i = 0; i < childNodesArray.length; i++) {
		// Check if we are skiping the current element
		if (params.ignoreElements.indexOf(childNodesArray[i].id) !== -1) {
		continue;
		}

		// Clone the child element
		const clonedChild = cloneElement(childNodesArray[i], params);

		// Attach the cloned child to the cloned parent node
		clone.appendChild(clonedChild);
	}

	if (params.scanStyles && element.nodeType === 1) {
		clone.setAttribute('style', (0, _functions.collectStyles)(element, params));
	}

	// Check if the element needs any state processing (copy user input data)
	switch (element.tagName) {
		case 'SELECT':
		// Copy the current selection value to its clone
		clone.value = element.value;
		break;
		case 'CANVAS':
		// Copy the canvas content to its clone
		clone.getContext('2d').drawImage(element, 0, 0);
		break;
	}

	return clone;
}`
Let me know if I can help you somehow.

**Comment by crabbly** [comment]
Hey guys, a fix for this has been published a few versions ago. Please run npm update to get the latest version. Sorry for the long delay responding to this. Thank you.
