### ISSUE TITLE
trouble with @media print

### ISSUE THREAD

**Issue by bartolomeukuma** [crabbly/Print.js#365]
Hi... i have an css
with 2 rules for @media print
```
@media print{ ... }
```
and
```
@media print and (max-width: 80mm) { ... }
```
but the second rule is applied every time, no matter if i set another size to width.
I tryed to print withou printjs, and it works.
i cant figure out why. any help will be great.
if you need more info, tell me.

**Comment by xingguo3** [comment]
@RodrigoDLopez  hi, I have the same problem that @media is not applied when using printjs, May I know how you solved it?
In my case, I want to add page break:
`@media print {
  .pagebreak {
    page-break-before: always;
    page-break-after: always;
  }
}`
