### ISSUE TITLE
What's the best way to print at a certain screen size?

### ISSUE THREAD

**Issue by choldgraf** [crabbly/Print.js#366]
This is a really useful tool - thanks!

I have a few CSS rules that are only applied on larger screens. I'd like these rules to be applied when I print to PDF, but I haven't found a way to do something like "print the page, but with a screen size of XXX". Is there any way to make sure that the right CSS rules are triggered based on screen size when I print?

**Comment by bartolomeukuma** [comment]
i'm having the same trouble here...
my issue was open for six days, and nobody answer.
let see your issue now.

**Comment by ProAnderson** [comment]
My issue might be related to yours: [https://github.com/crabbly/Print.js/issues/367](https://github.com/crabbly/Print.js/issues/367)

**Comment by crabbly** [comment]
Hey guys, sorry for the delay. I haven't had much time to work on this library. Any help is appreciated. 

Please try using CSS media queries (`@media print {...}`). 
The library will pass that into the print job, therefore, you should be able to control how your HTML is supposed to be printed.

I'm closing this in favor of #367. If the media query doesn't fix the problem, let's continue this conversation there. I'll try to be more responsive. Hopefully others can help as well.
Thank you.
