### ISSUE TITLE
Viewport Size When Printing

### ISSUE THREAD

**Issue by ProAnderson** [crabbly/Print.js#367]
Hello, this is more of a question than it is an issue (but maybe it could be an issue):

Right now when I print from a mobile device or when simulating a responsive interface (using Bootstrap 4.x) in browser developer tools, is the default behavior to replicate the viewport window size in the print job? I've attached two print jobs of the same view with one being the mobile size (Small), and the other being the full browser size (Full). If my project requires it, how would I get my application to print the full browser size by default?

[Grammar Tools Mobile Beta Small.pdf](https://github.com/crabbly/Print.js/files/3576762/Grammar.Tools.Mobile.Beta.Small.pdf)
[Grammar Tools Mobile Beta Full.pdf](https://github.com/crabbly/Print.js/files/3576763/Grammar.Tools.Mobile.Beta.Full.pdf)

**Comment by bartolomeukuma** [comment]
any knews about this issue?

**Comment by crabbly** [comment]
Hey guys, I didn't know of this issue. @ProAnderson thanks for reporting this.

I really don't know why this happens. Hopefully we can figure it out and improve the library.

Did you get this in IOS or Android? Both? What browser(s)?

**Comment by ProAnderson** [comment]
I can get it to replicate using Chrome dev tools using the mobile viewport simulation: https://developers.google.com/web/tools/chrome-devtools/device-mode

Same thing on Firefox Responsive Design Mode. Here's the latest Firefox nightly output from my latest test.

**Comment by crabbly** [comment]
Interesting. This may be related to your CSS. I just tested the documentation page, and the HTML prints the same between desktop and mobile simulation, in Chrome on Mac.

Could you please test on your side to see if the documentation page behaves the same as the tests you posted?
https://printjs.crabbly.com

I did however, noticed that PDF print is not working when emulating mobile. Looks like there is a browser incompatibility with PDF on mobile Chrome. In fact, mobile print in general is quite an issue. For reference, we are tracking browser support in #33.

**Comment by ProAnderson** [comment]
Thanks, I'll give media queries a try.
