### ISSUE TITLE
onPrintDialogClose does not work on mozila

### ISSUE THREAD

**Issue by PedroS5499** [crabbly/Print.js#368]
onPrintDialogClose does not work on mozila.
When user closes tab with print document, don't trigger calback

**Comment by didagu** [comment]
Which version of Mozilla are you using?

**Comment by t-walker-wei** [comment]
onPrintDialogClose also not work for me.
Mozila 69/Chrome 76.0.3809.132
jQuery:1.12.4
print.js:1.0.61

**Comment by crabbly** [comment]
This is a tricky feature. The issue with Firefox is a known issue, there is a comment line in the implementation here:
https://github.com/crabbly/Print.js/blob/master/src/js/functions.js#L80

I'll go over this logic whenever I have a chance. PRs are welcomed :)

**Comment by dbathlon** [comment]
I have also a problem with the onPrintDialogClose but it's a different problem. 
The callback function is executed **before** the print dialog opens. In the callback function there's an ajax call with a window.location.replace, so I never see the dialog unless I comment out the callback.
Here's how i call the printjs, I hope there's nothing wrong with it.
`printJS({
        printable: 'print',
        type: 'html',
        css: '/stylesheets/print.css',
        ignoreElements: ['button', 'namefields'],
        onPrintDialogClose: redirect()
    });`

**Comment by juansss** [comment]
> I have also a problem with the onPrintDialogClose but it's a different problem.
> The callback function is executed **before** the print dialog opens. In the callback function there's an ajax call with a window.location.replace, so I never see the dialog unless I comment out the callback.
> Here's how i call the printjs, I hope there's nothing wrong with it.
> I tried Mozilla and Chrome.
> `printJS({ printable: 'print', type: 'html', css: '/stylesheets/print.css', ignoreElements: ['button', 'namefields'], onPrintDialogClose: redirect() });`

Hi!
When you use redirect() you are calling the function instantly.
You should use redirect without "()", thats the way to pass the function

**Comment by crabbly** [comment]
This seems to be working fine with the latest version of Firefox. However, the same issue is currently happening when using Chrome on Windows (on MacOS it works fine). I'm closing this issue in favor of #348. If you are still having problems with Firefox or Chrome, please follow / use that thread instead. 
Thank you.

**Comment by crabbly** [comment]
@dbathlon You code will run the function right away, as mentioned by @juansss. You can use a constant to hold the function definition, and pass the constant as the callback. Another option is to pass an anonymous function that calls your redirect. Ex.:

```js
onPrintDialogClose: () => redirect()
```

Hope this helps.

**Comment by dbathlon** [comment]
> @dbathlon You code will run the function right away, as mentioned by @juansss. You can use a constant to hold the function definition, and pass the constant as the callback. Another option is to pass an anonymous function that calls your redirect. Ex.:
> 
> ```js
> onPrintDialogClose: () => redirect()
> ```
> 
> Hope this helps.

Thx for your help. I haven't tested it because I don't need the function anymore.
