### ISSUE TITLE
Print doesn't support text-decoration: 'line-through' property

### ISSUE THREAD

**Issue by KaroseLiu** [crabbly/Print.js#37]
When I add the css style in the print text like the title said text-decoration: 'line-through' , It doesn't work.

**Comment by crabbly** [comment]
@KaroseLiu I didn't know about this, thx for pointing it out. I'll take a look and try to find a fix for it.

**Comment by crabbly** [comment]
Hey @KaroseLiu , I added support for text-decoration with the latest release.
https://github.com/crabbly/Print.js/releases/latest
Thank you.
