### ISSUE TITLE
 onclick="printJS('printJS-form', 'html')" not showing print prv

### ISSUE THREAD

**Issue by jecfarolan360** [crabbly/Print.js#370]
Hello. I have issue on printJS because the print preview doesn't show.

`<button type="submit" class="btn btn-success btn-fill pull-right" id="form-button-add" name="form-button-add" onclick="printJS('printJS-form', 'html')">
                    CREATE 
                </button>`

`<div id="printJS-form">
      <h1>Print This Section Only</h1>
    </div>`

I used Laravel framework and printJS

**Comment by creativeJoe007** [comment]
Same here

**Comment by crabbly** [comment]
Hey guys, not a lot of information to work with here. Please try adding an event listener instead. Something like `document.getElementById("form-button-add").addEventListener("click", printJS('printJS-form', 'html'))`. I would recommend creating your own print method to encapsulate the `printJS` call, giving you that layer of customization and control. 

Also, make sure the library is loaded. I'm not sure if you are using the CDN, downloaded build or importing the npm package. Just make sure the lib is actually available in your component or browser environment.

If you still can't figure it out, please reopen this ticket with more information. Hope this helps.
