### ISSUE TITLE
HTML Imports Deprecated

### ISSUE THREAD

**Issue by TheOwnerIs** [crabbly/Print.js#373]
Hi guys,

I guess you're aware about this? HTML Imports is deprecated and will be removed Feb. 2020.

https://www.chromestatus.com/features/5144752345317376

Thanks for the script ;)

Cheers,
Henrik

**Comment by crabbly** [comment]
Hey @TheOwnerIs, thanks for reporting this. I don't think we are using this feature in the library. If I'm wrong, could you please point it out in the code base?
Thank you for your help.

**Comment by crabbly** [comment]
Closing this issue as I don't think it applies to the library. We are not using html imports. Feel free to reopen if necessary. Thank you.
