### ISSUE TITLE
Styles not loaded initially

### ISSUE THREAD

**Issue by Mashiane** [crabbly/Print.js#378]
Hi there

I'm using excel css files with scanStyles on also. Sadly I have to run it multiple times before the styles are loaded. Is there perhaps a way to set a wait period until all the css are loaded and the scanStyles is finished before executing the print?

Both printThis.js and JQuery.print.js have these features and work well with the exception that they dont keep some of my element formatting whilst your lib does.

Ta!

**Comment by melancholyfleur** [comment]
I am having a similar issue: we have a few fonts that we are trying to apply to what we want to print with Print.js and they aren't loading before the print dialog renders. It would be nice if there was a way to wait until it's all loaded, or to apply preloaded CSS.

**Comment by crabbly** [comment]
Hey guys, when it comes to fonts, if the external CSS is trying to load a font on its own, print.js won't know when the font is loaded. At least not at this moment. I'm not sure how we could handle this. Take a look at this ticket, it may be a duplicate:
https://github.com/crabbly/Print.js/issues/285

@Mashiane I'll take a better look at how we can improve external stylesheets preload.

**Comment by crabbly** [comment]
Closing this in favor of #285.
