### ISSUE TITLE
download option

### ISSUE THREAD

**Issue by nuketownhf** [crabbly/Print.js#379]
Hello,
is there any option to let the user download the pdf?

thanks

**Comment by crabbly** [comment]
Hey @nuketownhf, 

The library doesn't not offer a download option. Its focused on printing only.

If you already have the PDF on the server side, you can accomplish this very easily setting the response header from the server. If you are trying to get a PDF file from HTML, images or JSON, there are a few Javascript libraries that may accomplish that. Unfortunately, I personally don't use any to recommend.

Hope this helps.
