### ISSUE TITLE
Repeatable Page Header and Footer

### ISSUE THREAD

**Issue by s-nadesh** [crabbly/Print.js#38]
Hi, 

How to use repeatable page headers and footers for all the pages ?

Kindly help me. 

Thank you.

**Comment by crabbly** [comment]
Hey @s-nadesh , the library does not have this feature. Are you trying to add this when printing html or json?

**Comment by s-nadesh** [comment]
Hi @crabbly , 

Thanks for your reply. 
I tried HTML table to PDF, Print content is displayed correctly, But I want repeatable headers and footers.

Thank you.

**Comment by crabbly** [comment]
Got it. Thanks for the info. Again, for now the library doesn't have this feature, but I'll consider adding it in the future.

**Comment by s-nadesh** [comment]
Okay. Thank you.

**Comment by PrabhuKathiresan** [comment]
Is this feature added? 

I want my header to be repeated in each page? Is it possible?

**Comment by crabbly** [comment]
I won't be implementing this feature, because of the limited time I have to work on this library. Hopefully someone else can implement and submit a PR in the future.
