### ISSUE TITLE
how the library imported in the asp.net? 

### ISSUE THREAD

**Issue by animalisme** [crabbly/Print.js#382]
My  code like `<script src="../../shell/Print/print.js" type="module"></script>`,and i got the error:GET http://localhost:14993/%E8%84%9A%E6%9C%AC/Print/functions net::ERR_ABORTED 404 (Not Found),
anyone can help me ?

**Comment by crabbly** [comment]
Hey @animalisme, looks like your path to the library file is invalid. Try playing with your `src` definition. If you can't figure this out, one option would be to use the CDN instead. 
You can get the CDN url on the documentation page: https://printjs.crabbly.com/#download
