### ISSUE TITLE
Versioning must be improved prior to releases

### ISSUE THREAD

**Issue by nthornton2010** [crabbly/Print.js#383]
This is probably not the correct place to put this so please let me know if there is a better place that I can leave this kind of feedback in the future.

I'm currently running v1.0.54 from last year. I had to reinstall this module and because only the patch version is updated and the minor version is never updated, a breaking change was pulled into my project.

https://github.com/crabbly/Print.js/blob/d905ef5bf08f4bd064aae4d0b3578b61a3263956/src/index.d.ts

In 1.0.54, the 'export = printJS;' at the bottom of index.d.ts was 'export default printJS;'. Changing this caused all the imports in my project to fail to compile.

When releasing versions, please increase the minor version number if breaking changes are being introduced. The patch version should only be increased if no breaking changes are introduced.

**Comment by crabbly** [comment]
Hi @nthornton2010 I completely agree. It was my mistake as I did not see the breaking changes. I also haven't had much time to support the library, very sorry.

About the interface, I may have accepted a PR. I don't have much experience with TypeScript yet, what do you recommend we do to fix the interface?

Thank you for your help.

**Comment by nthornton2010** [comment]
When researching both ways of exporting, the thoughts on each seems to be split. Some say using 'export default' is better and others say 'export =' is better. At the end of the day, they're both just different forms of syntax. If I were you, I'd leave it the way it is now. If you change it back, then anyone on a newer version will have the same problem I had and will have to change how they import it.

**Comment by crabbly** [comment]
Sounds good. Will leave it as is for now. Thank you.
Also, I will be more careful with the versioning moving forward.

Thanks again for your help!
