### ISSUE TITLE
Print local files

### ISSUE THREAD

**Issue by NbdyFamous** [crabbly/Print.js#384]
Hi, 

I'm working on a local HTML file on a shared drive (not a server) and would like to use print.js to directly print files on the share drive. (Making lives a little easier) Like the example index file provided on downloading print.js files, I just want to print pdfs on my local PC. Is this possible? I tried and clicking the button does nothing.

Thanks

**Comment by crabbly** [comment]
Yes, its possible. If you clone the library (this repository) into your machine, take a look at the manual test file we have. It probably does exactly what you are looking for. The issue will be probably how you are linking the files. As long you can view them in the browser, you can pass to the library to be printed. Hope this helps.
