### ISSUE TITLE
Iframe stays in the DOM after print job is finished

### ISSUE THREAD

**Issue by Helen1314** [crabbly/Print.js#387]
Hello, after printing，iframe is not destroyed?

**Comment by crabbly** [comment]
Currently, the library does not delete the iframe. But we already have a hook that could be used to clean it after the print is complete. A PR would be welcome.

**Comment by Helen1314** [comment]
> Currently, the library does not delete the iframe. But we already have a hook that could be used to clean it after the print is complete. A PR would be welcomed.

But 'position: absolute;' is risky.If body has no relative position, will cause the page to be blank. 
Can iframe‘s  positioning  be changed to relative ? Can you speak Chinese?

**Comment by crabbly** [comment]
Hey @Helen1314, I don't speak Chinese, sorry. 

I'm not sure having an absolute positioned element would break the page. Can you replicate?
Try using the index.html included in this repository.

**Comment by websrookie** [comment]
> Hey @Helen1314, I don't speak Chinese, sorry.
> 
> I'm not sure having an absolute positioned element would break the page. Can you replicate?
> Try using the index.html included in this repository.

Hello, after printing, when I hit cancel,the page is still blocked

**Comment by crabbly** [comment]
It doesn't sound like a CSS issue.

**Comment by websrookie** [comment]
> It doesn't sound like a CSS issue.

Can you look at my question? Thank you

**Comment by crabbly** [comment]
@websrookie What question?

**Comment by crabbly** [comment]
Iframe is now getting removed from the DOM once the print job is dispatched.
This change will be published to npm in the next release. Thank you guys.

**Comment by crabbly** [comment]
This change was published to npm with v1.5.0. Please run `npm update print-js` to get it. Thank you
