### ISSUE TITLE
window.print() no longer works after printing PDF

### ISSUE THREAD

**Issue by voluntadpear** [crabbly/Print.js#388]
On Chrome 78 (macOS) `window.print()` does nothing when the page is refreshed after printing a PDF.

Steps to reproduce the issue:

1. Go to http://printjs.crabbly.com/
2. Click "Print PDF" on the first example
3. Refresh the page
4. Open the JS console and run `window.print()`
5. The printing UI is not shown. Nothing happens

Another way to reproduce the issue:

1. Go to http://printjs.crabbly.com/
2. Click "Print PDF" on the first example
3. Click the button again
4. Open the JS console and run `window.print()`
5. The printing UI is not shown. Nothing happens

Thank you!

**Comment by crabbly** [comment]
Hey Guillermo, thanks for reporting this.

This is such an interesting behavior. Once we refresh the page, the library is loaded again with a clean DOM state. Not sure how the library would be the cause of such behavior.

**Comment by karanbedre** [comment]
facing the same issue as @voluntadpear mentioned.
if I print the pdf for several times and try again with printJs, preview is not showing up. 
After facing this error I tried with window.print() which is showing as undefined.

**Comment by calirvine** [comment]
@voluntadpear @karanbedre  @crabbly Did anyone ever figure this out? I am also experiencing this. I think it is actually a chrome bug, as I stopped importing the library into my project entirely and window.print still does not work (It was working fine before).

**Comment by crabbly** [comment]
Looks like this was a temporary issue with some versions of chrome. I just tested using the latest version of Chrome in Windows and MacOS and it working as expected. Feel free to reopen this if necessary. Thank you guys.
