### ISSUE TITLE
Cors issue in Android chrome for printing the base64 pdf

### ISSUE THREAD

**Issue by GopeshMedayil** [crabbly/Print.js#389]
Hi,
Thanks a lot for the awesome library.
I am using the base64 option to print the pdf.It is working fine in desktop chrome browser.But it is throwing a CORS error in mobile chrome browser.
Error i am getting is:
`ERROR DOMException: Blocked a frame with origin "http://localhost:4200" from accessing a cross-origin frame.`
i tried with `showModal:true`,but of no use. I am using Angular 8 for the development.
Please help on this.

**Comment by crabbly** [comment]
Hey @GopeshMedayil,
Mobile browser support is weak right now. Recently, I'm unable to print any PDF files on chrome mobile, including base64.

When I simulate mobile through my chrome desktop (dev tools), I'm able to replicate the issue.

This may be related to how we are handling the iframe document. Maybe we could start exploring how we can eliminate this error:

`Resource interpreted as Document but transferred with MIME type application/pdf: "blob:...`

**Comment by niftylettuce** [comment]
@crabbly 	I'd gladly donate to the project to get this fixed.  Let me know, niftylettuce@gmail.com.

**Comment by kneczaj** [comment]
I am not sure if this is the same issue.

I have a code like this:
```
const blob = await getPdfBlob(this.documentContent || '');
const pdfUrl = URL.createObjectURL(blob);
printJS(pdfUrl);
```

where getPdfBlob() is a function which uses `pdf(MyDoc).toBlob();` from `react-pdf` like described here `https://react-pdf.org/advanced`. This produces the following error on Android (but works for desktop Chrome):
```
Uncaught DOMException: Blocked a frame with origin "http://localhost:3000" from accessing a cross-origin frame.
    at performPrint (webpack://printJS/./src/js/print.js?:74:35)
    at HTMLIFrameElement.iframeElement.onload (webpack://printJS/./src/js/print.js?:26:9)
```

The url of the produced IFrame is like this:
`blob:http://localhost:3000/529369ea-291c-4b9a-b629-d646c36b53be`

**Comment by crabbly** [comment]
Unfortunately, mobile browser support is still quite weak due to different behavior between mobile and desktop browsers. I'll will close this is favor of #33. Let's keep that issue open until we cover all mobile browser issues. Thank you guys.
