### ISSUE TITLE
print view lost some backgroud color and gif image

### ISSUE THREAD

**Issue by zj2050** [crabbly/Print.js#39]
@Baransu 

i had add library in html + js project ,  add to head  like :
`
    <link href="mysets/print/css/print.css" type="text/css"/>

    <script src="mysets/print/js/print.js"></script>

</head>
`
but when call it in button click
`
    printJS('mainviewpanel', 'html')
`

it show error : Uncaught ReferenceError: printJS is not defined

whether it need initialize , and how to do it 

thanks

**Comment by Baransu** [comment]
You have to import file from `dist` folder, for example: `mysets/print/dist/print.min.js`

**Comment by zj2050** [comment]
@Baransu 

dist folder ?
but the file i download not the folder

thanks ,it caust by here
![errprintjs](https://cloud.githubusercontent.com/assets/4464947/25062806/b2848e74-2206-11e7-886a-608df6ea1aa3.jpg)

**Comment by zj2050** [comment]
thanks dist folder can work ,but it lost some elements

the real page like this:
![real](https://cloud.githubusercontent.com/assets/4464947/25062856/c06cbf7e-2207-11e7-92da-a9687ed33db5.jpg)

but print js preview like this:
![preview](https://cloud.githubusercontent.com/assets/4464947/25062863/df2700fa-2207-11e7-9946-13019ea53eee.jpg)

how to set opition to print the same like page show ?

thanks

**Comment by zj2050** [comment]
@Baransu 
it seems print js lost backgroud color and the red gif image

**Comment by crabbly** [comment]
Hey @Baransu , the library currently will not include the gif images in the html print. I will try to change this. About the background color, by default, when printing html pages, browsers won't include background colors for elements. I will also try to add support for this, but you would still have to change a setting in your browser to print the background colors.

**Comment by crabbly** [comment]
The library will print animated gifs without issues.
Here is a fiddle with an example: 
http://jsfiddle.net/crabbly/qnhbstxq/
