### ISSUE TITLE
It is possible to force PrintJS Firefox behavior in another browsers?

### ISSUE THREAD

**Issue by JavierSR** [crabbly/Print.js#390]
In Chrome (or any popular browser) I need to open the content in another tab before print (Like Firefox incompatibility). Apparently there is no way to parameterize this behavior with PrintJS tools, it just happens if browser  doesn't allow printing PDF documents using iframes. 

I would like there would be an option to open content in new tab instead getting the Ctrl + P interface directly. Otherwise I dont know if its possible to try to cheat navigator data to force Firefox behavior.

**Comment by crabbly** [comment]
Hey @JavierSR, 
Yes, just don't use Printjs for those PDF files. 

The default browser behavior is to open in a new tab. Printjs was created to overcome that, and instead, print the PDF without opening the new tab and requiring the user to hit the print button again, when viewing the PDF.

Please reopen this if I miss-understood your question. Thx.
