### ISSUE TITLE
dist/print.js is bloated with eval()

### ISSUE THREAD

**Issue by maisumakun** [crabbly/Print.js#391]
In 1.0.63, code in `dist/print.js` ( [see from unpkg](https://unpkg.com/browse/print-js@1.0.63/dist/print.js) ) contains `eval()`.

It seems some build settings of Webpack might be inaccurate for distribution build.

**Comment by crabbly** [comment]
Hey @maisumakun, this doesn't sound good. I'll take a look at it. Any ideas on how we can fix this?

**Comment by natalan** [comment]
@crabbly did you run `npm run production` for 1.063 or `npm run development`? `eval` must be coming from `development` build

**Comment by natalan** [comment]
Anyway, I just submitted a PR here to set [devtool](https://webpack.js.org/configuration/devtool/#devtool) to `source-map` in dev builds.

**Comment by crabbly** [comment]
Sorry for the delay guys. I thought I used the `production` flag. But maybe I messed this up. 
I just merged your PR. Will run a few manual tests and try to publish a new version as soon as possible.

**Comment by crabbly** [comment]
Closing this since these changes were deployed to npm. Latest version is currently v1.1.0. Thank you.
