### ISSUE TITLE
React use Print.js print components

### ISSUE THREAD

**Issue by pingmouren** [crabbly/Print.js#395]
![image](https://user-images.githubusercontent.com/44625220/70206643-28af4e00-1763-11ea-8b0e-581d9158c03c.png)
i want to print this react components. print.js can not use jsx. what should i do

**Comment by yingzk** [comment]
you can try this:

`ReactDOMServer.renderToString`

**Comment by crabbly** [comment]
Print.js is targeting DOM rendered elements, therefore, it doesn't necessarily care if you use react, vue or any other framework to build your UI. 

That could be an interesting topic to explore in the future, but for now, just add ids to your HTML elements that you want to print using the lib, and you should have no issues when dispatching your print jobs.

Hope this help.
