### ISSUE TITLE
Javascript version for 1.0.63

### ISSUE THREAD

**Issue by DarrBuck** [crabbly/Print.js#396]
For version 1.0.61 you were able to download the straight JavaScript version.

![snip_20191206082205](https://user-images.githubusercontent.com/28006538/70300909-86927300-1801-11ea-8f4e-0b85f174791a.png)

Could you please do the same for 1.0.63
(or how does one create it from this file)
Is the CDN version 1.0.63?

![snip_20191206082433](https://user-images.githubusercontent.com/28006538/70301031-e4bf5600-1801-11ea-9faf-6069c82b3816.png)

Thanks

**Comment by amy19900919** [comment]
when i load the print.min.js in chrome , the css arrtibute is not work ? like this:
printJS({
			printable:'view-form-pc-print',
			type: 'html', 
			scanStyles: false,
			documentTitle: ''
		});

**Comment by crabbly** [comment]
Hey guys, sorry for the long delay. I haven't been able to put much time into the lib for a while. A new version got released this week, v1.1.0 which contains the latest builds
https://github.com/crabbly/Print.js/releases/tag/v1.1.0

I would recommend using the npm package tough.
https://www.npmjs.com/package/print-js

Hope this helps.
