### ISSUE TITLE
default export source vs type definition

### ISSUE THREAD

**Issue by william-lohan** [crabbly/Print.js#398]
There maybe a discrepancy between the source js and type definition

source:
https://github.com/crabbly/Print.js/blob/54d84af0a726708efc92ec4ef340bb7b6c20cf84/src/index.js#L10

ie import like `import printJS from 'print-js';`

type definition:
https://github.com/crabbly/Print.js/blob/54d84af0a726708efc92ec4ef340bb7b6c20cf84/src/index.d.ts#L42

This definition causes Typescript environments without  `allowSyntheticDefaultImports` to be required to import like `import * as printJS from 'print-js';`

**Comment by crabbly** [comment]
Hey @william-lohan, I accepted that interface in an PR a long time ago, not a fan of the namespace setup and export. I'm planning on releasing the next version of the lib in Typescript with an updated interface. However, in the meantime, I haven't experienced the same problem. I'm currently using the lib in a Typescript project where we didn't need to set `allowSyntheticDefaultImports`, and the import worked as expected.

Also, here is a codesandbox for a Typescript project importing the lib as expected, without adding `allowSyntheticDefaultImports` to its tsconfig. 
https://codesandbox.io/s/printjs-typescript-import-kw2po?file=/src/index.ts

I'll close this for now but feel free to reopen if necessary. A PR updating the current interface is welcomed, as long its backwards compatible. I hope we can release v2 sooner than later, with full Typescript support.
Thank you.
