### ISSUE TITLE
Any way to set "withCredentials" argument?

### ISSUE THREAD

**Issue by hms5232** [crabbly/Print.js#399]
I need to send request with credentials. The following  is what we coding:

````
printJS({
    printable: this.url,
    type: 'pdf',
    showModal: true,
    modalMessage: 'Generating File...',
    onPrintDialogClose: () => this.reload() 
});
````

But I can't find any argument to implement this.
We try to edit `src/js/print.js` and add `withCredentials = true`, then works. A part of codes from https://github.com/0verseas/Print.js/commit/3fbe62d0860416ede9a11bc608298de581dc0eec :
```
    // Get the file through a http request (Preload)
    let req = new window.XMLHttpRequest()
    req.responseType = 'arraybuffer'
    req.withCredentials = 'true';
    req.addEventListener('load', () => {
      // Check for errors
      if ([200, 201].indexOf(req.status) === -1) {
```
Is there any way or argument to setting  request with credentials?

**Comment by crabbly** [comment]
Hi @hms5232, just fetch the pdf contents first using whatever HTTP client you prefer, where you have full control over the request headers. You can then pass the pdf contents as a base64 or blob url to the library to dispatch the print job.

The documentation page has a working example printing a base64 pdf.
https://printjs.crabbly.com/
