### ISSUE TITLE
Add header each printing page except first page

### ISSUE THREAD

**Issue by Shankar1430** [crabbly/Print.js#401]
I need to add header for each page except first page.

I am not able to find a solution through this. Please give me a solution for this issue.

**Comment by gharibi** [comment]
Currently we don't have this functionality. However, [THIS](https://github.com/crabbly/Print.js/pull/393) may help you out.

**Comment by crabbly** [comment]
The library does not offer header customization per page number. A PR would be welcomed. Thank you.
