### ISSUE TITLE
how to add authorization token in request?

### ISSUE THREAD

**Issue by funnyconteo** [crabbly/Print.js#402]

**Comment by gharibi** [comment]
Could you provide more information?

**Comment by ecyrbe** [comment]
How can someone call an api that need a token in the header, like a bearer token :
`authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c`

**Comment by crabbly** [comment]
Hi @funnyconteo, just fetch the pdf contents first using whatever HTTP client you prefer, where you have full control over the request headers. You can then pass the pdf contents as a base64 or blob url to the library to dispatch the print job.

The documentation page has a working example printing a base64 pdf.
https://printjs.crabbly.com/
