### ISSUE TITLE
Can I append several pages and print everything?

### ISSUE THREAD

**Issue by hchauvat** [crabbly/Print.js#403]
Hi, 

I'm looking for a clever way of printing several pages in one click. Let me explain:

I have this page that shows a bunch of information. At the top of it, there are 3 buttons, that each leads to another part of information. For example: 

```javascript
website/result            // this is were the 'Print' button would be located and the first part of the stuff we want to print
website/result/more       // part 2/3 of what we want to print
website/result/advanced   // part 3/3 of what we want to print
```

Does Print.js provide something like this? Or do you guys know of anything that could help me achieve this?

Thanks a lot for your help!

**Comment by crabbly** [comment]
Hi @hchauvat, the library doesn't support multiple pdfs. We can either use another lib to merge the files first, or use a server side solution (API) before dispatching the print job. Thank you.

**Comment by crabbly** [comment]
Ref.: #462, #458, #215
