### ISSUE TITLE
Print.js not working with android webview

### ISSUE THREAD

**Issue by persano** [crabbly/Print.js#406]
Hi!

I'm developing a PWA for a computer wholesaler and recently added the print.js library to the website. It makes an excellent job even in mobile. But when i try to use it in the android PWA i developed it never triggers any functionality or error. 

I load the site in a webview and handle everything, like deeplinking, push notification and redirections. Maybe you can give a hand so i can finally make this work, because i m proud of what i did and it would be a shame for me if i cant get it to work in the app.

**Comment by crabbly** [comment]
Unfortunately, mobile browser support is still quite weak due to different behavior between mobile and desktop browsers. I'll will close this is favor of #33. Let's keep that issue open until we cover all mobile browser issues. I hope we can improve this soon. Thank you for reporting this.
