### ISSUE TITLE
If the html has img tag and has a image URL it does not print

### ISSUE THREAD

**Issue by AtulGhodke** [crabbly/Print.js#408]
I am trying to print raw html and html contains img tag with image URL . 
When i am sending a request to print html it does not showing any error in browser console but it showing the cancelled status for print.min.css and image in browser network and it does not print the html.
![cancel-request](https://user-images.githubusercontent.com/19547092/73276200-51f1d500-420e-11ea-9d56-b3bdba065333.png)

**Comment by crabbly** [comment]
This has been fixed. Please run npm update to get the latest version of the lib. Thank you.
