### ISSUE TITLE
Add Custome Css in NuxtJS

### ISSUE THREAD

**Issue by N0SYS73M1SS4F3** [crabbly/Print.js#410]
I tried to `customer Css` by following `printJS({
					printable: "printPOS",
					type: "html",
					scanStyle: false,
					css: "../../assets/css/print_pos.scss",
				});`

I got an error `http://127.0.0.1:3000/assets/css/print_pos.scss` not found!!

Is there a way to fix it?? Thanks in Advance...

**Comment by MLDMoritz** [comment]
create file assets/css/print_pos.scss

**Comment by N0SYS73M1SS4F3** [comment]
@MLDMoritz  i already created it..

**Comment by crabbly** [comment]
Hey @N0SYS73M1SS4F3, the library expects a public url for the compiled css. It doesn't work with local sass files. Just pass the compiled stylesheet relative path (or a variable with the dynamically created url string) to the lib so it can find your css at runtime in the browser environment. Remember, the print job won't get initiated on the server side, but instead, on the user's browser. Feel free to reopen this if any other issue. Thanks.
