### ISSUE TITLE
How to limit printing only once?

### ISSUE THREAD

**Issue by xianghongai** [crabbly/Print.js#411]
Awesome print kit!
The only question is, can it add a feature to limit the number of prints?

**Comment by crabbly** [comment]
@xianghongai, The library is using functional style and it doesn't not save any state. You can just add a counter to your code to track the number or print jobs being triggered, then disable the call to printjs after the first print job is dispatched (or any limit / number of jobs you choose). Should be a pretty straight forward implementation. Hope this helps.
