### ISSUE TITLE
Send rawhtml header

### ISSUE THREAD

**Issue by Jeffunez** [crabbly/Print.js#412]
Hi!! I try to use a standard header in my application. In the documentation it says that I can use a normal text or a raw html but when I place a raw html string this literal printout is not the expected randerization. 
this is my settings:
```
      printJS({ printable: 'export_id' 
      type: 'html', 
      header: '<h3 class="custom-h3">My custom header</h3>',
		  style: '.custom-h3 { color: red; }',
      targetStyles: ['*'],
      maxWidth: 1200,
      ignoreElements: ['ignore1', 'ignore2', ]
    });
```

It would help me a lot if I could add a more structured header to place whatever I need for example:

  printTest() {
    if (this.config) {

>       var title = "<img _ngcontent-ssm-c209='' alt='' src='https://via.placeholder.com/300'><div _ngcontent-ssm-c209='' class='textos'><h1 _ngcontent-ssm-c209=''>  title here </h1><h3 _ngcontent-ssm-c209=''> Subtitle here </h3></div>"

      var viewtoIgnore: string[] = this.config.ignoredElements;
      var setMaxWidth: number = this.config.maxWidth;
      printJS({ printable: this.config.idSelector, 
      type: 'html', 
      header: title,
      targetStyles: ['*'],
      maxWidth: setMaxWidth,
      ignoreElements: viewtoIgnore
    });
    }
  }

then I could have something like that header

"<img _ngcontent-ssm-c209='' alt='' src='https://via.placeholder.com/300'><div _ngcontent-ssm-c209='' class='textos'><h1 _ngcontent-ssm-c209=''>  title here </h1><h3 _ngcontent-ssm-c209=''> Subtitle here </h3></div>"

Thank you!!

**Comment by crabbly** [comment]
Hi @Jeffunez, instead of using `targetStyles`, try passing your style sheets using the `css` property. Or any custom style using the `style`. I hope this helps.
If you are still having issues, please create a fiddle (codepen, codesandbox or similar) and reopen this issue.
Thank you.
