### ISSUE TITLE
Custome Css Not Working In IE/Edge

### ISSUE THREAD

**Issue by gowrisankarreddy** [crabbly/Print.js#414]
Hi Guys,

I am tried this

 **printJS({ printable: 'myDIV1', type: 'html', header: 'PrintJS - Form Element Selection',
       css:['../../../assets/forms_main/css/formhub.css','../../../assets/Print/print.css'] 
     })** 

Its Working Fine in Chrome.
Same url Run in IE/Edge its printing only html not loading CSS.

Could you please suggest me to fix this.

I am using printjs version **https://printjs-4de6.kxcdn.com/print.min.js**

**Comment by olyamosunova** [comment]
Did you correct this mistake?

**Comment by crabbly** [comment]
@gowrisankarreddy The CDN version is outdated. We are probably not going to be updating that moving forward, and deprecate it all together. Please use npm or download the latest release version from here: https://github.com/crabbly/Print.js/releases

The latest version should be working as expected in Edge. Feel free to reopen this issue if necessary.
