### ISSUE TITLE
Npm version pollutes global namespace

### ISSUE THREAD

**Issue by dapetcu21** [crabbly/Print.js#42]
It's common practice to export the module when used from npm rather than affixing it to the global object.

This should work:

```js
import printJS from 'print.js'
printJS()
```

This should also work:

```js
const printJS = require('print.js')
printJS()
```

This is not ok:

```js
import 'print.js'
window.printJS()
```

**Comment by crabbly** [comment]
Yea, for sure. Fixed it with commit 163548d
Thank you @dapetcu21
