### ISSUE TITLE
text color not work

### ISSUE THREAD

**Issue by yethuaungptu** [crabbly/Print.js#420]
printJS({
                  printable: 'printArea',
                  type: 'html',
                  css:['/stylesheets/style.css','/bower_components/bootstrap/dist/css/bootstrap.min.css',
'/bower_components/font-awesome/css/font-awesome.min.css',],
                  targetStyles: ['*'],
                  style: '#printArea *{color:red}',
                  scanStyles : true
                });

**Comment by crabbly** [comment]
Just remove the `*` from the code above, that's not a valid css syntax. 
Ex.: `#printArea {color: red;}`
