### ISSUE TITLE
Print image on rotated page

### ISSUE THREAD

**Issue by stummer** [crabbly/Print.js#421]
Images are scaled for printing to use 100% of the page width.

If you print a landscape image with an aspect ratio of (3:2) and you switch the page to landscape in the print dialog, the image wil be printed on 2 pages; the second one contains a small stripe of the bottom of the image.

Is there an option/style to shrink the image to fit into the page, redardless of the page's orientation?

**Comment by jcnventura** [comment]
I created issue #434 to ask for such options.

**Comment by crabbly** [comment]
Hi @stummer, the library has two options to customize the image layout, passing raw styles with the `style` property, or entire stylesheets with the `css` property.
https://printjs.crabbly.com/#configuration

Hope this helps.
