### ISSUE TITLE
Possible enhancement?

### ISSUE THREAD

**Issue by jiferrero** [crabbly/Print.js#423]
Hi, 

We just trying your awesome library with our company tool ... Although you primary written the library to print PDF files directly, you have the option to print from a base64 string encoded so our question is if it is possible to slightly modify the library to also admit the raw binary to avoid the over load of encoding to base64 because later your library just decode it again in pdf.js print() method .... 
Something like a parameter to bypass it or adding the option of "raw" or "binary" instead "base64"

Thank you so much again for your wonderful library.

Best Jose

**Comment by crabbly** [comment]
Hi Jose, yes I don't see a problem with adding a `binary` property to the lib API if it's going to eliminate unnecessary processing for some cases. I haven't had much time to support the lib, therefore I'm currently focusing on bugs and won't implement this change at this moment. A PR would be very welcomed though. Thank you.
