### ISSUE TITLE
PrintJS function is add extra space in base url which is causing problem.

### ISSUE THREAD

**Issue by huzailjamil** [crabbly/Print.js#427]
I'm trying to use on printJS function but i'm seeing an extra space in the url which is why function is not able to find my file also when i gave full path it is adding base url and then add the path from public i'm using this on laravel.
![image](https://user-images.githubusercontent.com/30392631/79632081-79559f80-8176-11ea-8c19-84761b19ee91.png)
as you can see there is clearly a  space in link

**Comment by crabbly** [comment]
Hi @huzailjamil, this space is probably coming form outside the lib. The documentation page has examples using relative paths without any issues. You can also pass the full url to the lib, and it won't make any changes to it. 
If necessary, please reopen this and post the actual code you used to create the print job. Thank you.
