### ISSUE TITLE
Adding style OnClick option but It is not working.

### ISSUE THREAD

**Issue by maverickdeepak** [crabbly/Print.js#430]
```
<input type="" class="btn btn-warning" value="PRINT LABEL" onclick="printJS({'hiddenContent',
'html', targetStyle:['width:200']})">
```

When I am adding this code then it showing issues to me. i.e Uncaught SyntaxError: Unexpected token ','

**Comment by crabbly** [comment]
Hi @maverickdeepak, the target style should use `width` only. However, I believe you are trying to pass a custom style instead. For that, you can use the `style` or `css` properties.
https://printjs.crabbly.com/#configuration
