### ISSUE TITLE
Should print.js now work in Firefox because the Bug 911444 is fixed?

### ISSUE THREAD

**Issue by robbterr** [crabbly/Print.js#431]
Hi, 

i have seen Firefox closed the mentioned bug on the print.js website. 
Its already in the current release version 75.

https://bugzilla.mozilla.org/show_bug.cgi?id=911444

br Robert

**Comment by JonLaliberte** [comment]
@robbterr It doesn't seem to work, but I haven't looked at the code myself yet. My assumption is that for FF there is a branch to workaround the bug that only checks FF, not the version...

I had added a comment regarding this here as well: https://github.com/crabbly/Print.js/issues/33#issuecomment-620816499

**Comment by JonLaliberte** [comment]
Here: https://github.com/crabbly/Print.js/blob/54d228ae6d1517e5c99911521537c72b1b0f69f0/src/js/init.js#L130

Again, haven't tested removing this, so not sure if it'll work.
The correct fix would need to take in to account firefox release.

**Comment by robbterr** [comment]
if i remove hte isFirefox() check, i doesnt work and i get the same bug/error like here: 
https://bugzilla.mozilla.org/show_bug.cgi?id=911444#c103

"Warning: The PDF is not fully loaded"

**Comment by galzetta** [comment]
@robbterr From what I've read in the mozilla thread you cannot expect print.js to just drop the check & work.
First of all the FF fix does not handle the display: none case. Moreover apparently it does not work if the iframe has size 0, so basically you need to use a big iframe that is non visible (probably absolutely placed far away).

Finally it appears that there are some issues with loading time of the data, so the print.js library should do something to wait the data to actually load (which means triggering the print after the onload event in the iframe (actually I think you also have to add further delay).

IMHO checking this fix should be a priority for the maintainers since this is a big limitation in a major browser and we might finally get rid of this. I can tell you there are plenty of inhouse webapps that force whole businesses to use Chrome just because it was impossible to handle printing in a sane way in Firefox (think any kiosk stuff where the process involves printing anything).

**Comment by timdown** [comment]
I've had a brief play with printing PDF in current Firefox (version 80). My findings so far:

- An extra delay after the iframe element's load event is required. For a small PDF on my modern PC, 1000ms was enough but 100ms was not. I have not further information (yet) on what is a reliable delay.
- I'm pretty sure at least some of the PDF has to be visible for printing it to work. Hiding using CSS `display` or `visibility`, or via positioning the iframe outside of the visible page area using absolute positioning or `transform`, does not work ("The PDF is not fully loaded for printing" in most cases).
- Keeping the iframe visible and setting `opacity: 0` works.
- After the call to the iframe window object's `print()` method, removing the iframe element immediately or even after a brief delay results in the printing dialog to hang indefinitely. However, things are fine if you hide the iframe using any of the previously-mentioned methods at this point.

I think I have a workable solution for my needs using the following:

1. Display the iframe in the visible area of the page with a reasonable size to ensure some of the PDF document other than its toolbar is visible. 80px high seems to be enough. I'm not sure there's any reason to restrict it to that though.
2. Make the iframe invisible to the user using `opacity: 0`.
3. Once the iframe's `load` event fires, wait for some interval (I'll need to experiment with larger PDFs to pin this down) before calling `print()` on the iframe's window object
4. After the `print()` call, set `display: none` on the iframe.

**Comment by timdown** [comment]
I realised I didn't need all of Print.js for my case and created a gist using the method from my previous comment:

https://gist.github.com/timdown/cfacd32f6b5e439bb02aaf142343ce4c

**Comment by timdown** [comment]
I could create a PR for this project if there's interest?

**Comment by perifer** [comment]
Thanks for this @timdown , I will give it a try. 

Off-topic: https://github.com/crabbly/Print.js/issues/431#issuecomment-692662903 is also something I thought about. Although the lib is small, it's would be nice to just be able to use exactly what you need, which in my case also is the cross-browser print functionality.

**Comment by JonLaliberte** [comment]
@timdown Thanks for this!
[Over here](https://github.com/crabbly/Print.js/issues/417#issuecomment-689306070) @crabbly mentioned he'd welcome a PR for a fix for FireFox.

**Comment by timdown** [comment]
More research needed. I don't think setting `display: none` straight after the `print()` call is as safe as it first seemed.

I'll create a PR once I'm convinced it's working.

**Comment by crabbly** [comment]
A new version was published to npm with support for PDF printing in Firefox. Please run npm update to get it (v1.3.0).
Thanks to @timdown for the PR!
