### ISSUE TITLE
"n.onPdfOpen is not a function"

### ISSUE THREAD

**Issue by DarthSonic** [crabbly/Print.js#435]
I get "n.onPdfOpen is not a function" when trying to inject javascript to non-compatible Firefox browser (v76, win10). 

Should it be possible to inject "window.print()" to "onPdfOpen"?

**Comment by crabbly** [comment]
Hi @DarthSonic, sounds like the code you are passing as a callback is not a function. Just pass a proper function and you should be good to go. Here is an example:
https://github.com/crabbly/Print.js/blob/master/test/manual/index.html#L22
Hope this helps.
