### ISSUE TITLE
Prevent opening the print modal on Windows

### ISSUE THREAD

**Issue by jablonskipj** [crabbly/Print.js#437]
Is there a chance to force the library to use the default printer without opening the print modal on Windows? I want the print process to be faster and because of that it should use the default printing settings (or predefined in the params) and run the print process without forcing the user to interact with the print dialog.

**Comment by crabbly** [comment]
Hi @jablonskipj , that wouldn't be possible for security reasons. More details can be found in previous questions / issues on this repo. Good luck.
