### ISSUE TITLE
Uncaught DOMException: Blocked a frame with origin "https://printjs.crabbly.com" from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by raymond8080** [crabbly/Print.js#438]
I am getting an error when attempting to access the a webpage this week, using Chrome browser, Version 81.0.4044.138 (Official Build) (64-bit)

Previously, it is working. I doubt that Chrome has done some update blocking it to work.
The same error can be simulated at https://printjs.crabbly.com/ by clicking first example "Print PDF"

Uncaught DOMException: Blocked a frame with origin "https://printjs.crabbly.com" from accessing a cross-origin frame.

**Comment by quentin-decre** [comment]
Same problem here !

**Comment by crabbly** [comment]
Hey guys, I'm using the latest version of Chrome, currently version 85, and it seems to be working fine. Hopefully this was a temporary issue with v81. If necessary, please reopen this with the browser version and OS. Thank you.

**Comment by sreiterer** [comment]
Hi, i think the problem is back. The previous weeks it worked fine, but now i get the cors problem:


The problem can easily reproduced by clicking on the 'Print PDF' button at https://printjs.crabbly.com/:

`print.js?v1.5.0:1 Uncaught DOMException: Blocked a frame with origin "https://printjs.crabbly.com" from accessing a cross-origin frame.
    at u (https://printjs.crabbly.com/print.js?v1.5.0:1:4095)
    at HTMLIFrameElement.n.onload (https://printjs.crabbly.com/print.js?v1.5.0:1:5017)`

Chrome version: 86.0.4240.75 (32 bit)
Windows version: Windows 10 Pro (1909)

**Comment by moyuanhuang** [comment]
Hello, any update on this issue?

**Comment by shahdeep1989** [comment]
@crabbly I am using Version 91.0.4472.77 of chrome still facing same issue.

Error: SecurityError: Blocked a frame with origin "http://localhost:3000" from accessing a cross-origin frame.

<img width="946" alt="Screenshot 2021-06-09 at 12 14 21 PM" src="https://user-images.githubusercontent.com/8403716/121306303-4ba05c80-c91c-11eb-828b-b0f9f27c837c.png">

**Comment by quarryman** [comment]
The same issue for me, but it probably depends on browser. It works perfectly on Edge or on chrome on anther machine

**Comment by bartello1982** [comment]
same here

**Comment by tbroniewski** [comment]
The problem still exists. I'm afraid it is due to more restricted security in browsers (against iFrames).
