### ISSUE TITLE
POST request from printJS

### ISSUE THREAD

**Issue by aishwaryshukla** [crabbly/Print.js#442]
I have a query. Is it possible to make a post request from printJS? If yes then, how to do it? If no the, is there a way to tweak it? I have a situation wherein the query string will overshoot the limit set while making a GET http request. Requesting reply at the earliest.

**Comment by cedx** [comment]
It's not possible to make a POST request from Print.js... but you can fetch the POST response as a `Blob`, and pass `URL.createObjectURL(blob)` to the `printJS()` function.
For example (pseudo-code):

```js
const response = await fetch(<endpointUrl>, {method: "POST", body: <body>});
if (response.ok) {
  const pdf = await response.blob();
  const url = URL.createObjectURL(pdf);
  printJS(url);
  URL.revokeObjectURL(url);
}
```

**Comment by aishwaryshukla** [comment]
Thank you for the reply. I used the workaround that you suggested and made completed the workflow. Wouldn't it be great if printJS introduces POST request functionality as well?

**Comment by crabbly** [comment]
@cedx Thank you for posting an example.

@aishwaryshukla Adding support for POST requests would be interesting, but probably not worth the implementation. Many POST requests will require authentication headers, whereas others may require body payloads to be passed with the request. The library would need to support and handle these as well. I'm currently not planning on adding this, but a PR would be awesome.
Closing this issue for now. Thank you.
