### ISSUE TITLE
Elements from the previous page appear on the next page

### ISSUE THREAD

**Issue by kikyoluka** [crabbly/Print.js#443]
Hello, I have a question.
When I print a lot of html, the browser will help me perform automatic paging.
But I found that the content of the first page is normal, and there is an error on the second page.
The second page contains the content of the first page. The third page contains the contents of the second page and the first page.

I use Win10 and Chrome browser, and This is my code:

```
Print.onclick = function () {
    printJS({
        printable: "printmain",
        type: "html",
        css: '/css/printjs.css',
        scanStyles: false
    });
};
```

**Comment by crabbly** [comment]
Hey @kikyoluka, my guess is that this could be fixed using CSS media queries. The library doesn't control the resulted pages, it just passes the targeted HTML into an iframe, including the passed in stylesheets, and dispatch a print job on that iframe. From there, the browser is the one that decides how to allocate the HTML into different pages. My recommendation is to create print media queries with CSS, either in the current stylesheet or a dedicated one for printing, and pass that to the lib. Hope this help.
