### ISSUE TITLE
Apparently Firefox should have fixed the long-standing bug that prevented pdf printing - add support for pdf printing in Firefox?

### ISSUE THREAD

**Issue by galzetta** [crabbly/Print.js#448]
The bug that prevented Firefox from printing iframe contents is **allegedly** fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=911444 .

Can we know whether this is actually true and if so would it be possible to add pdf printing support for Firefox too?
From what I read it seems the only difference from Chrome is that the iframe cannot have `display: none` but must use `visibility: hidden` and its size must be big.

**Comment by FelixSchwarz** [comment]
I think this issue is the same as #431

**Comment by crabbly** [comment]
Hey @galzetta, I haven't looked into the bug resolution by Firefox yet. I'll jump into it. 

I'll close this issue since it duplicates #431, as mentioned by Felix. Please follow that thread instead.
