### ISSUE TITLE
Is it possible to Auto Save pdf file instead of print preview?

### ISSUE THREAD

**Issue by alvnrapada** [crabbly/Print.js#449]
When opening my app on a mobile browser and clicking the download button that triggers my js code for print-js, some mobile phones with lower version doesn't support print preview, I am thinking having an auto save option would be better for that. Thanks.

**Comment by crabbly** [comment]
@alvnrapada The purpose of the library is to help with printing, it doesn't have a save feature. It also doesn't handle the print preview, it just sends the job to the user browser.
