### ISSUE TITLE
http://printjs.crabbly.com/#cdn code snippets contain weird lines

### ISSUE THREAD

**Issue by KoichiSenada** [crabbly/Print.js#45]
There are three code snippets within the "Download and install" section at http://printjs.crabbly.com/#cdn
And every time I refresh the browser page their content changes!
Sometimes they contain console command lines, sometimes they contain HTML markup sources.
But they are totally supposed to be stable, while in fact they are not.
What causes such behavior?

**Comment by crabbly** [comment]
Hey @KoichiSenada , I see it. This is horrible. It must be the template I'm using to color style the snippets. We have to change that.

**Comment by crabbly** [comment]
I removed the styling lib from the docs page and the issue was resolved. Thank you @KoichiSenada
