### ISSUE TITLE
How to cancel printing time and text

### ISSUE THREAD

**Issue by fengzhihenxs** [crabbly/Print.js#454]
hi, is there a way to remove the header, do not use the header when printing
![Inked2_LI](https://user-images.githubusercontent.com/37610470/87379275-6c541b00-c5c2-11ea-9d73-741619e3f730.jpg)

**Comment by crabbly** [comment]
Hey @fengzhihenxs, this controlled in the user's browser settings and can't be manipulated with Javascript alone. A work around would be to create a PDF file first, and print that instead. Good luck.

**Comment by rajhim** [comment]
print({ printable: 'printReport', type: 'html', 
                                    maxWidth: 2500,
                                    targetStyles: ['*'],
                                    style:  '@page{ size:  auto;margin: 0mm; }'
                                });

By adding style we can remove header and footer;
