### ISSUE TITLE
Works in Browser, but same code hangs in electron app

### ISSUE THREAD

**Issue by aashutoshrathi** [crabbly/Print.js#455]
```js
const base64Pdf= await fetchPDF()
printJs({ printable: base64Pdf, type: 'pdf', base64: true })
```
This code evokes print in the browser window and prints the correct file, while in an electron app this hangs the application and produces a corrupt pdf file.

**Comment by crabbly** [comment]
Hi @aashutoshrathi, the library is intended to work with browsers. An electron app may require us to target a different API to dispatch the print job. Good luck.
