### ISSUE TITLE
HTML Printing isn't working in IE 11

### ISSUE THREAD

**Issue by k1smet333** [crabbly/Print.js#457]
It isn't possible to use HTML printing in IE 11.

This console error shows up:
SCRIPT5009: 'Symbol' is undefined
print.js (1,11018)

This also happens at http://printjs.crabbly.com/ in the HTML printing section.

As far as i know is the 'Symbol' data-type not compatible with IE 11.

Thanks

**Comment by waiaan** [comment]
same issue

**Comment by kikyoluka** [comment]
same issue + 1

**Comment by kikyoluka** [comment]
> 同样的问题 # 1
> `t.childNodes[Symbol.iterator] is not a function`

Ah, I solved my problem because Symbol.iterator cannot iterate objects, so just add Array.from() in front of it, like this `Array.from(t.childNodes)[Symbol.iterator]`

**Comment by clementchi** [comment]
same issue here. Can this be fixed soon? Thank you.

**Comment by crabbly** [comment]
Hey guys, HTML printing in IE 11 is now working with the lib latest version. Please run `npm update print-js` to get it.
Thank you.
