### ISSUE TITLE
Uncaught DOMException: Blocked a frame with origin 

### ISSUE THREAD

**Issue by netsystemsrl** [crabbly/Print.js#459]
hi,
with last update of chrome there is this error when printing PDF

print.js?v1.0.61:1 Uncaught DOMException: Blocked a frame with origin "https://printjs.crabbly.com" from accessing a cross-origin frame.
    at d (https://printjs.crabbly.com/print.js?v1.0.61:1:2207)
    at HTMLIFrameElement.o.onload (https://printjs.crabbly.com/print.js?v1.0.61:1:2015)

**Comment by crabbly** [comment]
Hi @netsystemsrl , the different port number will trigger the CORS error. The site was accessed through port 80 but the pdf is being retrieved through port 2015. Make sure they are both on the same port (80) and the issue should be fixed. Thank you.

**Comment by netsystemsrl** [comment]
try on site https://printjs.crabbly.com/
print button ... 
with chrome I have this error

**Comment by crabbly** [comment]
Just tested the site / docs page using Chrome 84 without any issues. The different ports shouldn't really be affected by a browser version. Maybe a configuration somewhere or proxy on your local environment. Good luck
