### ISSUE TITLE
Is print.js support Tiff image format?

### ISSUE THREAD

**Issue by priyank-ss** [crabbly/Print.js#463]
I have tried to print images by using **print.js** library and it's working fine. Now I want to print the **Tiff images**. so want to know if print.js supports the Tiff images. and if not then is there any workaround to print Tiff images using print.js? 

Any help much appreciate!!

**Comment by JandersonConstantino** [comment]
Hello @priyank-ss,
How do you do to render Tiff images in unsupported browsers?

**Comment by JandersonConstantino** [comment]
I'm asking because Tiff images are supported by Safari Browser,
so the lib works fine with Tiff images in Safari.

**Comment by crabbly** [comment]
Hey @priyank-ss, the library does not support Tiff files. We are probably never going to add this to the lib because of weak browser support, as explained by Janderson.
Thank you.
