### ISSUE TITLE
Using npm to install

### ISSUE THREAD

**Issue by NoelRorke** [crabbly/Print.js#469]
When running npm install pint-js --save on Windows 10, I get an error that says the packge.json file can't be found.
Can anybody help me resolve this issue as I've never used NODE.js before?

**Comment by crabbly** [comment]
Hey Noel, you first must setup a `package.json` config file for your application. There are lots of information online about it, but maybe this could be a staring point:
https://www.w3schools.com/whatis/whatis_npm.asp
Hope it helps.
