### ISSUE TITLE
Is Multiple pdf files print possible?

### ISSUE THREAD

**Issue by qkreltms** [crabbly/Print.js#476]
I've got pdf files something like these : pdf/dummy1.pdf, ..., pdf/dummyN.pdf
and tried below, but seems not works. Is Multiple pdf files print possible using other ways?
```
  printJS({
      printable: ['pdf/dummy1.pdf', 'pdf/dummy2.pdf', 'pdf/dummy3.pdf', ...]
      type: 'pdf'
    });
```

**Comment by crabbly** [comment]
Hi @qkreltms , the library doesn't not support multiple pdf documents in one print job. Please see these other issues for more details: #462, #458, #215, #403

**Comment by qkreltms** [comment]
Oh thanks for quick reply. I should merge pdf files into one file and print this using some library.
