### ISSUE TITLE
Use HTTPS to load PDF and print, and blank paper will appear.

### ISSUE THREAD

**Issue by Arayui** [crabbly/Print.js#477]
I use print-js to print online pdf resource. In my dev env, it works, load pdf successed by https. When I package the project and publish it to online web with HTTPS, it always show a blank page in preview window.

My project based on vue2.
Code:
printJs(url, 'pdf'). Example of URL, 
`https://api.arayui.cn/openapi/export/order?photo=https://v6.etiersoft.com/files/Visitor/HeadImage5b268187beac475e83bed5626c93592c.jpg&no=NO.100001&name=arayui`

I hope to hear from you as soon as possible.

**Comment by crabbly** [comment]
Hey Arayui, sounds like the remote PDF may not be completely loaded before the print job is dispatched by the library. Although the library tries to fetch and cache the PDF locally, in certain cases, it may be better to do that outside the `printJS` call, save the PDF contents to a local blob or pass base64 data to the lib instead. This way, you can make sure the PDF is fully loaded before trying to print it.

Hope this helps.

**Comment by Arayui** [comment]
I analyzed the whole process and found that the size of blobs generated in the dev env was inconsistent with that generated online.When I use axios load the pdf, and create blob by res, it's successed and works.

**Comment by Arayui** [comment]
OK, Where is the entry to deliver the blob? I can load pdf before print.

**Comment by Arayui** [comment]
OK, I converted bolb to Base64. thanks.
