### ISSUE TITLE
Spinner CSS seems to be wrong

### ISSUE THREAD

**Issue by Sylvain** [crabbly/Print.js#481]
Hi! 

It seems that the content of spinner is in fact the content of close button : 
https://github.com/crabbly/Print.js/blob/master/src/sass/partials/_spinner.scss

Am I correct?

**Comment by crabbly** [comment]
Hey Sylvain, nice catch! Looks like we overwrote it when migrating to sass. Thanks for pointing this out. I just pushed a commit fixing it.
https://github.com/crabbly/Print.js/commit/1cc599cdf05126cee267cae638443ec4708c2f47

I'll post an update here once this change is published to npm. Thank you.

**Comment by crabbly** [comment]
This change was published to npm with version 1.4.0. Thank you @Sylvain 🚀

**Comment by Sylvain** [comment]
Great! Many thanks!
