### ISSUE TITLE
Allow to print HTML element without ID (direct reference to the DOM element)

### ISSUE THREAD

**Issue by rjaros** [crabbly/Print.js#483]
Currently you need HTML element with an ID attribute for printing. Please add an option to call `printJS()` with a direct reference to the DOM element.

**Comment by crabbly** [comment]
Hi @rjaros, most modern JS applications don't even fetch the DOM to manipulate elements anymore. Receiving a DOM element seems to me that we are moving backwards. We probably won't be adding this feature to the lib. Using CSS selectors however could be an interesting addition to the lib Api. Hopefully we can add this in the future. PRs are very welcomed. 
For now, please add an id to your element and that should do it. Good luck.

**Comment by rjaros** [comment]
If I could just add an ID I wouldn't fill this issue :-) 
There are still use cases, when you just don't have full control over the generated html markup. But of course it's your decision - I'll try to workaround the problem in a different way.
