### ISSUE TITLE
TypeError: win is null 

### ISSUE THREAD

**Issue by kruczekdawid** [crabbly/Print.js#485]
Browser: Firefox 81.0
OS: Windows 10

`TypeError: win is null`

Following error sometimes occurs in `src/js/init.js`:

```
if (params.onBrowserIncompatible() === true) {
  let win = window.open(params.fallbackPrintable, '_blank')
  win.focus()
  if (params.onPdfOpen) params.onPdfOpen()
}
```

**Comment by crabbly** [comment]
Hey @kruczekdawid, the library now supports PDF print jobs with Firefox. Please run `npm update print-js` to get the latest version. Currently 1.4.0. The only browser that PDF print is not supported is Internet Explorer.

Here is the current browser compatibility table:
https://printjs.crabbly.com/#browsers

Please let me know if any other issues. Thanks.
