### ISSUE TITLE
"Save As" dialog box is popping up instead of the print dialog box

### ISSUE THREAD

**Issue by clayyy123** [crabbly/Print.js#489]
I am incorporating the print js library with electron/react.  For some reason, the Save As dialog box is popping up instead of the print dialog box. 

`print({ printable:[BASE64DATA], type:'pdf', base64: true })`
this is the function I am passing into the OnClick listener. Electron uses the Chromium engine so I am assuming it is compatible.  Thanks for the help!

**Comment by crabbly** [comment]
Hey @clayyy123, the library is not tested in Electron apps. It is made for the browser environment. Even if Electron is using chromium engine, the exposed Api could be quite different. As of right now, I would just assume that the lib is not compatible. We will need to dedicate some development time to tweak it and properly target that environment. I hope we can do that in the future. PRs are very welcomed! :)
Sorry I couldn't be of much help. Thanks for reporting this.

**Comment by clayyy123** [comment]
Thanks crabbly!
