### ISSUE TITLE
Print lost when preview do not load fast enough and the browser is closed

### ISSUE THREAD

**Issue by asfernandes** [crabbly/Print.js#493]
We have a case that a Windows application opens a browser window and this window asks printjs to print a pdf file.

After receive `onPrintDialogClose` the window (and hence the whole browser - which was closed before) is closed.

In the real case, the pdf is a small file and when the user clicks (or type enter) very fast on the print button in the preview dialog (before the PDF is loaded in the preview) the document is not printed.

I have able to consistently reproduce this problem with large pdfs which takes more time to load.

Also I did tests not closing the browser, but the tab and I see an alert about problem when printing the file. (In Portuguese: "Ocorreu um erro durante a impressão.  Verifique a sua impressora e tente novamente.")

Could you add another event that fires only after the document is sent to the printer?

Browser tested: Chrome
printjs versions tested: 1.0.63 and 1.5.0

**Comment by crabbly** [comment]
Hey Adriano, that's an interesting scenario. Currently, the `onPrintDialogClose` will trigger once the dialog is closed, exactly what the prop name says. However, I'm would assume the browser is processing the print job in the background, sending it to the printer. My guess is that if we close the browser before that is complete, the job will fail. As you mentioned, this will be easier to replicate with larger files for obvious reasons.

If that's the case, I'm not sure we can communicate with the browser to wait for that transfer to finish. The only event I can think of, is the `onafterprint`, which In fact I have been playing with lately in a separate branch. I was thinking about using it with the lib.

The only problem I had with it so far, is that it didn't work for PDF jobs. It seems to trigger based on DOM elements being targets, but it doesn't work in the iframe when the src is pdf. At least, I haven't been able to make it work yet.

That said, even if we make this work with PDF print jobs, and somehow is better than the current implementation, I'm still not sure if the event is actually thrown after the transfer is complete. My guess is that it is right after the dialog is closed.
 
From the event MDN docs:

> These events are raised after the user prints, or if they abort the print dialog

Ref:
https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onafterprint

**Comment by varshapwalia** [comment]
I can confirm the `onPrintDialogClose` has stopped working with the latest chrome version(Version 86.0.4240.75 (Official Build) (64-bit)) and skipping this function call altogether.

**Comment by crabbly** [comment]
I just tested the `onPrintDialogClose` callback with chrome v86 and it seems to work as expected. Looks like the issue here is due to the window getting closed.
