### ISSUE TITLE
too much blank pages

### ISSUE THREAD

**Issue by ulantiger** [crabbly/Print.js#498]
Hello there,

I am trying to print the HTML element, which has charts (Chartjs). It was working OK when I used ver 1.0.59 of Printjs. But there was a problem with saving a new file if there was a file with the same name(actually overwriting the existing file). 
Now I upgraded to 1.5? and getting too many blank pages, when actually there is only a page. 
I can send you the source code if you need.
Thanks 
Regards, Ulan

**Comment by crabbly** [comment]
Hey @ulantiger, it's impossible for us to know what the problem actually is without some code. I just tested some examples printing HTML and it seems to be working fine. The lib also support canvas, so printing charts should work as well. 
If you create a codexandbox or fiddle replicating the issue, please reopen this so we can help. Thank you.

**Comment by melloware** [comment]
@crabbly I have this same issue with ChartsJS.  It prints 935 blank pages!  Let me see if I can make a JS Fiddle.

**Comment by melloware** [comment]
@crabbly Here is a JSFiddle showing the issue:

https://jsfiddle.net/qgb09xk8/

**Comment by melloware** [comment]
As a note this is fixed in ChartsJS 3.2.0 for those watching this thread.
