### ISSUE TITLE
Print url Blank in IE

### ISSUE THREAD

**Issue by thanhtrantv** [crabbly/Print.js#50]
I'm trying to print on IE and URL is blank
![url blank](https://cloud.githubusercontent.com/assets/5763426/26135382/57cae2a2-3adf-11e7-8f4f-b4e09062b5cf.png)

**Comment by crabbly** [comment]
Hey @thanhtrantv ,
Which IE version and Windows are you using?
It works when tested in Windows 10, IE 11.

**Comment by thanhtrantv** [comment]
i'm using Windows 7, IE 11. So everything must be latest version?

**Comment by crabbly** [comment]
No. But I tested using the latest version. Looks IE won't print images in Windows 7. I will check if it is possible to add support for it.

**Comment by crabbly** [comment]
I'll close this issue and keep #33 as they are both related to browser support. Please update #33 with any browser test results you may have. Thank you.

**Comment by alluria14** [comment]
![image](https://user-images.githubusercontent.com/11032645/54892941-8aec4b00-4e81-11e9-84c2-4fe1afb27496.png)

This is the error that I got when using print-js in Windows 7 and IE 11.
