### ISSUE TITLE
New feature : Report template

### ISSUE THREAD

**Issue by asimengo** [crabbly/Print.js#500]
Hi everybody.

I have just discovered PrintJS and it's marvellous.
I have proposals for new features :
 A- CREATION OF REPORT
 1- Create an template on Json/XML format to draw report, like we can do with Crystal Report (Report Header/Footer, Page Header/Footer, Details), Parameters, Formulas. About Tables, just define structure.
 2- Report can be create by downloading an Application or ONLINE, at the end generate Report file on Json/XML format

B- USE OR REPORT
 1- We can load report template on one folder on our Web Application
 2- Call PrintJS with below parameters (reportname, data ), data will be an structure to specify table and data

The reason I ask here it's because PrintJS can already do a lot of thing, but now we need to manage Paging, and it will be possible to just add an template

ASIMENGO

**Comment by crabbly** [comment]
Hey @asimengo, I'm assuming the templates would be for the JSON printing option. That would indeed be very cool!
I'm not planing to add this in the near future, mostly due to lack of time to maintain the library. But a PR would be welcomed. Thank you for posting this.
