### ISSUE TITLE
"Undefined" text on all cell for printing type='json' with Blazor

### ISSUE THREAD

**Issue by asimengo** [crabbly/Print.js#501]
Hi All,
I am trying to print grid from Blazor, but I have "undefined" on all cell.
Below details:
**Model to call PrintJS**
    public class SFX_PrintJS_Properties
    {
        public string field { get; set; }
        public string displayName { get; set; }
    }
    public class **SFX_PrintJS**
    {
        public string type { get; set; }
        public object printable { get; set; }
        public string header { get; set; }
       public List<SFX_PrintJS_Properties> properties { get; set; }
        public SFX_PrintJS(object poData, List<SFX_PrintJS_Properties> poProperties, string psHeader = default)
        {
            printable = poData;
            type = "json";
            properties = poProperties;
            header = psHeader ?? string.Empty;
        }
   }

  **Method call on Razor Page (PrintEvent)**
    private async Task **PrintEvent**()
    {
        try
        {
            var oData = new List < TData > ();
            oData.AddRange(GridManager.Data);

            var oConfig = new SFX_PrintJS( oData, GridManager.GetPrintJSProperties(), Header);
            await PrintAsync (oConfig);
        }
        catch { }
    } 

   **Method call on Razor Inherit ComponentBase**
         protected async Task PrintAsync(SFX_PrintJS poConfig)
        {
            string sIdentifier = "PrintJS.NewPrint";

            try { await moJSRuntime.InvokeVoidAsync(sIdentifier,  poConfig); }
            catch { }
        }

 **Javascript Page**
window.**PrintJS** = {
    **NewPrint**: function (poConfig) {
        printJS(poConfig);
    },
};

**Final Result**
![image](https://user-images.githubusercontent.com/73651572/97697748-bb598980-1aa7-11eb-8a11-53cb8ab2d0d4.png)

Please, What I am doing wrong?
It's because I have to allow JS to call dotnet Method to retrieve data?

Thanks all for your help.

**Comment by crabbly** [comment]
Hey @asimengo, all you need to make sure is to pass valid JSON data into the `printJS` function. The documentation page has some examples, but you can also look into the manual test examples here available in the repository:
https://github.com/crabbly/Print.js/blob/master/test/manual/index.html#L77
Hope this helps.
