### ISSUE TITLE
Download link

### ISSUE THREAD

**Issue by liuxiachanghong** [crabbly/Print.js#502]
Your page [https://printjs.crabbly.com](https://printjs.crabbly.com) has the download button but the link is directing to:
[https://github.com/crabbly/Print.js/releases/tag/1.5.0](https://github.com/crabbly/Print.js/releases/tag/1.5.0)
But it should be:
[https://github.com/crabbly/Print.js/releases/tag/v1.5.0](https://github.com/crabbly/Print.js/releases/tag/v1.5.0)

**Comment by crabbly** [comment]
Hey @liuxiachanghong, thank you so much for reporting this. 🥇 
Just pushed a commit updating the documentation page. Should be fixed now.
