### ISSUE TITLE
Custom timeout on download PDF

### ISSUE THREAD

**Issue by Trotten** [crabbly/Print.js#506]
I can't find the option to set a timeout for pdf download. I tried to insert a req.timeout in the source code (at line 1188), but it didn't work. Without a timeout, if the server where the pdf resides took a long time to return the file (due to an internal slowness), I would not have the possibility to abort the download

**Comment by crabbly** [comment]
Hi @Trotten, the lib tries to preload the PDF before triggering the print job, but it that doesn't seem to be working, I would recommend fetching the PDF file first, and them pass a local blob or base64 data into the library. It should support both. This will give you better control over that request, allowing your code to confirm the document availability before dispatching the print job using the library. Hope this helps.
