### ISSUE TITLE
Not Working on IE

### ISSUE THREAD

**Issue by samee1985** [crabbly/Print.js#516]
![image](https://user-images.githubusercontent.com/49100200/100585720-028ba200-3314-11eb-929f-c53bb00dce0b.png)
its worked on chrome. but not in IE

**Comment by crabbly** [comment]
Sounds like the issue is how the lib is being imported. Looks like the `printJS` function isn't available in the IE environment. If you post more info, including a fiddle or codesandbox, I could help more. Thank you.
