### ISSUE TITLE
我想要实现批量打印图片及其他表单参数怎么实现？

### ISSUE THREAD

**Issue by lucangshiyu1** [crabbly/Print.js#518]
[
![image](https://user-images.githubusercontent.com/59046922/101625780-e811a100-3a56-11eb-8067-1a35a20854a7.png)
](url)
如图type选择image只能按照图片路径来打印图片，我还想添加表单的其他参数一起打印，并且实现一键批量打印，怎么实现啊

**Comment by TONGREN6** [comment]
如果选择html的话，可以单个页面打印，但是我要批量打印怎么实现

**Comment by chenrui0704** [comment]
循环页面即可

**Comment by crabbly** [comment]
Unfortunately I don't speak Chinese, therefore I had to use a translator. If I understood your question correctly, if you pass multiple images to the lib for image printing, it will aggregate them into a single page unless they don't fit, therefore using a 2nd or even more pages to print all the images. However, you can just use CSS to style the images and fit one per page, which I believe will achieve what you are trying to do. It may be as simple as targeting the `img` tag with either the `style` or `css` parameters. Hope this help.
