### ISSUE TITLE
PDF printable URL starting with ? fails

### ISSUE THREAD

**Issue by aj4mq** [crabbly/Print.js#519]
Background: I am using the same PHP script to generate the documents on the fly as is requesting the document. I have PHP that generates JS for very dynamic and more secure sites.

Took a while to figure it out, since the error routine doesn't seem to be triggered... If you're link isn't in the root directory, you need to change **printable: URL** to **document.location.href.split("?")[0] + URL** in your request.

Hope this helps someone else.

**Comment by crabbly** [comment]
Hey @aj4mq , the lib lives in the JS environment, therefore is has no knowledge of back-end code. We can either use a full or relative url and it should work as expected. Thank you.
