### ISSUE TITLE
Option to ignore HTML elements

### ISSUE THREAD

**Issue by Aloogy** [crabbly/Print.js#52]
Is there a way to ignore certain other HTML elements whilst using the html type? 

I'd like to be able to print a DIV however there is one particular element I'd like to ignore.

**Comment by crabbly** [comment]
Hey @Aloogy , the library doesn't have this feature. Interesting idea though. Maybe we could implement it.

**Comment by echan00** [comment]
same here, this would be a feature I could use

**Comment by crabbly** [comment]
Thinking about implementing this. 
How about adding an option within the html function to pass an array of `ids` for the elements that are supposed to be ignored?

**Comment by echan00** [comment]
Yes that would work. So this array of ids are children of the element id (to print)?

**Comment by crabbly** [comment]
Correct.

**Comment by echan00** [comment]
Awesome, let me know and i'll test it.

**Comment by crabbly** [comment]
Just publish this feature to npm. You can run `npm update print-js` to get it.
I'll be adding it to the documentation page. We now have an extra parameter `ignoreElements`, which accepts an array of html element ids that we can tell the library to ignore when printing a parent element.
For ex.:
```
  printJS({
    printable: 'printElementId',
    type: 'html',
    ignoreElements: ['elementIdToIgnore', 'anotherElementIdToIgnore']
  })
```

Here is a fiddle as a example:
https://jsfiddle.net/crabbly/tr8btp3s/

**Comment by KeerthanaNP** [comment]
ignoreElements are not working when we set scanstyles to false. Is there any particular problem with this?
