### ISSUE TITLE
how can print file via Blob()

### ISSUE THREAD

**Issue by morijenab** [crabbly/Print.js#521]
Hello 
AS is see most of the Doc is about how to print a file by its url. But as this issue  https://github.com/crabbly/Print.js/issues/316
I decided to download file via blob and then print the file.
here is what I have done :
```js
 const file = new Blob([responses.data], { type: "application/pdf" });
 printJS(fille);
```

but I got the error.

**Comment by matiasgabrielgarcia** [comment]
Hi there !

You need to pass an URL.

```javascript 
printJS(URL.createObjectURL(file))
```

**Comment by VitaliyBelyy** [comment]
Is there any way how to configure the file name on saving for this case? Property documentTitle doesn't work

**Comment by morijenab** [comment]
> Hi there!
> 
> You need to pass an URL.
> 
> ```js
> printJS(URL.createObjectURL(file))
> ```
there is an outstanding issue https://github.com/crabbly/Print.js/issues/316 about this way.
also as I saw in the doc and code we can pass file to the function.

**Comment by crabbly** [comment]
Hey @morijenab, as @matiasgabrielgarcia you can just pass the URL. About the `documentTile` issue, as @morijenab mentioned, we currently have an issue open for that, hopefully we can fix it in the near future. Will close this since #316 is open for the document title issue. Thanks.

**Comment by crabbly** [comment]
The open issue related to the filename control is actually #487.
