### ISSUE TITLE
printJS('url') 无效问题及解决方案

### ISSUE THREAD

**Issue by remi-hitonotora** [crabbly/Print.js#522]
本人有幸在项目中使用print.js,在问题前先感谢crabbly的提供.
问题是发生在 网络较差的情况, 网络好的可以通过浏览器F12 打开开发者页面把Online设置为 Slow 3G 或 Fast 3G来模拟网络较差环境,
由于源码中是使用 appendChild 在页面的Elements 中添加id为 printJS的一个元素节点, 在较差网络环境的情况下多次点击按钮触发printJs() 方法后  会在页面Elements 出现多个 id为 printJS的节点,此时使用printJS便会无效.
解决方案有2个.
第一种比较简单的就是通过浏览器刷新来清除多余元素节点.
第二种也是本人所使用的解决方案 就是在调用 printJS之前来循环清除节点达到效果, 代码大概如下
`let iframe = document.getElementsByTagName('iframe');`
                `  for (let i = 0; i < iframe.length; i++) {`
                    `if (iframe[i].getAttribute('id') === 'printJS') {`
                      `document.body.removeChild(iframe[i]);`
                   ` }`
                  `}`
但是这种方案也有一些问题, 就是清除的节点与拿到的节点数量不对应, 多点几次就能解决.

**Comment by crabbly** [comment]
Hi @remi-hitonotora, unfortunately I don't speak Chinese and had to use a translator, but if I understood it correctly, you could just disable the UI print button once its clicked to prevent the user from clicking it multiple times, and then enable it back using the lib `onPrintDialogClose` hook. I can think of a couple of other options but this would be my first try. Hope this help.
