### ISSUE TITLE
Firefox Warning: The PDF is not fully loaded for printing

### ISSUE THREAD

**Issue by thomanimation** [crabbly/Print.js#527]
Print-js: 1.5.0

Firefox: 84.0.2

File:  PDF with ~2MB per page.

Result: Firefox Warning: "The PDF is not fully loaded for printing" and a white page is printed.

In Chrome it prints fine.  Also the Firefox viewer prints it fine.

**Comment by egonvb** [comment]
Same Issue here,

PrintJS 1.5.0
Windows 10
Firefox 85.0.2

PDF is loaded through through ajax and added to printJS as base64 encoded string. file 750Kb

**Comment by crabbly** [comment]
The lib tries to pre-load the PDF before dispatching the print job, but somehow, this isn't very stable with Firefox. It's a simple HTTP request and cache, not sure what else we could do within the lib as an alternative to this. Until very recent, we couldn't even print PDF documents in Firefox, so I guess I can't complain much. 

For now my recommendation is to cache the PDF as a local Blob before dispatching the print job with the library. This would give you better control of the file availability and fix the issue with Firefox. Just make sure to pass the local Blob URL a and not the Blob itself, and the lib will print it as expected. 

Hope this help.

**Comment by swistak** [comment]
I've been experimenting with similar method, and found that increasing timeout on setTimeout from `1` to `1000` seems to work even for quite heavy objects.

**Comment by thomanimation** [comment]
thanks, I increased it to 2000 because I had trouble with 1000!
