### ISSUE TITLE
how to  calculate  onePageRow? 

### ISSUE THREAD

**Issue by zhangzhangxq** [crabbly/Print.js#531]
If the table row content is dynamic, If the table row content exceeds 100% of the row，the table page is displayed with line breaks 
so ... how to  calculate  onePageRow?   **type="html"**

**Comment by crabbly** [comment]
I'm not sure what would be the best option for this, but my guess is that it comes down to just passing a custom style with the `style` param or even a print stylesheet with the `css` option. Using css you should have full control of your table layout, including how to react to dynamic data. Hope this help.
