### ISSUE TITLE
how to print on labelprinter

### ISSUE THREAD

**Issue by arnold-b** [crabbly/Print.js#533]
Hello, 
how could i scale the printing from picture to a label printer. 
if i choose my brother ql 500,  i get in the preview a very long page and in the center you small testing image. 
on my webpage for one friend i generate labels in perl. for now we copy the image to a word document(12 labels) and print it out. 
in the future we want to use one labelprinter and print it directly one by one
![printout](https://user-images.githubusercontent.com/32824793/106352392-17b88900-62e3-11eb-9d4b-e7958e233db4.png)

thanks

**Comment by crabbly** [comment]
Hey @arnold-b, you may want to pass in a custom `style` option or even a whole print stylesheet with the `css` option to control the image size. Maybe as easy as targeting the `img` tag. Hope this help.
