### ISSUE TITLE
Print Multiple HTML Elements

### ISSUE THREAD

**Issue by gzzluis07** [crabbly/Print.js#536]
Is it possible to print an array of HTML elements at one time?  Similar to the way the library can print an array of images?

**Comment by crabbly** [comment]
Hi @gzzluis07, not at this moment. The library accepts one HTML element only. Could be an interesting feature to explore in the future though. An MR would be welcomed. Thank you.

**Comment by dongji0903** [comment]
I hope, when 'type' is 'html', 'printable' can accept css selector instead of element's id.
Then in html.js, replace document.getElementById into document.querySelectorAll.
