### ISSUE TITLE
HTML Printing does not apply any css styles from the page

### ISSUE THREAD

**Issue by theGrower** [crabbly/Print.js#537]
Using Fomantic-UI/Semantic for styling across the site. I'm trying to print a modal and it also uses the Fomantic Grid system and no styles are applied at all to the HTML. When I attempt to add specific style sheets this does not appear to have any impact on print styling whatsoever. 
`printJS('modal-id', 'html');`
No styles
`printJS({printable: 'modal-id', type: 'html', scanStyles: true });`
No styles
`printJS({printable: 'modal-id', type: 'html', scanStyles: false, css: ['path/to/css.css', 'path/to/another/css.css']});`
Still no styling. 
`printJS({ printable: 'course-quiz-modal', type: 'html', targetStyles: ['*'] });`
Still nothing... 

EDIT: It is applying some styles, because with `scanStyles: false` it is a little different. i.e. some horizontal components are now vertical. However, all styling is just so minimal. 
If I do: 

`printJS({ printable: 'course-quiz-modal', type: 'html', scanStyles: false, targetStyles: ['*'] });`
I get a lot more styling; however, the left margin starts the printing half way across the page and runs off the right side of the page. Additionally, there are issues with z-index as some content is hidden behind some wrapper containers. 

This is a project where the front-end is also done in Vue.js.

**Comment by crabbly** [comment]
Hi @theGrower, using the `css` option with `scanStyles` set to `false`, your third option above, is preferred and should work. My only guess is that the stylesheets are not getting preloaded correctly before the print job is dispatched. If they are external stylesheets, you could cache them with the user's browser before sending dispatching the print job. Hope this help. If you can replicate the issue within a codesandbox or fiddle, I could look more into it.
