### ISSUE TITLE
http error handling

### ISSUE THREAD

**Issue by camilova** [crabbly/Print.js#55]
Hi,

Is there a way to control when server responds, for example, code "404 not found", when I attempt to request a PDF (they are generated dinamically from server) ?

I have tested, and it shows a print preview for a "404 not found page". It should be very ussefull if it can call a callback when some error occurs.

thanks a lot.

**Comment by crabbly** [comment]
Hi @camilova , currently, there isn't a way for a callback. I love the idea though, we should implement this into the library.

**Comment by camilova** [comment]
How can I help to that ? How can I contribute?

**Comment by crabbly** [comment]
I don't have any pointers on that. But fee free to propose a implementation. Or submit a PR.

**Comment by Neobugu** [comment]
For "fast" answer you could make an ajax request to validate if content is online such as

```
$.ajax({
    type: 'HEAD',
    url: 'http://yoursite.com/page.html',
success: function() {
        // page exists
},
error: function() {
        // page does not exist
}
});
```
maybe not quite accurate but could help

**Comment by crabbly** [comment]
I won't be implementing this feature because of my limited time to work on this library. A PR would be welcome.

If there is a chance that the pdf file could not exist, I would recommend checking if the file exists before passing it to the `printJS` function.
