### ISSUE TITLE
Css Url path not working.

### ISSUE THREAD

**Issue by Gicehajunior** [crabbly/Print.js#555]
I may be wrong but hey, anyone to volunteer and show me how to apply my css file when printing a html format. my css file located on a certain path on the server. tried all means with no avail.

**Comment by fingers10** [comment]
here you go,

Refer your styles and script in index.html page
```html
<link href="css/site.css" rel="stylesheet" />
<script src="js/print.js"></script>
```

then while printing,
```js
printJS({ printable: id, type: 'html', scanStyles: true, css: 'css/site.css' });
```
