### ISSUE TITLE
Print text with form feed

### ISSUE THREAD

**Issue by sbandariyadav** [crabbly/Print.js#56]
Hi,

I want to print text file with form feed. I made some changes and able to print it. But the problem is that I could not do page break even my text file contains form feed.

Please help me in resolving this

**Comment by crabbly** [comment]
Hey @sbandariyadav , the library supports pdf files. Event though it may have worked with text files, it won't understand page breaks when using form feed, unfortunately.

**Comment by sbandariyadav** [comment]
So is there any alternative/workaround for printing text file with page breaks
