### ISSUE TITLE
How Import Print.js in Angular 2

### ISSUE THREAD

**Issue by vishaltps** [crabbly/Print.js#57]
How Can i use it in angular 2 ?

**Comment by crabbly** [comment]
Try this: `import printJS from 'node_modules/print.js/src/index.js';`

**Comment by pedrosimoes-nbr** [comment]
that's ugly :(

**Comment by pedrosimoes-nbr** [comment]
And also needs to activate the allowJs typescript flag: https://github.com/Microsoft/TypeScript/issues/14485

Not cool 👎

**Comment by crabbly** [comment]
@pedrosimoes-nbr  Please explain your comment about importing the package when using angular. As far as I know, there shouldn't be any difference.

**Comment by crabbly** [comment]
@pedrosimoes-nbr Please help. You comments don't make any sense to me.

**Comment by pedrosimoes-nbr** [comment]
The biggest problem is the name of the module: `node_modules/print.js`, the dot between print and js confuses the typescript module import.

Your suggestion was to reference the file directly like this `import printJS from 'node_modules/print.js/src/index.js';` but if you do this you also have to configure the flag `allowJs` for the typescript could accept it, and this was a condition that I didn't want.

And I also had other problems with the integration, I believe that your lib is great but in face of these integration problems with angular I had to implement a solution on my own.

I hope that my comment could help you.

**Comment by joseluisq** [comment]
> The biggest problem is the name of the module: node_modules/print.js, the dot between print and js confuses the typescript module import.

Yep,
In fact, I have the same issue using ES6 import `import PrintJS from 'print.js'`
```
This dependency was not found:
* print.js in ./~/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]]}!./~/vue-loader/lib/selector.js?type=script&index=0!./assets/js/components/mycomponent.vue
```
Adding a dash instead a dot (print-js) it could help!

By the way, this issue it should be renamed.

**Comment by mswaidan** [comment]
I'm having the same issue. Library looks great but am unable to get it loaded due to the . in the name.

**Comment by nsksaisaravana** [comment]
I am getting below error when i call PrintJS in Angular 2

Error: __WEBPACK_IMPORTED_MODULE_5_print_js_src__.a.printJS is not a function

**Comment by tckastanek** [comment]
I had a similar problem using it React. You can work around it by installing it locally and changing the file name to print-js and requiring that. You'll have to be careful and also delete the .js file extension (and may even need to manually copy the files into your node_modules). 
Works, but not ideal.

**Comment by joseluisq** [comment]
@tckastanek I did create an alternative at https://github.com/joseluisq/printd
Maybe It could work for you.

**Comment by crabbly** [comment]
I renamed the library to print-js. Try using npm install print-js --save instead.

**Comment by tckastanek** [comment]
@crabbly The updated name works great! Thank you!

**Comment by embds** [comment]
@tckastanek and @crabbly, how do you use it on your angular 2 project? Can you share sample there?

King regards

**Comment by jackjamieson** [comment]
Importing print-js from a lazy loaded module causes ` Error: Uncaught (in promise): Error: Loading chunk ...` in IE in Angular 2+.

**Comment by subatomicglue** [comment]
```
import printJS from 'node_modules/print.js/src/index.js';
```

where... in my `component`?   in my `app.module.ts`, someplace else?   didn't work for me.  got `_co.printJS is not a function`

**Comment by subatomicglue** [comment]
getting more traction with this in my component:
```
import printjs from 'print-js';
```
and this in the component class definition:
`printJS = printjs;`

and this in the html template:
```
<div class='pointer' (click)="printJS( content_url )">PRINTJS</div>
```
clicking this element then downloads the pdf file...  so...   not that exciting.  ha. :)

**Comment by crabbly** [comment]
You shouldn't do this: `printJS = printjs`, as it overwrites the global `printJS` function.

Just import the library, for ex.: `import print from 'print-js'`, and the function `printJS` will be available in your code.

**Comment by subatomicglue** [comment]
see my earlier bug report, that didn't work, it results in:
```
_co.printJS is not a function
```

this is the import I used at the top of the component:
```
import print from 'print-js'
```

**Comment by subatomicglue** [comment]
To future internet travelers, my problem was adding this line in `typings.d.ts`:
```
declare var printJS: any;
```
I removed, and can now reference printJS from my html template.

**Comment by subatomicglue** [comment]
This is the HTML template which works for me (pops up a modal and print dialog under Chrome/MacOSX).  Works with pdf hosted at Amazon AWS S3 named such as `https://myorganization.s3.amazonaws.com/8aafec21-ff95-ca8z-695g-a7779962df5f_6681153436723` 
```
<div class='pointer' (click)="printJS( {type:'pdf', printable: content_url, showModal: true, modalMessage: 'retreiving...'})">PRINTJS</div>
```

**Comment by crabbly** [comment]
Just published a new version to npm which has proper support for module import.
The library will still expose a global variable `printJS`, but the recommend usage now should be to import the package at the same file where it will be used:

For ex.:

`import printJS from 'print-js'`

`printJS('path-to.pdf')`

Run `npm update print-js` to get the latest version.

**Comment by kamal0912** [comment]
> I fixed my problem with `_co.printJS is not a function`...
> I was adding this line in `typings.d.ts`, which I did as a habit:
> 
> ```
> declare var printJS: any;
> ```
> I removed, and can now reference printJS from my html template.

@subatomicglue  I am unable to resolve thie error. Please help.

**Comment by crabbly** [comment]
Hi @kamal0912, a new version is out with better Typescript support. 
Please run `npm update print-js` to get it. You shouldn't have any issues importing the library.
Thank you.

**Comment by Salmanferozkhan** [comment]
Hi, I'm using AngularJS 6 and using your print-js 
I'm giving on typescript this 
print() {
    printJS('http://www.pdf995.com/samples/pdf.pdf');
  }
means I want to show pdf using the link but it shows print the current page not working URL of pdf

**Comment by ShemaPatrick** [comment]
`import printJS from 'print-js'; works for me
`

**Comment by andrecontdi** [comment]
I'm still having problems importing on TypeScript (Angular 7).

`error TS1192: Module '"C:/Dev/Wash&Iron/wi-frontend-sisad/node_modules/print-js/src/index"' has
no default export`

@crabbly 
I solved changing directly at the end of the index.d.ts  from `export = printJS;` to `export default printJS;`

**Comment by crabbly** [comment]
Interesting. Thank you for the feedback, @andrecontdi 
FYI: https://github.com/crabbly/Print.js/issues/304

**Comment by asfernandes** [comment]
With latest version, see https://github.com/crabbly/Print.js/pull/293

**Comment by rahulswimmer** [comment]
I have installed "print-js": "^1.0.61" for my angular 5 application.

I import the package, like this: 

    import printJS from "print-js"

There is red underline for printJS saying, 
Module '"/Users/printProject/node_modules/print-js/src/index"' has no default export.ts

But, index.js inside src does have a export default printJS.

Because of this, I am not able to build my project, what should I do ?

**Comment by rahulswimmer** [comment]
Solved this issue:

Not only are we suppose to change

    export = printJS to export default printJS

But also the import statement in the component to :

import 'printJS' from 'print-js/src/index'

**Comment by dami95** [comment]
1) `npm install print-js --save` 
2) `import printJS from 'print-js';` in component code
3) tsconfig.json: `"allowSyntheticDefaultImports": true,` option in`compilerOptions`

**Comment by khanhnm222** [comment]
import * as printJS from 'print-js';  workes for me!

**Comment by Trend20** [comment]
>     1. `npm install print-js --save`
> 
>     2. `import printJS from 'print-js';` in component code
> 
>     3. tsconfig.json: `"allowSyntheticDefaultImports": true,` option in`compilerOptions`

Thank you so much. This helped me
