### ISSUE TITLE
Header in image is undefined.

### ISSUE THREAD

**Issue by stirrblig** [crabbly/Print.js#58]
Hi, thanks for a nice plugin.

There is a small issue with header in the Image.print function.
In image.js, row 23 and forward:

      if (params.header) {
        addHeader(printableElement)
      }

When I print using a header, I get a header with the text "undefined".
I think the correct code is to replace the addHeader code with:

      if (params.header) {
        addHeader(printableElement, params.header)
      }

...just like it's done from Html.print.

**Comment by crabbly** [comment]
Thank you, @stirrblig . I'll change it soon. Or if you submit a PR I'll merge it right away. :)

**Comment by crabbly** [comment]
Forgot to update this issue. This has already been fixed. I added an example to the documentation:
http://print.js_docs.dev/#image
