### ISSUE TITLE
printing html element

### ISSUE THREAD

**Issue by chhunly-github** [crabbly/Print.js#60]
I cannot find how to set font for printing

**Comment by jketcham** [comment]
You might have already found this, but the [online docs](http://printjs.crabbly.com/#documentation) show all configurable options and `font` is one of them, which defaults to `TimesNewRoman`.

**Comment by crabbly** [comment]
Hey @chhunly-github , @jketcham is correct. The library uses `TimesNewRoman` as the default printing font, however, you can pass any font you like using the `font` param: http://printjs.crabbly.com/#docs
