### ISSUE TITLE
pdf printing

### ISSUE THREAD

**Issue by chhunly-github** [crabbly/Print.js#61]
I don't know why I always got download when I use the function printJS with pdf file

**Comment by crabbly** [comment]
Hey @chhunly-github , unfortunately the library doesn't support PDF printing in all browsers. Whenever the library doesn't support PDF printing for the user's browser, it will open a new tab instead. Some browsers / settings may however start a download instead. 
http://printjs.crabbly.com/#pdf

Browser support: http://printjs.crabbly.com/#browsers
