### ISSUE TITLE
Print without opening

### ISSUE THREAD

**Issue by AllanDiaz** [crabbly/Print.js#62]
Hello,
I am facing an issue : I need to print a list of PDF, without opening the "print window", because it would open too much windows which is bad for the user experience. Do you think of any solution ? Is it possible to print a pdf without opening this window everytime ?

**Comment by crabbly** [comment]
Hey @AllanDiaz , the library doesn't support this. In fact, I'm not even sure it can be accomplished with JavaScript alone, for security purposes. Imagine if you open a website, and some unknown JavaScript code start printing things to your printer without you having control over it. Not something we would look for :/
