### ISSUE TITLE
Trying to print on thermal printer

### ISSUE THREAD

**Issue by rohitatcoffee** [crabbly/Print.js#640]
`
 const responseBlob = new Blob([pdfBlob], {
        type: 'application/pdf'
      });
      const fileURL = URL.createObjectURL(responseBlob);
      setPreview(false);
      // printJS(fileURL);
      printJS({
        type: 'pdf',
        printable: fileURL,
      });
`

Trying to print a pdf receipt, but it adds empty spaces on top and bottom.

![Screenshot 2022-09-08 at 6 52 40 PM](https://user-images.githubusercontent.com/12725720/189104483-f7e07477-3031-4bf0-934b-c33d277bf5b1.png)

How I can remove these spaces?

Note: PDF does not have margin on the top and bottom

![Screenshot 2022-09-08 at 7 06 00 PM](https://user-images.githubusercontent.com/12725720/189107063-59e7fe5e-e1cc-4f09-a217-9da45e343ecc.png)

**Comment by TingNLP** [comment]
@rohitatcoffee 
try it
https://developer.mozilla.org/en-US/docs/Web/CSS/@page
