### ISSUE TITLE
bower.json have wrong main property 

### ISSUE THREAD

**Issue by fromcouch** [crabbly/Print.js#65]
main property in bower.json would be:

    "name": "print.js",
    "description": "A tiny javascript library to help printing from the web.",
    "main": "./dist/print.min.js",
    
actually my gulp script isn't working with wiredep. If I change bower.json works fine.

Thanks

**Comment by crabbly** [comment]
Hey @fromcouch , that's weird, `src/print.js` should work just fine as the `main` property.
Check the specs here: https://github.com/bower/spec/blob/master/json.md#main

**Comment by fromcouch** [comment]
The link you post says:

> The entry-point files necessary to use your package. Only one file per filetype.

src/print.js not exist

**Comment by crabbly** [comment]
@fromcouch You are correct, we changed `print.js` to `index.js`. `bower.json` must be updated. I'll do it soon. A PR would be welcome. Thank you.
