### ISSUE TITLE
Unable to set a file name

### ISSUE THREAD

**Issue by Orcinuss** [crabbly/Print.js#66]
Would it be possible to add the ability to set the file name for printing. Currently it is `about/blank`. This way people can save the file as a PDF on the print screen with the right file name.

Perhaps this could be an additional option?

**Comment by crabbly** [comment]
@Orcinuss Maybe we could set the iframe document title by receiving it as an additional option.

**Comment by crabbly** [comment]
You can now pass the parameter `documentTitle` which will set as the iframe title and used when saving a PDF file of the print element.

**Comment by MaikkiaM** [comment]
![image](https://user-images.githubusercontent.com/37313886/79548576-f0673700-8095-11ea-9578-856cbd1e83a9.png)


![image](https://user-images.githubusercontent.com/37313886/79548672-12f95000-8096-11ea-96df-01470148ea1f.png)


still not working for me. wheres my Error?

**Comment by galzetta** [comment]
I agree with @MaikkiaM . I'm specifying the PDF with base64 and the documentTitle option gets ignored. The name of the PDF appears to be the name of the data url created with `createObjectURL`. Is there some way to fix this?

**Comment by Buyur** [comment]
I would also agree - not working for me either

**Comment by gabolucuy** [comment]
Anybody has a workaround for this issue?

**Comment by wolfgangschneider** [comment]
Anybody has a workaround for this issue?

**Comment by chriscrowley** [comment]
documentTitle isn't working for me either.

**Comment by dominikPaluch** [comment]
I have the same problem

**Comment by illiabakunovskyi** [comment]
As I see from docs it doesn't have support for pdf files but will be nice if you will add it

**Comment by farrellp43** [comment]
Same problem here

**Comment by dastan0017** [comment]
same problem here

**Comment by danielrose7** [comment]
A fix for this has been opened in #724 — for PDF iframes, Chrome reads `document.title` asynchronously after `print()` returns, so the library now temporarily guards the title with a `MutationObserver` to keep it stable.

Reference implementation as a standalone helper: https://gist.github.com/danielrose7/adb604b9334118d98de6e856efd043df
