### ISSUE TITLE
font size

### ISSUE THREAD

**Issue by radhial222** [crabbly/Print.js#68]
font size dosnt change size if i put some data in "td" element
but its work in "tr" element
any suggestion @crabbly ?

**Comment by crabbly** [comment]
Hey @radhial222 , sorry for not replying. I haven't had time to look into this yet. If you have figured it out, please post it here. Thx.

**Comment by crabbly** [comment]
Hey @radhial222 , I finally took the time to create a fiddle testing this. Something is wrong with your code. The library will change the font size as expected.

http://jsfiddle.net/crabbly/1z10wbce/
