### ISSUE TITLE
when I use firefox, the demo got blank

### ISSUE THREAD

**Issue by neverlous** [crabbly/Print.js#681]
When I check the document with firefox, the "Print base64 PDF" didn't work well , got the blank print preview. But the chrome is ok.
It may be a compatibility problem.

https://printjs.crabbly.com/#documentation
![image](https://github.com/crabbly/Print.js/assets/8750037/ac183d40-9fc3-4e4e-af9c-4e8a7988e370)

The firefox show the blank most of the time, rarely is it normal:
![image](https://github.com/crabbly/Print.js/assets/8750037/0ee62a6a-ba38-4ac4-9fa6-5715ac4f8616)

The chrome show the right:
![image](https://github.com/crabbly/Print.js/assets/8750037/b6c5a196-1477-4f19-b2d5-8a352046e808)

**Comment by neverlous** [comment]
Duplicate with #665

**Comment by Mudassarali222** [comment]
Hi, 
yes you are right, [print-js](https://printjs.crabbly.com/#documentation) is not updated please use this for latest code implementation [print-js-updated](https://github.com/LukasKlement/Print.js)

**Comment by neverlous** [comment]
> 

Yes i have fix it  with print-js-updated

**Comment by neverlous** [comment]
> Hi, yes you are right, [print-js](https://printjs.crabbly.com/#documentation) is not updated please use this for latest code implementation [print-js-updated](https://github.com/LukasKlement/Print.js)

Yes i have fix it with print-js-updated

**Comment by Mudassarali222** [comment]
Ok.
