### ISSUE TITLE
Json printing in IE11

### ISSUE THREAD

**Issue by horiuchie** [crabbly/Print.js#69]
Hi, I'm using your awesome library.

I got the below when json printing in IE11, as if no height has been set at all.

```
someJSONdata = [
    {
       name: 'John Doe',
       email: 'john@doe.com',
       phone: '111-111-1111'
    },
    {
       name: 'Barry Allen',
       email: 'barry@flash.com',
       phone: '222-222-2222'
    },
    {
       name: 'Cool Dude',
       email: 'cool@dude.com',
       phone: '333-333-3333'
    }
 ];
```

↓

![ie11](https://user-images.githubusercontent.com/28750080/28445858-0f7d8d82-6e02-11e7-8341-26a456d4cc99.png)

Although I know the library doesn't support json printing in IE, I think it works in at least IE11 if the flex-basis within "params.htmlData" is set to auto.

Please let me submit the pull request.

**Comment by crabbly** [comment]
Great! Thank you, @horiuchie
