### ISSUE TITLE
Does not work with Edge?

### ISSUE THREAD

**Issue by AnderssonPeter** [crabbly/Print.js#7]
Hi I'm trying to print a embedded PDF in edge, this seems like a impossible task.
I tried your solution and it at least shows the Print dialog but the content is just a big black frame with a small black box in it.
Same happens when I use the example on your page.

![print in edge](https://cloud.githubusercontent.com/assets/1308309/19972245/ad1d33c8-a1e1-11e6-9f13-419e7af32287.png)

**Comment by AnderssonPeter** [comment]
Found a kind of solution, if I use `window.Open("url")`, then wait a long time to ensure that the pdf is loaded. then call `.print()` on the window it works. my problem is that I haven't found any way to detect when its done loading...

**Comment by crabbly** [comment]
@AnderssonPeter Interesting. I haven't had time to look into this yet. I'll post any updates here as soon as I can.

**Comment by Donool** [comment]
Also having issues in Edge when trying to print a remote PDF

**Comment by crabbly** [comment]
I tested and confirmed the issue with Edge. I'll work on a solution for it.

**Comment by lesyk** [comment]
In my case no action executed. IE11.

**Comment by AnderssonPeter** [comment]
@lesyk do you have some sort of PDF application installed? if not then your out of luck as IE11 does not have a native PDF Viewer (Edge does have one).
If https://github.com/crabbly/Print.js/issues/8 is implemented that could be used to disable the button or show a message box instead.

**Comment by crabbly** [comment]
@lesyk The latest version should support IE11. 
https://github.com/crabbly/Print.js/releases/latest
Could you download and give it a try? Please let me know how it goes. 
Thx.

**Comment by AnderssonPeter** [comment]
I think IE 11 has worked all along Edge was the problem..

**Comment by crabbly** [comment]
@AnderssonPeter IE wasn't working before, however it is now with the latest release. 
Unfortunately, Edge is still not working. I'm trying to find a solution for it.

**Comment by sergeychernov** [comment]
Unfortunately IE does not work with 1.0.13 from npm

**Comment by crabbly** [comment]
@sergeychernov Which IE version are you using? And Windows? Thx

**Comment by sergeychernov** [comment]
IE is 11.0.9600.18538
Windows 8.1 Pro
Demo does not work in IE either.

**Comment by AnderssonPeter** [comment]
@crabbly Oh it seems your right it isen't working in IE, my bad.
No matter if a PDF reader is installed or not.
Im using IE 11, i nave no idea what version of `Print.Js` im using.

**Comment by crabbly** [comment]
@AnderssonPeter Yes, it seems like it is not printing PDF in internet explorer and / or edge.
I added a compatibility table to the documentation page.
http://printjs.crabbly.com/#browsers

**Comment by crabbly** [comment]
I'll close this issue and keep #33 as they are both related to browser support. Please update #33 with any browser test results you may have. Thank you.
