### ISSUE TITLE
Supplied parameters do not match

### ISSUE THREAD

**Issue by froodley** [crabbly/Print.js#71]
I was able to get print.js to import into A2 successfully using this path:

import printjs from 'node_modules/print.js/src/index.js'

However, TSLint is preventing it from compiling because "Supplied parameters do not match any signature of call target"

printjs('divId', 'html');

Looking at the code, I see it is because you are using arguments instead of the signature.

**Comment by crabbly** [comment]
Hey @froodley , this is a typescript error, not a javascript / library error. Feel free to fork and change the code to use in your typescript project.

**Comment by froodley** [comment]
To move this library into the A2 era, I would consider exposing a couple of wrapper functions that can be imported instead, with defined signatures for the two different modes of use.

**Comment by crabbly** [comment]
Hey @froodley , I really don't see a need for this. However, if you think this can benefit other developers, please put a PR together and I would consider merging it. Thank you.
