### ISSUE TITLE
modal not print

### ISSUE THREAD

**Issue by hooh88** [crabbly/Print.js#72]
Hi,
my div element is Modal Bootstrap.
but in print page not show elements!

**Comment by crabbly** [comment]
Is the modal `display` style set to `none`? Could you please post the model HTML here? Thank you.

**Comment by manikandanpachaiyappan** [comment]
i'm not able to get modal print. please help me.

here is my code:

<!DOCTYPE html>
<html>
<head>
	<title>print js</title>
	<link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/semantic.css'>
	<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js'></script>
	<script src='https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/semantic.js'></script>
	<link rel="stylesheet" type="text/css" href="print.min.css">
</head>
<body>

<div id="modaldiv" class="ui modal" >

	<button type="ui button" id="button" onclick="printJS('modaldiv','html')">
       Print
 	</button>
  <i class="close icon"></i>
  <div class="header">
    Profile Picture
  </div>
  <div class="content">
    <div class="ui medium image">
      <img src="img/bmw5.png">
    </div>
    <div class="description">
      <div class="ui header">We've auto-chosen a profile image for you.</div>
      <p>We've grabbed the following image from the <a href="#" target="_blank">gravatar</a> image associated with your registered e-mail address.</p>
      <p>Is it okay to use this photo?</p>
    </div>
  </div>
  <div class="actions">
    <div class="ui black button">
      Nope
    </div>
    <div class="ui positive right labeled icon button">
      Yep, that's me
      <i class="checkmark icon"></i>
    </div>
  </div>
</div>

<a class="item ui button" id="logIn">
    <i class="user icon"></i> Log In 
</a>

	


<script src='print.min.js'></script>
<script type="text/javascript">
$(document).ready(function(){
     $('#logIn').click(function(){
        $('#modaldiv').modal('show');    
     });
});


function printHTML() {
	printJS('modaldiv', 'html')
}

document.getElementById ("button").addEventListener ("click", printHTML)



</script>
</body>
</html>

**Comment by manikandanpachaiyappan** [comment]
Hi @crabbly , i agree your answer, but adding the code modal show also creating the same problem.

added snippet please provide some answers with the snippet

https://stackoverflow.com/q/50167483/9739021

**Comment by crabbly** [comment]
Hey @manikandanpachaiyappan , I had answered your stackoverflow question. The issue is with the modal style / css. Currently, the modal div that you are trying to print has a negative `margin-top` style applied. That will create an issue when you print it. You will have to play with your html and css to print that modal correctly. 
ps.: Once the library adds support for css media queries, it will be easier to manipulate print styles in these scenarios.
