### ISSUE TITLE
Printing multiple files in a batch

### ISSUE THREAD

**Issue by mrothenbuecher** [crabbly/Print.js#73]
Hi,

in my use case I want to print multiple Files in batch.

I use follwing code to print:
```
$('#printfiles').click(function(ev){
  // print pdf files
  $('#pdf').children('div').each(function(i, child){
    $child = $(child);
    printJS({printable:$child.data("path")});				
  });
});
```
Because of the async request all the files will be requested at the same time but
only one will be printed.

In my opinion there are three possible solutions:

- giving printjs the option to executed the request sync
- open each file in a blank page
- queue the print requests

**Comment by crabbly** [comment]
Hey @mrothenbuecher , yea, the library currently doesn't support printing multiple files. Not sure if this is even something we should do, as the preview screen has to show to the user for each file. Sounds like a quite annoying user experience. I would code something towards merging the files first into a single file, then printing that one file. This would create one print preview only, providing a better user experience.

**Comment by Andreasbaaserud** [comment]
Hi @crabbly ,

Since this case is still closed, I guess printing of multiple files in a batch is not yet supported?

**Comment by unnikrishnan-r** [comment]
@mrothenbuecher 
I chanced upon this while attempting to do something similar.
As @crabbly  suggested, I ended up merging the pdf files (https://stackoverflow.com/questions/21478738/how-can-we-do-pdf-merging-using-javascript) and then using printJS to print it.

Worked fine.
