### ISSUE TITLE
Print HTML no line feeds between <div> tags

### ISSUE THREAD

**Issue by RoyBradley** [crabbly/Print.js#74]
I'm using bootstrap v3.x when I print a section of a HTML page all <div> (rows) are ignored and printed inline. It looks like it is trying to follow the column layout.

Is there a fix or an option I don’t know about to fix this?

My print button:
```
<button type="button" onclick="printJS({ printable: 'printJS-form', type: 'html' })" class="btn btn-sm btn-danger">
Print Form
</button>

```

**Comment by crabbly** [comment]
Looks like there are currently a few issues with printing html. Not sure why you are getting this behavior. I'll try to work on the library soon and hopefully fix some of these issues.

**Comment by crabbly** [comment]
@RoyBradley Hey Roy, the library now has a new option, `targetStyles` where you can choose to process all applied styles to the HTML element that is being printed.
http://printjs.crabbly.com/#configuration

Here is a fiddle with an example of bootstrap 3.x grid being printed with Print.js:
https://jsfiddle.net/crabbly/rj397t4v/

If you are still having issues, feel free to reopen this.
Thank you.
