### ISSUE TITLE
print polygons

### ISSUE THREAD

**Issue by VuThuyThuy97** [crabbly/Print.js#75]
I tried to print a svg polygon element but printjs didn't print anything. Help me to fix please

**Comment by crabbly** [comment]
I haven't texted printing svg's yet. Not sure why isn't working. I'll try to look into some of these issues soon.

**Comment by crabbly** [comment]
Hey @VuThuyThuy97 , 
I have created a fiddle to test printing svg's and it works as expected.
http://jsfiddle.net/crabbly/eoxo57jo/
