### ISSUE TITLE
HTML Printing is not working on the latest version of chrome

### ISSUE THREAD

**Issue by SleepyFanjo** [crabbly/Print.js#76]
Hi,

I am using the latest version of google chrome (Version 60.0.3112.101 (Official Build) (64-bit)) and the printing html function is not working anymore. I included screenshots from the actual, official demo website to avoid any bug implied by my code and not the library itself.

Apparently it doesn't work too with Edge and IE11.

There is no preview for firefox but it seems to work.

<img width="1011" alt="screen shot 2017-08-22 at 13 27 19" src="https://user-images.githubusercontent.com/6151817/29563418-cb4eba00-873d-11e7-94f0-6755cd552a8d.png">
<img width="1003" alt="screen shot 2017-08-22 at 13 27 45" src="https://user-images.githubusercontent.com/6151817/29563417-cb4e993a-873d-11e7-981e-134fbb632264.png">

**Comment by crabbly** [comment]
hey @SleepyFanjo , thanks for the update. I will try to find out why and hopefully adapt the code to support it again.

**Comment by paragpkulkarni** [comment]
Issue is occurring for the content in div element. It is printing correctly if the content is wrapped in table, tr, td tag.

**Comment by lumeshadow** [comment]
It also doesn't work on Firefox. And it does not work whether content is in a div or in a table.

**Comment by crabbly** [comment]
I'll close this issue and keep #33 as they are both related to browser support. Please update #33 with any browser test results you may have. Thank you.
