### ISSUE TITLE
Print in silent mode default printer

### ISSUE THREAD

**Issue by joaquinsosamartin** [crabbly/Print.js#79]
Hi,

it is possible print in silent mode in default printer without displaying the popup?

Thanks

**Comment by crabbly** [comment]
Hi @joaquinsosamartin , the library can't do a silent print without a browser confirmation / preview. This may not be possible with javascript alone. The reason is probably security. Imagine if you go to a random website, and it automatically sends a 1000 page print job to your printer :(

**Comment by sytpb** [comment]
The reason is probably security.....  but ,   Is there any way to solve this problem ?

**Comment by weixiaoyi** [comment]
Agreed with the maintainer: Print.js (and any pure front-end library) cannot do true silent printing without the browser print dialog. That’s a browser security boundary, not a missing API in Print.js.

If the product really needs silent printing (POS, labels, warehouse), the usual approach is a **local print agent + web SDK**, not another toggle in the page.

We built that path as the npm package [web-print-pdf](https://www.npmjs.com/package/web-print-pdf): the page talks to a local client over WebSocket, and the client sends the job silently (optional printer / paper / scale settings).

That only fits workflows where installing a small local client is acceptable. If you must stay zero-install / browser-only, Print.js + the system print dialog is still the right tool.
