### ISSUE TITLE
Add a fuction to check for support

### ISSUE THREAD

**Issue by AnderssonPeter** [crabbly/Print.js#8]
I currently have a button that executes printJS("Url"), but if you run in a browser that does not have PDF support, IE11 with no PDF reader on the system the button does nothing at all.

So a function that could check if there is PDF support and allowing me to hide my button would be great!

**Comment by crabbly** [comment]
@AnderssonPeter  Love the idea. Will implement. Thank you.

**Comment by moay** [comment]
Any news on that one?

**Comment by crabbly** [comment]
@moay I didn't have time to add this feature yet. I'll post an update here as soon as it is done.

**Comment by crabbly** [comment]
I added a function check for browser support. 
PDF files will open into a new tab if browser is not supported. 
Here is the current browser support status for all features:
http://printjs.crabbly.com/#browsers
