### ISSUE TITLE
JSON PRINT SHOWING  ONLY ONE PAGE

### ISSUE THREAD

**Issue by ianmin2** [crabbly/Print.js#80]
I have a json document with many elements but when I am printing, only one page shows up

I am running the command 
```
         printJS({
                printable: $scope.reports.map(function(d) {
                    return {
                        name: d.name,
                        id: d.id,
                        major: d.major,
                        time: d.time,
                        reason: d.flag.reason
                    };
                }),
                properties: ['name', 'id', 'major', 'time', 'reason'],
                type: 'json'
            });
```

in my AngularJS application.

> **  - Firefox 55.0.2 _ Ubuntu Linux**

**Comment by crabbly** [comment]
Hey @ianmin2 , I finally took the time to look into this. Your issue may be related to your code or data. Maybe the number of items in your JSON data array is paginated. 

Here is a fiddle showing that if you pass any JSON data that requires more than one page, all pages will be printed.
http://jsfiddle.net/crabbly/qdf795v5/
