### ISSUE TITLE
Getting the printed PDF

### ISSUE THREAD

**Issue by aimensasi** [crabbly/Print.js#81]
is there a way we can get access to the pdf file. I mean, after the html is converted to pdf. Can i get that file even before printing.

**Comment by crabbly** [comment]
Hey @aimensasi , the library doesn't convert html to pdf. It just prepares and print it. Some browsers like Chrome will give you a print preview that may have helped you assume that.
However, there are some libraries that help you convert html to pdf using javascript, here is an example, hope it works for you:
https://github.com/MrRio/jsPDF

**Comment by aimensasi** [comment]
thanks for the reply, I tried that library but it does not work in the same way I want it to. 

Thanks anyway.

@crabbly
