### ISSUE TITLE
Can't print PDF files from website in different domain?

### ISSUE THREAD

**Issue by ScofieldYeh** [crabbly/Print.js#82]
I tried below to print pdf files in my Azure blob, the page will be hang on "Retrieving Document..."
Is that because of the cross domain issue? I tried if I put this file on my website works fine.
printJS({ printable: 'http://icefork.blob.core.windows.net/rentselftw/pdf/sample.pdf', type: 'pdf', showModal: true });

**Comment by crabbly** [comment]
Hey @ScofieldYeh , that's correct. It won't print because of the cross domain issue. Since the library uses a hidden iframe to load and print the pdf without opening a new screen or tab, loading a file from another domain isn't supported. Unfortunately.

**Comment by crabbly** [comment]
I found a way to work around the cross domain issue. The solution is already available with the latest version of the library.
Take a look at #95
