### ISSUE TITLE
Angular application production build error

### ISSUE THREAD

**Issue by op01** [crabbly/Print.js#84]
I created an angular application using `@angular/cli`. During development it was fine. But when I built it with a production flag turned on `ng build --prod`, I got an error

```
ERROR in vendor.e2c2049abe5ab17d4902.bundle.js from UglifyJs
Unexpected token: punc ()) [vendor.e2c2049abe5ab17d4902.bundle.js:15098,14]
```

**Comment by khorark** [comment]
Hi. See issue https://github.com/crabbly/Print.js/issues/83

**Comment by crabbly** [comment]
Hi @op01 , as @khorark mentioned, this is the same issue reported in #83. Currently opened. I'll close this (84) / move it to 83.

**Comment by crabbly** [comment]
The latest npm package version won't import ES6 code anymore. This should prevent issues for anybody using compilers that do not read ES6.
