### ISSUE TITLE
Background color for table header row

### ISSUE THREAD

**Issue by aarushreddy** [crabbly/Print.js#85]
Do we have option to provide color to header row of table.i am using Json data to print?

**Comment by crabbly** [comment]
Currently no. Maybe we should add it.

**Comment by aarushreddy** [comment]
can we give borders to header also.

**Comment by aarushreddy** [comment]
Business guys are expecting borders and background color to header

**Comment by crabbly** [comment]
Added optional grid style parameters when printing JSON data. You can style the grid header as well the grid rows.
http://printjs.crabbly.com/#configuration
