### ISSUE TITLE
Uncaught ReferenceError: i is not defined

### ISSUE THREAD

**Issue by vrushali-shirode** [crabbly/Print.js#86]
<!DOCTYPE html>
<html>
<head>
	<title>Print receipt </title>
	
	<script src="js/jquery-1.10.2.min.js"></script>
	<script src="js/print.min.js"></script>
	
	<link rel="stylesheet" type="text/css" href="css/print.css">
	<link rel="stylesheet" type="text/css" href="css/invoice.css">
</head>
<body>
    <div class="invoice-box" id="invoiceTemplate">
        <table cellpadding="0" cellspacing="0" >
            <tr class="top">
                <td colspan="2">
                    <table>
                        <tr>
                            <td class="title">
                                <img src="images/logo.png" style="width:100px; height:100px;">
                            </td>
                            
                            <td>
                                Invoice #: 123<br>
                                Created: January 1, 2015<br>
                                Due: February 1, 2015
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            
            <tr class="information">
                <td colspan="2">
                    <table>
                        <tr>
                            <td>
                                Sparksuite, Inc.<br>
                                12345 Sunny Road<br>
                                Sunnyville, CA 12345
                            </td>
                            
                            <td>
                                Acme Corp.<br>
                                John Doe<br>
                                john@example.com
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            
            <tr class="heading">
                <td>
                    Payment Method
                </td>
                
                <td>
                    Check #
                </td>
            </tr>
            
            <tr class="details">
                <td>
                    Check
                </td>
                
                <td>
                    1000
                </td>
            </tr>
            
            <tr class="heading">
                <td>
                    Item
                </td>
                
                <td>
                    Price
                </td>
            </tr>
            
            <tr class="item">
                <td>
                    Website design
                </td>
                
                <td>
                    $300.00
                </td>
            </tr>
            
            <tr class="item">
                <td>
                    Hosting (3 months)
                </td>
                
                <td>
                    $75.00
                </td>
            </tr>
            
            <tr class="item last">
                <td>
                    Domain name (1 year)
                </td>
                
                <td>
                    $10.00
                </td>
            </tr>
            
            <tr class="total">
                <td></td>
                
                <td>
                   Total: $385.00
                </td>
            </tr>
        </table>
    </div>
    <button type="button" onclick="printJS('invoiceTemplate', 'html')">Print</button>
</body>
</html>

**Comment by crabbly** [comment]
hey @vrushali-shirode , I can't replicate this issue. Are you using the latest version?

**Comment by vrushali-shirode** [comment]
@crabbly yes. I downloaded latest file from http://printjs.crabbly.com/ .

**Comment by crabbly** [comment]
Could you please the complete error log? Looking for the code line where the error occurred. I can't seem to find this, neither replicate the error when printing html.

**Comment by crabbly** [comment]
I don't this error is related to the library. Please complete error log to open this issue again. Thx
