### ISSUE TITLE
Errors 'missing semicolons'

### ISSUE THREAD

**Issue by aarushreddy** [crabbly/Print.js#88]
Downloaded the latest version.  . 22 for grid styles.but when we copied the library it is showing errors 'missing semicolons' and please provide example to use grid attributes.

**Comment by crabbly** [comment]
Please post your code here.

**Comment by aarushreddy** [comment]
![errors](https://user-images.githubusercontent.com/32718908/31582144-6b323256-b199-11e7-95b9-245d8c2a1e25.PNG)

i copied and paste the JS file from given version 1.0.22 for the gridstyle. if we see the attached screen shot it is saying we have errors in Print.min.js. Am i missing anything.

**Comment by aarushreddy** [comment]
Issue is with the eclipse verion. it is showing errors in Juno.
