### ISSUE TITLE
How to make it print preview at larger size

### ISSUE THREAD

**Issue by Vittalks** [crabbly/Print.js#9]
We need to make it print preview at larger size

please me out this

![screen shot 2016-11-15 at 10 06 02 am](https://cloud.githubusercontent.com/assets/3850377/20293313/42e97fe6-ab1b-11e6-868d-9dffd4ebeb67.png)

**Comment by crabbly** [comment]
@Vittalks I'm not sure what you mean by that. Could you please explain?
The print preview screen in Chrome can't be controlled by the library.

**Comment by crabbly** [comment]
Hi @Vittalks , I will close this since it doesn't look like it is an issue with the library. Of course you can reopen and explain, if i didn't understand it correctly. Thank you.
