### ISSUE TITLE
Please Use Window.location.origin instead of window.location.href

### ISSUE THREAD

**Issue by tejamedasani** [crabbly/Print.js#92]
https://github.com/crabbly/Print.js/blob/d2547024966d896b907412654c3d8031eefb8687/src/js/pdf.js#L10

Example:

Current location: www.example.com/inside/path

Printable Path: /printable/awesome.pdf

Actual Url (which contains/renders the pdf) : www.example.com/printable/awesome.pdf

Loading this pdf with feedback ( showmodal: true ) results in two get requests being sent. One of them uses window.location.href which returns a 404 because the url constructed with window.href will be www.example.com/inside/path/printable/awesome.pdf instead of www.example.com/printable/awesome.pdf.

**Comment by crabbly** [comment]
Merged! Thank you
