### ISSUE TITLE
How to print multiple ID content in a HTML page

### ISSUE THREAD

**Issue by ramdsr26** [crabbly/Print.js#94]
EX: 
Need to print only the val1 & val3 contents

<div id="val1">content1</div>
<div id="val2">content2</div>
<div id="val3">content3</div>

**Comment by crabbly** [comment]
@ramdsr26 Hey SakthiRam, the library doesn't support this. I'm not planning on implementing this feature because of my limited time available to work on the library, unfortunately. Hopefully someone can submit a PR.
