### ISSUE TITLE
Want to Repeat Header and Footer in every Page.

### ISSUE THREAD

**Issue by kathirvelkg** [crabbly/Print.js#96]
Hi, 
Thanks for a wonderful library. I am trying to use this library to print Patient Lab report which is in HTML format. I want to repeat a table of 3 rows and 4 columns containing patient and sample detail to be repeated in every page as page header and a line of words as footer in every page. Kindly guide me to achieve this.

**Comment by crabbly** [comment]
@kathirvelkg Hey Kathirvel, the library doesn't not support this. Unfortunately, I'm also not planning on implementing this feature, because of my limited time available to work in it. Hopefully someone will eventually submit a PR for this.
