### ISSUE TITLE
Will create many <iframe> with id="printjs" after multi-times printing call

### ISSUE THREAD

**Issue by tonysmz** [crabbly/Print.js#97]
I found it will create a <iframe> with id ="printjs" on my page everytime when I call the print command, so if I can many times printing action on same page, it will add more iframe in my page, could this iframe be deleted once the printing active is finished?

**Comment by crabbly** [comment]
Hey @tonysmz , the library automatically deletes the the iframe for you, whenever a new print job is created. I have no idea why isn't deleting for you. Are you getting any console errors?

I just tested multiple print options at the documentation page (http://printjs.crabbly.com), and in the end, the html had one iframe only, as expected. Please try printing multiple times in the documentation page and let me know if the same thing happens there as well. Thx.

**Comment by crabbly** [comment]
@tonysmz Anything?

**Comment by crabbly** [comment]
Closing this since I can't replicate the issue. Feel free to post more information and reopen this at any time.
