### ISSUE TITLE
Custom "Loading..." functions

### ISSUE THREAD

**Issue by steveklebanoff** [crabbly/Print.js#98]
The built-in modal feature is great, but for folks who want a consistent "Loading..."  screen throughout their app, it might not fit their needs.

It'd be awesome if you could specify custom onBeginLoading and onDoneLoading functions.  This would allow end-users to use their own "Loading.." modals or loading behavior.

What do you think?  I'd be happy to take a stab at implementing this.

**Comment by steveklebanoff** [comment]
Put in a PR: https://github.com/crabbly/Print.js/pull/99. Let me know what ya think!

**Comment by crabbly** [comment]
I like it. It's a nice option to have. Thank you, Steve.
